In [46]:
import pandas as pd
import numpy as np

df = pd.read_csv('Medicare_Provider_Utilization_and_Payment_Data__Physician_and_Other_Supplier_PUF_CY2017.csv')

In [47]:
df

,National Provider Identifier,Last Name/Organization Name of the Provider,First Name of the Provider,Middle Initial of the Provider,Credentials of the Provider,Gender of the Provider,Entity Type of the Provider,Street Address 1 of the Provider,Street Address 2 of the Provider,City of the Provider,...,HCPCS Code,HCPCS Description,HCPCS Drug Indicator,Number of Services,Number of Medicare Beneficiaries,Number of Distinct Medicare Beneficiary/Per Day Services,Average Medicare Allowed Amount,Average Submitted Charge Amount,Average Medicare Payment Amount,Average Medicare Standardized Amount
0,1003021114,AYUSO,ROSALIA,NaN,"MD, PHD",F,I,4902 QUEENS BLVD,4TH FLOOR,WOODSIDE,...,31231,Diagnostic examination of nasal passages using...,N,32.0,32,32,249.150000,443.224375,195.330000,166.570000
1,1003021114,AYUSO,ROSALIA,NaN,"MD, PHD",F,I,4902 QUEENS BLVD,4TH FLOOR,WOODSIDE,...,86003,Measurement of antibody (IgE) to allergic subs...,N,446.0,11,13,6.850000,14.231502,6.713027,7.016682
2,1003021114,AYUSO,ROSALIA,NaN,"MD, PHD",F,I,4902 QUEENS BLVD,4TH FLOOR,WOODSIDE,...,94010,Measurement and graphic recording of total and...,N,14.0,13,14,42.410000,83.068571,33.250000,28.420000
3,1003021114,AYUSO,ROSALIA,NaN,"MD, PHD",F,I,4902 QUEENS BLVD,4TH FLOOR,WOODSIDE,...,95004,"Injection of allergenic extracts into skin, ac...",N,1472.0,33,33,8.300000,15.344137,6.476957,5.351338
4,1003021114,AYUSO,ROSALIA,NaN,"MD, PHD",F,I,4902 QUEENS BLVD,4TH FLOOR,WOODSIDE,...,99203,"New patient office or other outpatient visit, ...",N,27.0,27,27,126.350000,231.301111,93.996667,81.247037
5,1003021114,AYUSO,ROSALIA,NaN,"MD, PHD",F,I,4902 QUEENS BLVD,4TH FLOOR,WOODSIDE,...,99213,Established patient office or other outpatient...,N,33.0,25,33,84.230000,188.952121,65.938485,57.868485
6,1003027301,BUTT,AHMED,T,M.D.,M,I,1300 THORNTON ST,SUITE 200,FREDERICKSBURG,...,94010,Measurement and graphic recording of total and...,N,13.0,11,13,33.950000,85.000000,20.069231,22.380769
7,1003027301,BUTT,AHMED,T,M.D.,M,I,1300 THORNTON ST,SUITE 200,FREDERICKSBURG,...,94060,Measurement and graphic recording of the amoun...,N,26.0,25,26,57.850000,125.000000,42.336538,46.243077
8,1003027301,BUTT,AHMED,T,M.D.,M,I,1300 THORNTON ST,SUITE 200,FREDERICKSBURG,...,95004,"Injection of allergenic extracts into skin, ac...",N,3241.0,63,63,6.350000,9.000000,4.687513,5.314810
9,1003027301,BUTT,AHMED,T,M.D.,M,I,1300 THORNTON ST,SUITE 200,FREDERICKSBURG,...,95012,Measurement of inhaled nitric oxide gas,N,41.0,36,41,18.110000,35.000000,12.627073,14.239756
10,1003027301,BUTT,AHMED,T,M.D.,M,I,1300 THORNTON ST,SUITE 200,FREDERICKSBURG,...,95117,"Injection of incremental dosages of allergen, ...",N,217.0,20,217,9.700000,32.055300,6.463594,7.531106
11,1003027301,BUTT,AHMED,T,M.D.,M,I,1300 THORNTON ST,SUITE 200,FREDERICKSBURG,...,95165,Preparation and provision of single or multipl...,N,351.0,17,19,12.430000,16.500000,8.355897,9.191937
12,1003027301,BUTT,AHMED,T,M.D.,M,I,1300 THORNTON ST,SUITE 200,FREDERICKSBURG,...,99204,"New patient office or other outpatient visit, ...",N,49.0,49,49,155.940000,280.000000,106.184898,116.235918
13,1003027301,BUTT,AHMED,T,M.D.,M,I,1300 THORNTON ST,SUITE 200,FREDERICKSBURG,...,99213,Established patient office or other outpatient...,N,60.0,49,60,69.430000,90.000000,40.909500,45.466167
14,1003027301,BUTT,AHMED,T,M.D.,M,I,1300 THORNTON ST,SUITE 200,FREDERICKSBURG,...,99214,Established patient office or other outpatient...,N,24.0,21,24,102.180000,140.000000,72.399583,87.634167
15,1003039199,HUTSON,JULIE,A,M.D.,F,I,3290 N WELLNESS DR STE 180,NaN,HOLLAND,...,94060,Measurement and graphic recording of the amoun...,N,23.0,18,23,57.610000,125.000000,35.626087,48.252609
16,1003039199,HUTSON,JULIE,A,M.D.,F,I,3290 N WELLNESS DR STE 180,NaN,HOLLAND,...,95004,"Injection of allergenic extracts into skin, ac...",N,463.0,11,11,6.330000,20.000000,3.975227,5.573197
17,1003039199,HUTSON,JULIE,A,M.D.,F,I,3290 N WELLNESS DR STE 180,NaN,HOLLAND,...,95117,"Injection of incremental dosages of allergen, ...",N,727.0,27,727,9.600000,29.000000,6.247318,7.110028
18,1003039199,HUTSON,JULIE,A,M.D.,F,I,3290 N WELLNESS DR STE 180,NaN,HOLLAND,...,99204,"New patient office or other outpatient visit, ...",N,15.0,15,15,160.370000,210.000000,111.627333,123.538000
19,1003039199,HUTSON,JULIE,A,M.D.,F,I,3290 N WELLNESS DR STE 180,NaN,HOLLAND,...,99213,Established patient office or other outpatient...,N,74.0,45,74,70.970000,90.000000,45.548514,52.574595
20,1003039199,HUTSON,JULIE,A,M.D.,F,I,3290 N WELLNESS DR STE 180,NaN,HOLLAND,...,99214,Established patient office or other outpatient...,N,36.0,28,36,104.590000,135.000000,73.638611,80.306389
21,1003041476,LINDGREN,KEVIN,D,MD,M,I,610 S MAPLE AVE STE 5500,NaN,OAK PARK,...,99203,"New patient office or other outpatient visit, ...",N,20.0,20,20,114.605000,247.250000,81.229500,77.503000
22,1003071713,CARDET GUISASAOLA,JUAN CARLOS,NaN,MD,M,I,13330 USF LAUREL DR,NaN,TAMPA,...,99213,Established patient office or other outpatient...,N,23.0,14,23,80.660000,280.000000,57.532174,52.491304
23,1003080052,CRONIN,JULIA,A,MD,F,I,701 E EL CAMINO REAL,NaN,MOUNTAIN VIEW,...,95004,"Injection of allergenic extracts into skin, ac...",N,613.0,16,16,8.780000,24.000000,6.883524,5.345954
24,1003080052,CRONIN,JULIA,A,MD,F,I,701 E EL CAMINO REAL,NaN,MOUNTAIN VIEW,...,99203,"New patient office or other outpatient visit, ...",N,16.0,16,16,129.270000,316.000000,100.284375,84.754375
25,1003080052,CRONIN,JULIA,A,MD,F,I,701 E EL CAMINO REAL,NaN,MOUNTAIN VIEW,...,99204,"New patient office or other outpatient visit, ...",N,11.0,11,11,193.890000,478.000000,145.258182,123.527273
26,1003080052,CRONIN,JULIA,A,MD,F,I,701 E EL CAMINO REAL,NaN,MOUNTAIN VIEW,...,99213,Established patient office or other outpatient...,N,18.0,17,18,88.270000,215.000000,65.365000,55.373889
27,1003093832,MAJESKI,ELIZABETH,I,MD,F,I,46 MARKFIELD DR,SUITE A,CHARLESTON,...,36415,Insertion of needle into vein for collection o...,N,15.0,15,15,3.000000,13.000000,2.940000,2.940000
28,1003093832,MAJESKI,ELIZABETH,I,MD,F,I,46 MARKFIELD DR,SUITE A,CHARLESTON,...,94010,Measurement and graphic recording of total and...,N,30.0,25,30,33.400000,60.166667,25.467333,28.656667
29,1003093832,MAJESKI,ELIZABETH,I,MD,F,I,46 MARKFIELD DR,SUITE A,CHARLESTON,...,95004,"Injection of allergenic extracts into skin, ac...",N,927.0,17,17,6.150000,9.000000,4.821607,5.345965
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29714,1992890727,EADES,JACK,R,MD,M,I,5223 PAULSEN ST,NaN,SAVANNAH,...,99213,Established patient office or other outpatient...,N,120.0,80,120,70.210000,97.125000,52.540417,55.490833
29715,1992890727,EADES,JACK,R,MD,M,I,5223 PAULSEN ST,NaN,SAVANNAH,...,99214,Established patient office or other outpatient...,N,426.0,159,426,103.520000,153.122066,76.296972,80.821291
29716,1992890727,EADES,JACK,R,MD,M,I,5223 PAULSEN ST,NaN,SAVANNAH,...,99215,Established patient office or other outpatient...,N,77.0,63,77,139.770000,183.311688,106.733766,111.987532
29717,1992901425,KOPYLTSOVA,YELENA,NaN,MD,F,I,9020 5TH AVE FL 3,NaN,BROOKLYN,...,94010,Measurement and graphic recording of total and...,N,27.0,17,27,43.420000,85.000000,30.885556,26.314815
29718,1992901425,KOPYLTSOVA,YELENA,NaN,MD,F,I,9020 5TH AVE FL 3,NaN,BROOKLYN,...,95004,"Injection of allergenic extracts into skin, ac...",N,5310.0,100,101,8.511262,15.000000,6.377653,5.315414
29719,1992901425,KOPYLTSOVA,YELENA,NaN,MD,F,I,9020 5TH AVE FL 3,NaN,BROOKLYN,...,95012,Measurement of inhaled nitric oxide gas,N,14.0,11,14,23.720000,50.000000,18.224286,15.190000
29720,1992901425,KOPYLTSOVA,YELENA,NaN,MD,F,I,9020 5TH AVE FL 3,NaN,BROOKLYN,...,95024,Injection of allergenic extracts into skin for...,N,134.0,17,17,9.820000,18.000000,7.544851,6.189701
29721,1992901425,KOPYLTSOVA,YELENA,NaN,MD,F,I,9020 5TH AVE FL 3,NaN,BROOKLYN,...,99203,"New patient office or other outpatient visit, ...",N,97.0,97,97,129.037216,200.000000,96.331134,84.269897
29722,1992901425,KOPYLTSOVA,YELENA,NaN,MD,F,I,9020 5TH AVE FL 3,NaN,BROOKLYN,...,99213,Established patient office or other outpatient...,N,50.0,35,50,85.993200,150.000000,59.458000,52.170200
29723,1992954390,OGBOGU,PRINCESS,NaN,MD,F,I,2050 KENNY RD,SUITE 2200,COLUMBUS,...,95004,"Injection of allergenic extracts into skin, ac...",N,1730.0,29,29,6.320000,25.000000,4.784306,5.175277
29724,1992954390,OGBOGU,PRINCESS,NaN,MD,F,I,2050 KENNY RD,SUITE 2200,COLUMBUS,...,95115,Injection of incremental dosages of allergen,N,22.0,11,22,8.270000,35.000000,6.195000,6.751364
29725,1992954390,OGBOGU,PRINCESS,NaN,MD,F,I,2050 KENNY RD,SUITE 2200,COLUMBUS,...,99204,"New patient office or other outpatient visit, ...",N,49.0,49,49,160.330000,355.000000,119.511837,124.137959
29726,1992954390,OGBOGU,PRINCESS,NaN,MD,F,I,2050 KENNY RD,SUITE 2200,COLUMBUS,...,99205,"New patient office or other outpatient visit, ...",N,11.0,11,11,202.250000,440.000000,158.560000,164.030000
29727,1992954390,OGBOGU,PRINCESS,NaN,MD,F,I,2050 KENNY RD,SUITE 2200,COLUMBUS,...,99213,Established patient office or other outpatient...,N,13.0,13,13,70.930000,155.000000,51.332308,53.727692
29728,1992954390,OGBOGU,PRINCESS,NaN,MD,F,I,2050 KENNY RD,SUITE 2200,COLUMBUS,...,99214,Established patient office or other outpatient...,N,16.0,14,16,104.530000,230.000000,62.381250,71.372500
29729,1992977896,PYLE,REGAN,C,DO,F,I,120 MIDLAND AVENUE,SUITE #230,GLENWOOD SPRINGS,...,36415,Insertion of needle into vein for collection o...,N,15.0,14,15,3.000000,37.000000,2.940000,2.940000
29730,1992977896,PYLE,REGAN,C,DO,F,I,120 MIDLAND AVENUE,SUITE #230,GLENWOOD SPRINGS,...,94010,Measurement and graphic recording of total and...,N,95.0,56,95,36.740000,150.000000,27.594105,27.226000
29731,1992977896,PYLE,REGAN,C,DO,F,I,120 MIDLAND AVENUE,SUITE #230,GLENWOOD SPRINGS,...,94060,Measurement and graphic recording of the amoun...,N,27.0,24,27,62.550000,291.000000,49.040000,48.390000
29732,1992977896,PYLE,REGAN,C,DO,F,I,120 MIDLAND AVENUE,SUITE #230,GLENWOOD SPRINGS,...,95004,"Injection of allergenic extracts into skin, ac...",N,2116.0,47,47,6.930000,14.000000,5.314967,5.374967
29733,1992977896,PYLE,REGAN,C,DO,F,I,120 MIDLAND AVENUE,SUITE #230,GLENWOOD SPRINGS,...,99203,"New patient office or other outpatient visit, ...",N,19.0,19,19,110.610000,264.000000,71.053684,70.248421
29734,1992977896,PYLE,REGAN,C,DO,F,I,120 MIDLAND AVENUE,SUITE #230,GLENWOOD SPRINGS,...,99204,"New patient office or other outpatient visit, ...",N,46.0,46,46,167.750000,382.000000,116.858043,117.611304
29735,1992977896,PYLE,REGAN,C,DO,F,I,120 MIDLAND AVENUE,SUITE #230,GLENWOOD SPRINGS,...,99213,Established patient office or other outpatient...,N,101.0,71,101,74.650000,159.000000,54.202475,54.086436
29736,1992977896,PYLE,REGAN,C,DO,F,I,120 MIDLAND AVENUE,SUITE #230,GLENWOOD SPRINGS,...,99214,Established patient office or other outpatient...,N,65.0,35,65,109.750000,239.000000,81.510615,81.643385
29737,1992988844,PADI,ANUPAMA,R,M.D.,F,I,19465 DEERFIELD AVE,#101,LEESBURG,...,95004,"Injection of allergenic extracts into skin, ac...",N,882.0,29,30,7.500000,14.721088,5.880000,5.345975
29738,1992988844,PADI,ANUPAMA,R,M.D.,F,I,19465 DEERFIELD AVE,#101,LEESBURG,...,95115,Injection of incremental dosages of allergen,N,139.0,32,139,9.880000,28.410072,6.793381,6.170216
29739,1992988844,PADI,ANUPAMA,R,M.D.,F,I,19465 DEERFIELD AVE,#101,LEESBURG,...,95117,"Injection of incremental dosages of allergen, ...",N,74.0,24,74,11.441351,34.297297,8.132297,7.388108
29740,1992988844,PADI,ANUPAMA,R,M.D.,F,I,19465 DEERFIELD AVE,#101,LEESBURG,...,99204,"New patient office or other outpatient visit, ...",N,36.0,36,36,176.870000,277.222222,123.407222,119.013889
29741,1992988844,PADI,ANUPAMA,R,M.D.,F,I,19465 DEERFIELD AVE,#101,LEESBURG,...,99213,Established patient office or other outpatient...,N,26.0,24,26,78.840000,117.692308,54.929615,53.852692
29742,1992988844,PADI,ANUPAMA,R,M.D.,F,I,19465 DEERFIELD AVE,#101,LEESBURG,...,99214,Established patient office or other outpatient...,N,12.0,11,12,115.760000,177.333333,78.907500,79.521667
29743,1992998405,NARAYAN,SARA,E,MD,F,I,133 LITTLETON RD STE 103,ALLERGY WEST,WESTFORD,...,99204,"New patient office or other outpatient visit, ...",N,11.0,11,11,179.220000,450.000000,140.510000,130.280000

In [48]:
outfile = df.drop_duplicates(subset=['National Provider Identifier'])

In [49]:
outfile.to_csv("Medicare_filtered.csv")

In [50]:
df_filtered = pd.read_csv('medicare_filtered_full.csv')

In [51]:
df_filtered[df_filtered.State == 'HI']

,Unnamed: 0,National Provider Identifier,Last Name/Organization Name of the Provider,First Name of the Provider,Middle Initial of the Provider,Credentials of the Provider,Gender of the Provider,Entity Type of the Provider,Street Address 1 of the Provider,Street Address 2 of the Provider,...,Number,Street,Unit Type,Unit Number,City,State,County,Zip,Country,Source
21,164,1003859059,KUO,PHILIP,I,"M.D., PH.D.",M,I,414 ULUNIU ST,NaN,...,414,Uluniu St,NaN,NaN,Kailua,HI,Honolulu County,96734.0,US,City of Honolulu
64,589,1013911924,WANG,ALLAN,V,"MD, PHD",M,I,75-166 KALANI ST,SUITE 204,...,75,Kalani St,NaN,NaN,Kailua Kona,HI,Hawaii County,96740.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
173,1601,1043482706,OSTROUKHOVA,MARINA,NaN,MD,F,I,1329 LUSITANA ST STE 603,NaN,...,1329,Lusitana St,Ste,603,Honolulu,HI,Honolulu County,96813.0,US,City of Honolulu
395,3557,1114106036,MCDONNELL,JOHN,T,MD,M,I,46-001 KAMEHAMEHA HWY STE 401,NaN,...,46,Kamehameha Hwy,Unit,401,Kaneohe,HI,Honolulu County,96744.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
558,5017,1164459327,KUO,PHILIP,H,MD,M,I,414 ULUNIU ST,NaN,...,414,Uluniu St,NaN,NaN,Kailua,HI,Honolulu County,96734.0,US,City of Honolulu
726,6573,1225008303,SHAH,APARNA,S,M.D.,F,I,1 JARRETT WHITE RD,"MCHK-DMA, TRIPLER ARMY HOSPITAL",...,1,Jarrett White Rd,NaN,NaN,Tripler Army Medical Center,HI,Honolulu County,96859.0,US,City of Honolulu
989,9127,1306041967,HARADA,ABIGAIL,S,M.D.,F,I,1329 LUSITANA ST STE 504,"QUEEN'S MEDICAL CENTER, POB II",...,1329,Lusitana St,Ste,504,Honolulu,HI,Honolulu County,96813.0,US,City of Honolulu
2219,20143,1669561841,KAM,JEFFREY,C,M.D.,M,I,888 S KING ST,NaN,...,888,S King St,NaN,NaN,Honolulu,HI,Honolulu County,96813.0,US,City of Honolulu
2267,20569,1689681439,ANDO,RICHARD,E,MD,M,I,405 N KUAKINI ST,SUITE 903,...,405,N Kuakini St,NaN,NaN,Honolulu,HI,Honolulu County,96817.0,US,City of Honolulu

In [52]:
df_filtered[['National Provider Identifier','Zip', 'County', 'State']]

      National Provider Identifier      Zip               County State
0                       1003021114  11377.0        Queens County    NY
1                       1003027301  22401.0  Fredericksburg city    VA
2                       1003039199  49424.0        Ottawa County    MI
3                       1003041476  60304.0          Cook County    IL
4                       1003071713  33612.0  Hillsborough County    FL
5                       1003080052  94040.0   Santa Clara County    CA
6                       1003093832  29407.0    Charleston County    SC
7                       1003110008  55805.0     St. Louis County    MN
8                       1003186479  64108.0       Jackson County    MO
9                       1003800939  33980.0     Charlotte County    FL
10                      1003802398  33470.0    Palm Beach County    FL
11                      1003809518  44512.0      Mahoning County    OH
12                      1003809724  40245.0     Jefferson County    KY
13                      1003812595  76712.0      McLennan County    TX
14                      1003813205  43560.0         Lucas County    OH
15                      1003815234  48315.0        Macomb County    MI
16                      1003815374  19046.0    Montgomery County    PA
17                      1003819624  50702.0    Black Hawk County    IA
18                      1003848474  19713.0    New Castle County    DE
19                      1003850439  19072.0    Montgomery County    PA
20                      1003855859   6824.0     Fairfield County    CT
21                      1003859059  96734.0      Honolulu County    HI
22                      1003861055  48074.0     St. Clair County    MI
23                      1003863796   1970.0         Essex County    MA
24                      1003865726  23233.0       Henrico County    VA
25                      1003866302  44129.0      Cuyahoga County    OH
26                      1003868043  18954.0         Bucks County    PA
27                      1003878299  60602.0          Cook County    IL
28                      1003878943   7080.0     Middlesex County    NJ
29                      1003879230  77702.0     Jefferson County    TX
...                            ...      ...                  ...   ...
3248                    1982799359  19426.0    Montgomery County    PA
3249                    1982869897  22911.0     Albemarle County    VA
3250                    1982886826  35209.0     Jefferson County    AL
3251                    1982890901  90064.0   Los Angeles County    CA
3252                    1982903498   2445.0       Norfolk County    MA
3253                    1982921169  32224.0         Duval County    FL
3254                    1982947958  40509.0       Fayette County    KY
3255                    1992020903   1887.0     Middlesex County    MA
3256                    1992700793  34239.0      Sarasota County    FL
3257                    1992701833  40217.0     Jefferson County    KY
3258                    1992722565  85051.0      Maricopa County    AZ
3259                    1992724843  44124.0      Cuyahoga County    OH
3260                    1992744668  10801.0   Westchester County    NY
3261                    1992756548  33026.0       Broward County    FL
3262                    1992764260  72209.0       Pulaski County    AR
3263                    1992770259  16214.0       Clarion County    PA
3264                    1992780316  11220.0         Kings County    NY
3265                    1992788988   2114.0       Suffolk County    MA
3266                    1992798532  77802.0        Brazos County    TX
3267                    1992811806  20650.0    St. Mary's County    MD
3268                    1992812358  94301.0   Santa Clara County    CA
3269                    1992828289  31021.0       Laurens County    GA
3270                    1992835367  97401.0          Lane County    OR
3271                    1992862817  48302.0       Oakland County    MI
3272                    1992890727  31405.0       Chatham County    GA
3273                    1992901425  11209.0         Kings County    NY
3274                    1992954390  43210.0      Franklin County    OH
3275                    1992977896  81601.0      Garfield County    CO
3276                    1992988844  20176.0       Loudoun County    VA
3277                    1992998405   1886.0     Middlesex County    MA

[3278 rows x 4 columns]

In [67]:
df_filtered[['National Provider Identifier', 'Zip','County', 'State']].groupby('Zip').aggregate({"National Provider Identifier":"count", "County":"first","State":"first"})

         National Provider Identifier                        County State
Zip
1060.0                              1              Hampshire County    MA
1062.0                              5              Hampshire County    MA
1103.0                              2                Hampden County    MA
1201.0                              1              Berkshire County    MA
1440.0                              2              Worcester County    MA
1453.0                              4              Worcester County    MA
1605.0                              2              Worcester County    MA
1608.0                              1              Worcester County    MA
1702.0                              1              Middlesex County    MA
1747.0                              1              Worcester County    MA
1757.0                              1              Worcester County    MA
1772.0                              1              Worcester County    MA
1803.0                              1              Middlesex County    MA
1821.0                              1              Middlesex County    MA
1824.0                              4              Middlesex County    MA
1843.0                              1                  Essex County    MA
1845.0                              1                  Essex County    MA
1886.0                              2              Middlesex County    MA
1887.0                              3              Middlesex County    MA
1890.0                              1              Middlesex County    MA
1902.0                              1                  Essex County    MA
1950.0                              1                  Essex County    MA
1970.0                              5                  Essex County    MA
2026.0                              1                Norfolk County    MA
2062.0                              2                Norfolk County    MA
2101.0                              1                Suffolk County    MA
2111.0                              2                Suffolk County    MA
2114.0                             14                Suffolk County    MA
2115.0                              4                Suffolk County    MA
2130.0                              2                Suffolk County    MA
...                               ...                           ...   ...
98101.0                             4                   King County    WA
98104.0                             2                   King County    WA
98105.0                             3                   King County    WA
98115.0                             8                   King County    WA
98122.0                             1                   King County    WA
98133.0                             1                   King County    WA
98195.0                             2                   King County    WA
98201.0                             5              Snohomish County    WA
98225.0                             2                Whatcom County    WA
98226.0                             1                Whatcom County    WA
98274.0                             1                 Skagit County    WA
98383.0                             2                 Kitsap County    WA
98405.0                             2                 Pierce County    WA
98431.0                             2                 Pierce County    WA
98499.0                             4                 Pierce County    WA
98506.0                             1               Thurston County    WA
98664.0                             1                  Clark County    WA
98683.0                             2                  Clark County    WA
98686.0                             3                  Clark County    WA
98801.0                             1                 Chelan County    WA
98902.0                             1                 Yakima County    WA
99202.0                             1                Spokane County    WA
99204.0                             5                Spokane County    WA
99336.0                             1                 Benton County    WA
99352.0                             1                 Benton County    WA
99362.0                             2            Walla Walla County    WA
99508.0                             5        Anchorage Municipality    AK
99645.0                             1     Matanuska-Susitna Borough    AK
99669.0                             1       Kenai Peninsula Borough    AK
99701.0                             1  Fairbanks North Star Borough    AK

[1725 rows x 3 columns]

In [68]:
df_filtered = df_filtered[df_filtered.State != "PR"]
grouped = df_filtered[['National Provider Identifier', 'County', 'State']].groupby(['County', 'State']).count()
grouped

                              National Provider Identifier
County                 State
Ada County             ID                                5
Adair County           MO                                1
Adams County           CO                                9
                       IL                                2
Aiken County           SC                                1
Alachua County         FL                                5
Alameda County         CA                                9
Alamosa County         CO                                1
Albany County          NY                               10
Albemarle County       VA                               11
Alexandria city        VA                                3
Allegan County         MI                                1
Allegany County        MD                                1
Allegheny County       PA                               17
Allen County           IN                                7
Anchorage Municipality AK                                5
Anderson County        SC                                1
                       TX                                1
Androscoggin County    ME                                1
Angelina County        TX                                1
Anne Arundel County    MD                                9
Anoka County           MN                                2
Arapahoe County        CO                                5
Arlington County       VA                                2
Ascension Parish       LA                                1
Atlantic County        NJ                                1
Augusta County         VA                                1
Baldwin County         AL                                2
                       GA                                1
Baltimore County       MD                               12
...                                                    ...
Washington County      WI                                1
Washoe County          NV                                5
Washtenaw County       MI                               14
Waukesha County        WI                                2
Wayne County           IN                                1
                       MI                               21
Webb County            TX                                2
Weber County           UT                                3
Webster County         IA                                1
Weld County            CO                                1
Westchester County     NY                               25
Westmoreland County    PA                                1
Whatcom County         WA                                3
Wicomico County        MD                                1
Will County            IL                                5
Williamsburg city      VA                                3
Williamson County      TN                                8
                       TX                                7
Winchester city        VA                                2
Winnebago County       IL                                2
                       WI                                2
Worcester County       MA                               12
Wyandotte County       KS                                4
Yakima County          WA                                1
Yavapai County         AZ                                1
Yellowstone County     MT                                3
Yolo County            CA                                2
York County            ME                                1
                       PA                                3
Yuma County            AZ                                1

[628 rows x 1 columns]

In [69]:
pop_df = pd.read_csv('popests_counties.csv')

In [70]:
df_filtered[(df_filtered.State == 'AK')]

,Unnamed: 0,National Provider Identifier,Last Name/Organization Name of the Provider,First Name of the Provider,Middle Initial of the Provider,Credentials of the Provider,Gender of the Provider,Entity Type of the Provider,Street Address 1 of the Provider,Street Address 2 of the Provider,...,Number,Street,Unit Type,Unit Number,City,State,County,Zip,Country,Source
128,1179,1033184023,FOOTE,JAMES,T,M.D.,M,I,1001 NOBLE ST,NaN,...,1001,Noble St,NaN,NaN,Fairbanks,AK,Fairbanks North Star Borough,99701.0,US,Fairbanks North Star Borough
1123,10310,1336130020,RATHKOPF,MELINDA,M,M.D.,F,I,3841 PIPER STREET,SUITE T4-054,...,3841,Piper St,NaN,NaN,Anchorage,AK,Anchorage Municipality,99508.0,US,Municipality of Anchorage
1255,11466,1366553273,NEENO,TERESA,A,MD,F,I,3841 PIPER STREET,SUITE 74-054,...,3841,Piper St,NaN,NaN,Anchorage,AK,Anchorage Municipality,99508.0,US,Municipality of Anchorage
1822,16463,1548201395,DEMAIN,JEFFREY,G,M.D,M,I,3841 PIPER ST,SUITE T4-054,...,3841,Piper St,NaN,NaN,Anchorage,AK,Anchorage Municipality,99508.0,US,Municipality of Anchorage
1962,17745,1588711444,JAMES,KRISTINA,NaN,MD,F,I,44455 STERLING HWY,NaN,...,44455,Sterling Hwy,NaN,NaN,Soldotna,AK,Kenai Peninsula Borough,99669.0,US,Copyright å© 2015 Kenai Peninsula Borough
1971,17824,1588845275,ARSENEAU,APRIL,M,MD,F,I,425 E DAHLIA AVE,SUITE MB,...,425,E Dahlia Ave,NaN,NaN,Palmer,AK,Matanuska-Susitna Borough,99645.0,US,Matanuska-Susitna Borough
2374,21552,1710977822,MOORE,LAURA,M,MD,F,I,3841 PIPER STREET,SUITE T4-054,...,3841,Piper St,NaN,NaN,Anchorage,AK,Anchorage Municipality,99508.0,US,Municipality of Anchorage
2394,21770,1720076656,MEIER,ERIC,A,M.D.,M,I,3841 PIPER ST,SUITE T4-054,...,3841,Piper St,NaN,NaN,Anchorage,AK,Anchorage Municipality,99508.0,US,Municipality of Anchorage

In [71]:
pop_df

,FIPStxt,State,Area_Name,ESTIMATES_BASE_2010,POP_ESTIMATE_2010,POP_ESTIMATE_2011,POP_ESTIMATE_2012,POP_ESTIMATE_2013,POP_ESTIMATE_2014,POP_ESTIMATE_2015,POP_ESTIMATE_2016,POP_ESTIMATE_2017,POP_ESTIMATE_2018,POP_ESTIMATE_2019
0,0,US,United States,"308,758,105","309,321,666","311,556,874","313,830,990","315,993,715","318,301,008","320,635,163","322,941,311","324,985,539","326,687,501","328,239,523"
1,1000,AL,Alabama,"4,780,125","4,785,437","4,799,069","4,815,588","4,830,081","4,841,799","4,852,347","4,863,525","4,874,486","4,887,681","4,903,185"
2,1001,AL,Autauga County,"54,597","54,773","55,227","54,954","54,727","54,893","54,864","55,243","55,390","55,533","55,869"
3,1003,AL,Baldwin County,"182,265","183,112","186,558","190,145","194,885","199,183","202,939","207,601","212,521","217,855","223,234"
4,1005,AL,Barbour County,"27,455","27,327","27,341","27,169","26,937","26,755","26,283","25,806","25,157","24,872","24,686"
5,1007,AL,Bibb County,"22,915","22,870","22,745","22,667","22,521","22,553","22,566","22,586","22,550","22,367","22,394"
6,1009,AL,Blount County,"57,322","57,376","57,560","57,580","57,619","57,526","57,526","57,494","57,787","57,771","57,826"
7,1011,AL,Bullock County,"10,911","10,876","10,675","10,606","10,549","10,663","10,400","10,389","10,176","10,174","10,101"
8,1013,AL,Butler County,"20,940","20,932","20,866","20,670","20,356","20,327","20,162","20,012","19,888","19,631","19,448"
9,1015,AL,Calhoun County,"118,526","118,408","117,744","117,190","116,471","115,917","115,469","114,973","114,710","114,331","113,605"
10,1017,AL,Chambers County,"34,169","34,122","34,033","34,104","34,139","33,977","33,996","33,745","33,707","33,600","33,254"
11,1019,AL,Cherokee County,"25,979","25,963","25,989","25,958","26,017","25,895","25,732","25,768","25,805","26,014","26,196"
12,1021,AL,Chilton County,"43,632","43,653","43,689","43,582","43,628","43,760","43,700","43,866","44,120","44,163","44,428"
13,1023,AL,Choctaw County,"13,858","13,849","13,609","13,563","13,397","13,317","13,231","13,045","12,925","12,833","12,589"
14,1025,AL,Clarke County,"25,833","25,766","25,587","25,155","25,123","24,864","24,698","24,340","24,063","23,918","23,622"
15,1027,AL,Clay County,"13,930","13,898","13,687","13,434","13,404","13,441","13,415","13,393","13,350","13,294","13,235"
16,1029,AL,Cleburne County,"14,972","15,004","14,928","14,889","14,976","15,026","14,914","14,848","14,899","15,010","14,910"
17,1031,AL,Coffee County,"49,955","50,208","50,444","51,141","50,681","50,657","50,963","51,202","51,853","51,950","52,342"
18,1033,AL,Colbert County,"54,428","54,524","54,539","54,570","54,529","54,462","54,417","54,497","54,695","55,004","55,241"
19,1035,AL,Conecuh County,"13,236","13,236","13,195","13,046","12,912","12,677","12,678","12,500","12,431","12,292","12,067"
20,1037,AL,Coosa County,"11,756","11,780","11,486","11,346","11,254","11,037","10,934","10,819","10,724","10,643","10,663"
21,1039,AL,Covington County,"37,762","37,809","38,020","37,805","37,814","37,760","37,556","37,382","37,062","36,953","37,049"
22,1041,AL,Crenshaw County,"13,893","13,869","13,894","13,915","13,847","13,851","13,850","13,916","13,858","13,825","13,772"
23,1043,AL,Cullman County,"80,406","80,456","80,410","80,279","80,690","81,068","81,761","82,450","82,867","83,418","83,768"
24,1045,AL,Dale County,"50,251","50,394","50,122","50,289","49,771","49,414","49,365","49,362","49,342","49,143","49,172"
25,1047,AL,Dallas County,"43,813","43,854","43,251","42,789","41,976","41,554","40,936","40,080","39,238","38,294","37,196"
26,1049,AL,DeKalb County,"71,120","71,163","71,365","70,944","70,912","70,993","71,087","71,104","71,437","71,407","71,513"
27,1051,AL,Elmore County,"79,272","79,552","79,993","80,193","80,536","80,538","80,872","81,204","81,422","81,011","81,209"
28,1053,AL,Escambia County,"38,320","38,345","38,204","38,023","37,765","37,735","37,661","37,475","36,993","36,524","36,633"
29,1055,AL,Etowah County,"104,429","104,459","104,369","104,278","103,884","103,399","102,998","102,855","103,007","102,611","102,268"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3243,72095,PR,"Maunabo Municipio, Puerto Rico","12,245","12,235","12,065","11,906","11,754","11,544","11,314","11,084","10,798","10,361","10,321"
3244,72097,PR,"Mayagüez Municipio, Puerto Rico","89,080","88,805","87,070","85,304","83,698","81,636","79,671","77,643","75,371","71,944","71,530"
3245,72099,PR,"Moca Municipio, Puerto Rico","40,109","40,093","39,733","39,326","38,921","38,320","37,730","37,072","36,265","34,848","34,891"
3246,72101,PR,"Morovis Municipio, Puerto Rico","32,610","32,651","32,586","32,480","32,368","32,121","31,858","31,520","31,044","30,051","30,335"
3247,72103,PR,"Naguabo Municipio, Puerto Rico","26,720","26,763","26,826","26,856","26,886","26,774","26,624","26,456","26,137","25,399","25,761"
3248,72105,PR,"Naranjito Municipio, Puerto Rico","30,402","30,373","30,182","30,007","29,816","29,498","29,136","28,719","28,175","27,180","27,349"
3249,72107,PR,"Orocovis Municipio, Puerto Rico","23,423","23,415","23,150","22,880","22,653","22,309","21,931","21,534","21,022","20,204","20,220"
3250,72109,PR,"Patillas Municipio, Puerto Rico","19,257","19,214","18,950","18,694","18,468","18,147","17,784","17,411","16,961","16,276","16,211"
3251,72111,PR,"Peñuelas Municipio, Puerto Rico","24,282","24,221","23,769","23,277","22,819","22,290","21,728","21,120","20,419","19,399","19,249"
3252,72113,PR,"Ponce Municipio, Puerto Rico","166,327","165,733","162,621","159,317","156,396","153,004","149,039","144,494","139,888","133,052","131,881"
3253,72115,PR,"Quebradillas Municipio, Puerto Rico","25,919","25,888","25,685","25,480","25,282","24,934","24,579","24,173","23,653","22,824","22,918"
3254,72117,PR,"Rincón Municipio, Puerto Rico","15,200","15,206","15,100","14,981","14,872","14,731","14,565","14,360","14,087","13,613","13,656"
3255,72119,PR,"Río Grande Municipio, Puerto Rico","54,319","54,278","53,864","53,678","53,332","52,588","51,767","50,803","49,631","47,839","48,025"
3256,72121,PR,"Sabana Grande Municipio, Puerto Rico","25,361","25,326","25,031","24,703","24,458","24,080","23,605","23,169","22,602","21,714","21,712"
3257,72123,PR,"Salinas Municipio, Puerto Rico","31,078","31,037","30,755","30,405","30,172","29,733","29,287","28,804","28,238","27,087","27,128"
3258,72125,PR,"San Germán Municipio, Puerto Rico","35,691","35,624","35,190","34,718","34,161","33,570","32,946","32,333","31,465","30,239","30,227"
3259,72127,PR,"San Juan Municipio, Puerto Rico","395,475","394,296","386,927","379,547","372,507","364,166","355,561","346,440","336,139","320,761","318,441"
3260,72129,PR,"San Lorenzo Municipio, Puerto Rico","41,036","41,010","40,631","40,254","39,919","39,326","38,749","38,119","37,283","35,904","35,989"
3261,72131,PR,"San Sebastián Municipio, Puerto Rico","42,430","42,354","41,773","41,189","40,615","39,830","39,024","38,187","37,201","35,659","35,528"
3262,72133,PR,"Santa Isabel Municipio, Puerto Rico","23,274","23,277","23,190","23,084","22,998","22,751","22,510","22,220","21,794","21,050","21,209"
3263,72135,PR,"Toa Alta Municipio, Puerto Rico","74,070","74,282","74,532","74,661","74,816","74,603","74,344","73,890","73,052","71,008","72,025"
3264,72137,PR,"Toa Baja Municipio, Puerto Rico","89,616","89,474","88,094","86,743","85,511","83,853","82,027","80,211","77,961","74,582","74,271"
3265,72139,PR,"Trujillo Alto Municipio, Puerto Rico","74,860","74,785","73,915","73,038","72,126","70,866","69,614","68,196","66,487","63,721","63,674"
3266,72141,PR,"Utuado Municipio, Puerto Rico","33,149","33,045","32,563","32,027","31,542","30,923","30,241","29,506","28,738","27,502","27,395"
3267,72143,PR,"Vega Alta Municipio, Puerto Rico","39,951","39,934","39,798","39,610","39,482","39,058","38,646","37,991","37,050","35,782","36,061"
3268,72145,PR,"Vega Baja Municipio, Puerto Rico","59,662","59,562","58,688","57,857","57,063","55,942","54,805","53,677","52,318","50,136","50,023"
3269,72147,PR,"Vieques Municipio, Puerto Rico","9,301","9,314","9,247","9,227","9,179","9,081","8,965","8,833","8,666","8,362","8,386"
3270,72149,PR,"Villalba Municipio, Puerto Rico","26,073","26,001","25,542","25,135","24,745","24,256","23,662","23,091","22,452","21,436","21,372"
3271,72151,PR,"Yabucoa Municipio, Puerto Rico","37,941","37,874","37,361","36,844","36,377","35,732","35,076","34,363","33,519","32,254","32,282"
3272,72153,PR,"Yauco Municipio, Puerto Rico","41,947","41,828","41,036","40,249","39,492","38,535","37,585","36,654","35,474","33,853","33,575"

In [72]:
df_filtered[df_filtered.State != "PR"]

,Unnamed: 0,National Provider Identifier,Last Name/Organization Name of the Provider,First Name of the Provider,Middle Initial of the Provider,Credentials of the Provider,Gender of the Provider,Entity Type of the Provider,Street Address 1 of the Provider,Street Address 2 of the Provider,...,Number,Street,Unit Type,Unit Number,City,State,County,Zip,Country,Source
0,0,1003021114,AYUSO,ROSALIA,NaN,"MD, PHD",F,I,4902 QUEENS BLVD,4TH FLOOR,...,49-2,Queens Blvd,NaN,NaN,Woodside,NY,Queens County,11377.0,US,City of New York
1,6,1003027301,BUTT,AHMED,T,M.D.,M,I,1300 THORNTON ST,SUITE 200,...,1300,Thornton St,NaN,NaN,Fredericksburg,VA,Fredericksburg city,22401.0,US,Virginia Geographic Information Network (VGIN)
2,15,1003039199,HUTSON,JULIE,A,M.D.,F,I,3290 N WELLNESS DR STE 180,NaN,...,3290,N Wellness Dr,Ste,180,Holland,MI,Ottawa County,49424.0,US,Ottawa
3,21,1003041476,LINDGREN,KEVIN,D,MD,M,I,610 S MAPLE AVE STE 5500,NaN,...,610,S Maple Ave,Ste,5500,Oak Park,IL,Cook County,60304.0,US,Cook
4,22,1003071713,CARDET GUISASAOLA,JUAN CARLOS,NaN,MD,M,I,13330 USF LAUREL DR,NaN,...,13330,Usf Laurel Dr,NaN,NaN,Tampa,FL,Hillsborough County,33612.0,US,Statewide2
5,23,1003080052,CRONIN,JULIA,A,MD,F,I,701 E EL CAMINO REAL,NaN,...,701,E El Camino Real,NaN,NaN,Mountain View,CA,Santa Clara County,94040.0,US,Santa Clara County
6,27,1003093832,MAJESKI,ELIZABETH,I,MD,F,I,46 MARKFIELD DR,SUITE A,...,46,Markfield Dr,NaN,NaN,Charleston,SC,Charleston County,29407.0,US,City of Charleston
7,41,1003110008,KANDEEL,ALAADDIN,H,M.D.,M,I,400 E 3RD ST,ESSENTIA HEALTH DULUTH CLINIC,...,400,E 3rd St,NaN,NaN,Duluth,MN,St. Louis County,55805.0,US,St Louis
8,49,1003186479,GIRDHAR,MANIKA,NaN,D.O.,F,I,2401 GILLHAM RD,NaN,...,2401,Gillham Rd,NaN,NaN,Kansas City,MO,Jackson County,64108.0,US,Jackson
9,57,1003800939,MENDEZ,ELVIN,M,MD,M,I,22655 BAYSHORE RD,STE 130,...,22655,Bayshore Rd,NaN,NaN,Punta Gorda,FL,Charlotte County,33980.0,US,Charlotte County
10,65,1003802398,KRISHNA RAO,DESAI,G,M.D.,M,I,12959 PALMS WEST DR,SUITE 230,...,12959,Palms West Dr,NaN,NaN,Loxahatchee,FL,Palm Beach County,33470.0,US,Palm Beach County
11,66,1003809518,HOUSER,WILLIAM,L,M.D.,M,I,250 DEBARTOLO PL,SUITE 1510,...,250,Debartolo Pl,NaN,NaN,Youngstown,OH,Mahoning County,44512.0,US,Mahoning
12,73,1003809724,DAMIN,DEREK,A,MD,M,I,163 SOUTH ENGLISH STATION ROAD,NaN,...,163,S English Station Rd,NaN,NaN,Louisville,KY,Jefferson County,40245.0,US,"Metro Louisville, LOJIC partners"
13,83,1003812595,AMAR,NIRAN,J,M.D.,M,I,333 LONDONDERRY DR,STE 100,...,333,Londonderry Dr,NaN,NaN,Waco,TX,McLennan County,76712.0,US,City of Waco
14,100,1003813205,SAFADI,GHASSAN,S,M.D.,M,I,7640 SYLVANIA AVE,J,...,7640,Sylvania Ave,NaN,NaN,Sylvania,OH,Lucas County,43560.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
15,113,1003815234,WHITE,ANNE,H,MD,F,I,50505 SCHOENHERR RD,SUITE 350,...,50505,Schoenherr Rd,NaN,NaN,Shelby Township,MI,Macomb County,48315.0,US,Macomb
16,127,1003815374,ABBOUD,ELIAS,M,M.D.,M,I,261 OLD YORK RD,STE 325,...,261,Old York Rd,NaN,NaN,Jenkintown,PA,Montgomery County,19046.0,US,Montgomery
17,136,1003819624,JAVIER,FELIPE,C,MD,M,I,2710 SAINT FRANCIS DR STE 411,NaN,...,2710,St Francis Dr,Ste,411,Waterloo,IA,Black Hawk County,50702.0,US,TIGER/Lineå¨ dataset from the US Census Bureau
18,143,1003848474,GEIMEIER,WILLIAM,J,M.D.,M,I,179 W CHESTNUT HILL RD,SUITE 1,...,179,W Chestnut Hill Rd,NaN,NaN,Newark,DE,New Castle County,19713.0,US,New Castle
19,151,1003850439,BOWSER,CORINNA,S,M.D.,F,I,200 MERION AVE,NaN,...,200,Merion Ave,NaN,NaN,Narberth,PA,Montgomery County,19072.0,US,Montgomery
20,159,1003855859,ALTSCHUL-LATZMAN,AIMEE,S,M.D.,F,I,140 SHERMAN ST,3RD FLOOR,...,140,Sherman St,NaN,NaN,Fairfield,CT,Fairfield County,6824.0,US,Town of Fairfield
21,164,1003859059,KUO,PHILIP,I,"M.D., PH.D.",M,I,414 ULUNIU ST,NaN,...,414,Uluniu St,NaN,NaN,Kailua,HI,Honolulu County,96734.0,US,City of Honolulu
22,172,1003861055,COOKINGHAM,GAIL,A,MD,F,I,2820 STABLE DRIVE,NaN,...,2837,Stable,NaN,NaN,Smiths Creek,MI,St. Clair County,48074.0,US,Semcog
23,180,1003863796,OBER,ANDREW,I,M.D.,M,I,114R HIGHLAND AVE,NaN,...,114,Highland Ave,NaN,NaN,Salem,MA,Essex County,1970.0,US,"Office of Geographic Information (MassGIS), Co..."
24,187,1003865726,GELBER,LAWRENCE,E,M.D.,M,I,9920 INDEPENDENCE PARK DR,SUITE 100,...,9920,Independence Park Dr,NaN,NaN,Henrico,VA,Henrico County,23233.0,US,Henrico
25,197,1003866302,DURVE,MOHAN,J,MD,M,I,6115 POWERS BLVD,202,...,6115,Powers Blvd,NaN,NaN,Cleveland,OH,Cuyahoga County,44129.0,US,Cuyahoga
26,211,1003868043,KOVEN,NORMAN,NaN,M.D.,M,I,130 ALMSHOUSE RD,SUITE 105,...,130,Almshouse Rd,NaN,NaN,Richboro,PA,Bucks County,18954.0,US,Bucks
27,224,1003878299,SIDDIQI,AYESHA,NaN,M.D.,F,I,30 N MICHIGAN AVE,#1107,...,30,N Michigan Ave,NaN,NaN,Chicago,IL,Cook County,60602.0,US,City of Chicago
28,230,1003878943,KOTHARI,HARISH,B,MD,M,I,906 OAK TREE ROAD,SUITE N,...,906,Oak Tree Rd,NaN,NaN,South Plainfield,NJ,Middlesex County,7080.0,US,"NJ Office of Information Technology (NJOIT), O..."
29,236,1003879230,SINGH,RANJIT,R,M.D.,M,I,3030 NORTH ST,STE 500,...,3030,North St,NaN,NaN,Beaumont,TX,Jefferson County,77702.0,US,City of Beaumont
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3248,29451,1982799359,SHAH,SHAILEN,R,M.D.,M,I,555 SECOND AVENUE,SUITE C-750,...,555,2nd Ave,NaN,NaN,Collegeville,PA,Montgomery County,19426.0,US,Montgomery
3249,29460,1982869897,KLAFFKY,ERIN,J,MD,F,I,1415 ROLKIN CT STE 102,NaN,...,1415,Rolkin Ct,Ste,102,Charlottesville,VA,Albemarle County,22911.0,US,Albemarle
3250,29465,1982886826,SIKORA,MAXCIE,M,M.D.,F,I,504 BROOKWOOD BLVD,NaN,...,504,Brookwood Blvd,NaN,NaN,Birmingham,AL,Jefferson County,35209.0,US,Jefferson
3251,29471,1982890901,BENOUNI,SARALEEN,NaN,M.D.,F,I,11500 W OLYMPIC BLVD,STE 630,...,11500,W Olympic Blvd,NaN,NaN,Los Angeles,CA,Los Angeles County,90064.0,US,City of Los Angeles
3252,29480,1982903498,SOKOL,KRISTIN,C,M.D.,F,I,1 BROOKLINE PL,APPT 623,...,1,Brookline Pl,NaN,NaN,Brookline,MA,Norfolk County,2445.0,US,City of Brookline
3253,29485,1982921169,GONZALEZ ESTRADA,ALEXEI,NaN,MD,M,I,4500 SAN PABLO RD S,NaN,...,4500,San Pablo Rd S,NaN,NaN,Jacksonville,FL,Duval County,32224.0,US,Duval
3254,29500,1982947958,WU,SHUYA,NaN,MD,F,I,100 N EAGLE CREEK DR,NaN,...,100,N Eagle Creek Dr,NaN,NaN,Lexington,KY,Fayette County,40509.0,US,Lexington Fayette
3255,29509,1992020903,ROSENBAUM,ZOE,NaN,M.D.,F,I,41 MALL RD,LAHEY HOSPITAL AND MEDICAL CENTER,...,41,Mill Rd,NaN,NaN,Wilmington,MA,Middlesex County,1887.0,US,"Office of Geographic Information (MassGIS), Co..."
3256,29518,1992700793,BLOOM,FREDERICK,L,M.D.,M,I,2650 BAHIA VISTA ST,STE 304,...,2650,Bahia Vista St,NaN,NaN,Sarasota,FL,Sarasota County,34239.0,US,Sarasota County
3257,29535,1992701833,GLASS,THOMAS,A,M.D.,M,I,1261 GOSS AVE,NaN,...,1261,Goss Ave,NaN,NaN,Louisville,KY,Jefferson County,40217.0,US,"Metro Louisville, LOJIC partners"
3258,29544,1992722565,HIGGINS,WILLIAM,H,D.O.,M,I,8618 N 35TH AVE STE 3,NaN,...,8618,N 35th Ave,Ste,3,Phoenix,AZ,Maricopa County,85051.0,US,Maricopa
3259,29556,1992724843,TCHEUREKDJIAN,HAIG,NaN,M.D.,M,I,5915 LANDERBROOK DR,STE. 110,...,5915,Landerbrook Dr,NaN,NaN,Cleveland,OH,Cuyahoga County,44124.0,US,Cuyahoga
3260,29580,1992744668,ARAYATA,RICARDO,B,M.D.,M,I,145 HUGUENOT ST,SUITE 610,...,145,Huguenot St,NaN,NaN,New Rochelle,NY,Westchester County,10801.0,US,Westchester
3261,29588,1992756548,LLANES,SHARLENE,J,M.D.,F,I,600 N HIATUS RD,SUITE 215,...,600,N Hiatus Rd,NaN,NaN,Pembroke Pines,FL,Broward County,33026.0,US,Broward
3262,29596,1992764260,BADHWAR,ANIL,K,M.D,M,I,11321 INTERSTATE 30,SUITE 308,...,11321,Interstate 30,NaN,NaN,Little Rock,AR,Pulaski County,72209.0,US,Pulaski
3263,29611,1992770259,DESAI,HARESH,I,M.D.,M,I,1008 S 5TH AVE,STE 201,...,1008,S 5th Ave,NaN,NaN,Clarion,PA,Clarion County,16214.0,US,TIGER/Line¨ dataset from the US Census Bureau
3264,29613,1992780316,THAW,EMERALD,M,MD,F,I,5908 5TH AVE,NaN,...,5908,5th Ave,NaN,NaN,Brooklyn,NY,Kings County,11220.0,US,City of New York
3265,29614,1992788988,HESTERBERG,PAUL,E,MD,M,I,55 FRUIT STREET,MASSACHUSETTS GENERAL HOSPITAL COX BUILDING 201,...,55,Fruit St,NaN,NaN,Boston,MA,Suffolk County,2114.0,US,City of Boston
3266,29625,1992798532,PAULL,KEITH,J,M.D.,M,I,3201 UNIVERSITY DR E STE 245,NaN,...,3201,University Dr E,Ste,245,Bryan,TX,Brazos County,77802.0,US,Brazos
3267,29639,1992811806,SIMLOTE,PRADEEP,NaN,MD,M,I,41680 MISS BESSIE DR,SUITE 203,...,41680,Miss Bessie Dr,NaN,NaN,Leonardtown,MD,St. Mary's County,20650.0,US,St Marys
3268,29653,1992812358,BLESSING-MOORE,JOANN,C,M.D.,F,I,723 EMERSON ST,NaN,...,723,Emerson St,NaN,NaN,Palo Alto,CA,Santa Clara County,94301.0,US,City of Palo Alto
3269,29663,1992828289,JOHNSON,RODNEY,M,M.D.,M,I,227 INDUSTRIAL BLVD,NaN,...,227,Industrial Blvd,NaN,NaN,Dublin,GA,Laurens County,31021.0,US,Laurens
3270,29675,1992835367,KEHL,SARAH,S,M.D.,F,I,1488 OAK ST,NaN,...,1488,Oak St,NaN,NaN,Eugene,OR,Lane County,97401.0,US,Lane
3271,29686,1992862817,SAVLIWALA,MOHAMMEDI,N,MD,M,I,10 W SQUARE LAKE RD,# 301,...,10,W Square Lake Rd,NaN,NaN,Bloomfield Hills,MI,Oakland County,48302.0,US,Oakland
3272,29699,1992890727,EADES,JACK,R,MD,M,I,5223 PAULSEN ST,NaN,...,5223,Paulsen St,NaN,NaN,Savannah,GA,Chatham County,31405.0,US,City of Savannah
3273,29717,1992901425,KOPYLTSOVA,YELENA,NaN,MD,F,I,9020 5TH AVE FL 3,NaN,...,9020,5th Ave,NaN,NaN,Brooklyn,NY,Kings County,11209.0,US,City of New York
3274,29723,1992954390,OGBOGU,PRINCESS,NaN,MD,F,I,2050 KENNY RD,SUITE 2200,...,2050,Kenny Rd,NaN,NaN,Columbus,OH,Franklin County,43210.0,US,Franklin
3275,29729,1992977896,PYLE,REGAN,C,DO,F,I,120 MIDLAND AVENUE,SUITE #230,...,120,Midland Ave,NaN,NaN,Glenwood Springs,CO,Garfield County,81601.0,US,Statewide
3276,29737,1992988844,PADI,ANUPAMA,R,M.D.,F,I,19465 DEERFIELD AVE,#101,...,19465,Deerfield Ave,NaN,NaN,Leesburg,VA,Loudoun County,20176.0,US,Loudoun
3277,29743,1992998405,NARAYAN,SARA,E,MD,F,I,133 LITTLETON RD STE 103,ALLERGY WEST,...,133,Littleton Rd,Ste,103,Westford,MA,Middlesex County,1886.0,US,"Office of Geographic Information (MassGIS), Co..."

In [73]:
#np.unique(df_filtered['County'].astype('category'))
counties = []
for item in df_filtered['County']:
    counties.append(item)
counties = np.unique(counties)

states = []
for item in df_filtered['State']:
    states.append(item)
states = np.unique(states)
states
#counties.dropna()
#counties.remove('nan')
counties = np.delete(counties, np.where(counties == 'nan'))
states = np.delete(states, np.where(states == 'nan'))

In [74]:
grouped["pop_est"] =""
grouped
(grouped.loc['Ada County'].index[0])

'ID'

In [75]:
pop_df[(pop_df.State == 'CO') & (pop_df.Area_Name == 'Adams County')].POP_ESTIMATE_2019.values[0]

'517,421'

In [76]:
pop_est_values = []
for county in counties:
    print(county)
    row = grouped.loc[county]
    if len(row) > 1:
        for state in row.index:
            print(state)
            temp = pop_df[(pop_df.State == state) & (pop_df.Area_Name == county)].POP_ESTIMATE_2019.values[0]
            pop_est_values.append(temp)
    else:
        state = row.index[0]
        print(state)
        if state == "PR":
            pass
        else:
            if county == "DoÌ±a Ana County":
                county = "Doña Ana County"
            temp = pop_df[(pop_df.State == state) & (pop_df.Area_Name == county)].POP_ESTIMATE_2019.values[0]
            pop_est_values.append(temp)

Ada County
ID
Adair County
MO
Adams County
CO
IL
Aiken County
SC
Alachua County
FL
Alameda County
CA
Alamosa County
CO
Albany County
NY
Albemarle County
VA
Alexandria city
VA
Allegan County
MI
Allegany County
MD
Allegheny County
PA
Allen County
IN
Anchorage Municipality
AK
Anderson County
SC
TX
Androscoggin County
ME
Angelina County
TX
Anne Arundel County
MD
Anoka County
MN
Arapahoe County
CO
Arlington County
VA
Ascension Parish
LA
Atlantic County
NJ
Augusta County
VA
Baldwin County
AL
GA
Baltimore County
MD
Baltimore city
MD
Bannock County
ID
Barnstable County
MA
Bartholomew County
IN
Bartow County
GA
Bay County
FL
MI
Beaver County
PA
Bedford County
VA
Bell County
TX
Bennington County
VT
Benton County
AR
OR
WA
Bergen County
NJ
Berks County
PA
Berkshire County
MA
Bernalillo County
NM
Berrien County
MI
Bexar County
TX
Bibb County
GA
Black Hawk County
IA
Blair County
PA
Blount County
TN
Blue Earth County
MN
Bonneville County
ID
Boone County
KY
MO
Bossier Parish
LA
Botetourt County
VA
Boulder County
CO
Bowie County
TX
Boyd County
KY
Bradford County
PA
Brazoria County
TX
Brazos County
TX
Brevard County
FL
Bristol County
MA
Bronx County
NY
Broome County
NY
Broward County
FL
Brown County
SD
WI
Bucks County
PA
Buncombe County
NC
Burke County
NC
Burleigh County
ND
Burlington County
NJ
Butler County
OH
Butte County
CA
Cabell County
WV
Cache County
UT
Caddo Parish
LA
Calcasieu Parish
LA
Calhoun County
AL
MI
Calvert County
MD
Camden County
NJ
Cameron County
TX
Campbell County
KY
Cape Girardeau County
MO
Carroll County
GA
Cascade County
MT
Cass County
ND
Catawba County
NC
Cattaraugus County
NY
Cayuga County
NY
Cecil County
MD
Centre County
PA
Champaign County
IL
Charles County
MD
Charleston County
SC
Charlotte County
FL
Charlottesville city
VA
Chatham County
GA
Chelan County
WA
Cherokee County
GA
Chesapeake city
VA
Cheshire County
NH
Chester County
PA
Chesterfield County
VA
Chippewa County
MI
Chisago County
MN
Chittenden County
VT
Christian County
KY
Citrus County
FL
Clackamas County
OR
Clarion County
PA
Clark County
IN
NV
WA
Clarke County
GA
Clay County
FL
MO
Clinton County
OH
Cobb County
GA
Coffee County
TN
Collier County
FL
Collin County
TX
Columbia County
GA
Comal County
TX
Comanche County
OK
Contra Costa County
CA
Cook County
IL
Coos County
OR
Coweta County
GA
Craighead County
AR
Craven County
NC
Crow Wing County
MN
Cumberland County
ME
NC
NJ
PA
Cuyahoga County
OH
Dakota County
MN
Dallas County
IA
TX
Dane County
WI
Dauphin County
PA
Davidson County
TN
Daviess County
KY
Davis County
UT
DeKalb County
GA
IL
Delaware County
IN
PA
Denton County
TX
Denver County
CO
Deschutes County
OR
Dickson County
TN
District of Columbia
DC
Dorchester County
SC
Douglas County
CO
KS
NE
DoÌ±a Ana County
NM
DuPage County
IL
Dubuque County
IA
Durham County
NC
Dutchess County
NY
Duval County
FL
East Baton Rouge Parish
LA
Eau Claire County
WI
Ector County
TX
Eddy County
NM
El Paso County
CO
TX
Elkhart County
IN
Ellis County
TX
Emmet County
MI
Erie County
NY
OH
PA
Escambia County
FL
Essex County
MA
NJ
Fairbanks North Star Borough
AK
Fairfax County
VA
Fairfield County
CT
Falls Church city
VA
Fauquier County
VA
Fayette County
GA
KY
Florence County
SC
Floyd County
GA
IN
Forsyth County
GA
NC
Fort Bend County
TX
Franklin County
MO
NY
OH
VT
Frederick County
MD
Fredericksburg city
VA
Fresno County
CA
Fulton County
GA
Gallatin County
MT
Gallia County
OH
Galveston County
TX
Garfield County
CO
OK
Garland County
AR
Genesee County
MI
Gloucester County
NJ
Goodhue County
MN
Grafton County
NH
Grand Forks County
ND
Grand Traverse County
MI
Green County
WI
Greene County
MO
OH
Greenville County
SC
Greenwood County
SC
Gregg County
TX
Guilford County
NC
Gwinnett County
GA
Hall County
GA
Hamilton County
IN
OH
TN
Hampden County
MA
Hampshire County
MA
Hancock County
OH
WV
Hardin County
KY
Harford County
MD
Harris County
TX
Harrison County
KY
MS
Harrisonburg city
VA
Hartford County
CT
Hawaii County
HI
Hennepin County
MN
Henrico County
VA
Henry County
GA
IN
Hernando County
FL
Hidalgo County
TX
Hillsborough County
FL
NH
Hinds County
MS
Honolulu County
HI
Horry County
SC
Houston County
AL
GA
Howard County
IN
MD
Hudson County
NJ
Humboldt County
CA
Imperial County
CA
Indian River County
FL
Ingham County
MI
Iredell County
NC
Jackson County
IL
MI
MO
MS
OR
Jasper County
SC
Jefferson County
AL
CO
KY
MO
NY
TX
Jefferson Parish
LA
Johnson County
IA
IN
KS
MO
Kalamazoo County
MI
Kanawha County
WV
Kandiyohi County
MN
Kane County
IL
Kankakee County
IL
Kenai Peninsula Borough
AK
Kendall County
IL
TX
Kennebec County
ME
Kenosha County
WI
Kent County
DE
MI
RI
Kenton County
KY
Kern County
CA
Kerr County
TX
King County
WA
Kings County
NY
Kitsap County
WA
Knox County
TN
Kootenai County
ID
La Crosse County
WI
La Plata County
CO
LaPorte County
IN
Lackawanna County
PA
Lafayette Parish
LA
Lake County
FL
IL
IN
OH
Lamar County
MS
Lancaster County
NE
PA
Lane County
OR
Laramie County
WY
Larimer County
CO
Lauderdale County
AL
MS
Laurens County
GA
Leavenworth County
KS
Lee County
AL
FL
GA
MS
Lehigh County
PA
Lenoir County
NC
Leon County
FL
Lewis and Clark County
MT
Lexington County
SC
Licking County
OH
Lincoln County
SD
Linn County
IA
Litchfield County
CT
Livingston County
MI
Lorain County
OH
Los Alamos County
NM
Los Angeles County
CA
Loudoun County
VA
Lowndes County
GA
Lubbock County
TX
Lucas County
OH
Luzerne County
PA
Lycoming County
PA
Lynchburg city
VA
Macomb County
MI
Macon County
IL
Madison County
AL
IL
TN
Mahoning County
OH
Manatee County
FL
Marathon County
WI
Maricopa County
AZ
Marion County
FL
IN
OH
OR
Marquette County
MI
Matanuska-Susitna Borough
AK
Maury County
TN
McCracken County
KY
McHenry County
IL
McLean County
IL
McLennan County
TX
Mecklenburg County
NC
Medina County
OH
TX
Mendocino County
CA
Merced County
CA
Mercer County
NJ
PA
WV
Mesa County
CO
Miami-Dade County
FL
Middlesex County
MA
NJ
Midland County
MI
TX
Mifflin County
PA
Milwaukee County
WI
Minnehaha County
SD
Missoula County
MT
Mobile County
AL
Mohave County
AZ
Monmouth County
NJ
Monongalia County
WV
Monroe County
IN
MI
NY
PA
Monterey County
CA
Montgomery County
AL
MD
OH
PA
TN
TX
VA
Montour County
PA
Moore County
NC
Morgan County
AL
Morris County
NJ
Multnomah County
OR
Muscogee County
GA
Muskegon County
MI
Muskogee County
OK
Nacogdoches County
TX
Napa County
CA
Nash County
NC
Nassau County
NY
Nevada County
CA
New Castle County
DE
New Hanover County
NC
New Haven County
CT
New London County
CT
New York County
NY
Newport News city
VA
Niagara County
NY
Norfolk County
MA
Northampton County
PA
Nueces County
TX
Oakland County
MI
Ocean County
NJ
Ohio County
WV
Okaloosa County
FL
Oklahoma County
OK
Olmsted County
MN
Oneida County
NY
Onondaga County
NY
Onslow County
NC
Ontario County
NY
Orange County
CA
FL
NC
NY
Orleans Parish
LA
Osceola County
FL
Otsego County
NY
Ottawa County
MI
Ouachita Parish
LA
Outagamie County
WI
Ozaukee County
WI
Palm Beach County
FL
Pasco County
FL
Pasquotank County
NC
Passaic County
NJ
Pennington County
SD
Penobscot County
ME
Peoria County
IL
Phelps County
MO
Philadelphia County
PA
Pierce County
WA
Pike County
KY
Pima County
AZ
Pinellas County
FL
Pitt County
NC
Placer County
CA
Plymouth County
MA
Polk County
FL
IA
Porter County
IN
Pottawatomie County
OK
Potter County
TX
Prince George's County
MD
Prince William County
VA
Providence County
RI
Pueblo County
CO
Pulaski County
AR
KY
Putnam County
NY
TN
Queens County
NY
Racine County
WI
Ramsey County
MN
Randolph County
NC
Rapides Parish
LA
Reno County
KS
Richland County
SC
Richmond County
GA
NY
Richmond city
VA
Riverside County
CA
Roanoke city
VA
Rock County
WI
Rock Island County
IL
Rockdale County
GA
Rockingham County
NH
Rockland County
NY
Ross County
OH
Rutherford County
TN
Sacramento County
CA
Saginaw County
MI
Salem city
VA
Saline County
KS
Salt Lake County
UT
San Bernardino County
CA
San Diego County
CA
San Francisco County
CA
San Joaquin County
CA
San Luis Obispo County
CA
San Mateo County
CA
Sangamon County
IL
Santa Barbara County
CA
Santa Clara County
CA
Santa Cruz County
CA
Santa Fe County
NM
Sarasota County
FL
Saratoga County
NY
Sarpy County
NE
Schenectady County
NY
Schuylkill County
PA
Scott County
IA
Sebastian County
AR
Sedgwick County
KS
Seminole County
FL
Sevier County
TN
Shawnee County
KS
Sheboygan County
WI
Shelby County
TN
Sherburne County
MN
Skagit County
WA
Smith County
TX
Snohomish County
WA
Solano County
CA
Somerset County
NJ
Sonoma County
CA
Spartanburg County

SC
Spokane County
WA
St. Charles County
MO
St. Clair County
IL
MI
St. Joseph County
IN
St. Landry Parish
LA
St. Lawrence County
NY
St. Louis County
MN
MO
St. Louis city
MO
St. Lucie County
FL
St. Mary's County
MD
St. Tammany Parish
LA
Stanislaus County
CA
Stark County
OH
Stearns County
MN
Stephenson County
IL
Steuben County
NY
Stevens County
MN
Story County
IA
Strafford County
NH
Suffolk County
MA
NY
Suffolk city
VA
Sullivan County
TN
Summit County
OH
Sumner County
TN
Sumter County
SC
Sussex County
DE
Tarrant County
TX
Taylor County
TX
Tazewell County
VA
Terrebonne Parish
LA
Thurston County
WA
Tippecanoe County
IN
Tompkins County
NY
Towns County
GA
Travis County
TX
Trumbull County
OH
Tulare County
CA
Tulsa County
OK
Tuscaloosa County
AL
Tuscola County
MI
Twin Falls County
ID
Union County
NJ
PA
Utah County
UT
Vanderburgh County
IN
Ventura County
CA
Victoria County
TX
Vigo County
IN
Virginia Beach city
VA
Volusia County
FL
Wake County
NC
Walker County
TX
Walla Walla County
WA
Ward County
ND
Warren County
KY
MS
NY
OH
Washington County
AR
MD
MN
OH
OR
PA
TN
TX
UT
WI
Washoe County
NV
Washtenaw County
MI
Waukesha County
WI
Wayne County
IN
MI
Webb County
TX
Weber County
UT
Webster County
IA
Weld County
CO
Westchester County
NY
Westmoreland County
PA
Whatcom County
WA
Wicomico County
MD
Will County
IL
Williamsburg city
VA
Williamson County
TN
TX
Winchester city
VA
Winnebago County
IL
WI
Worcester County
MA
Wyandotte County
KS
Yakima County
WA
Yavapai County
AZ
Yellowstone County
MT
Yolo County
CA
York County
ME
PA
Yuma County
AZ

In [93]:
latlong_df = pd.read_csv('county_latlong_name.csv')
latlong_df

       fips state_abbr        lat         lon         name              county
0      1001         AL  32.500383  -86.494186      Autauga      Autauga County
1      1003         AL  30.548923  -87.762466      Baldwin      Baldwin County
2      1005         AL  31.844037  -85.309929      Barbour      Barbour County
3      1007         AL  33.030918  -87.127655         Bibb         Bibb County
4      1009         AL  33.955246  -86.591402       Blount       Blount County
5      1011         AL  32.116326  -85.701202      Bullock      Bullock County
6      1013         AL  31.773538  -86.653511       Butler       Butler County
7      1015         AL  33.725459  -85.819404      Calhoun      Calhoun County
8      1017         AL  32.860437  -85.266519     Chambers     Chambers County
9      1019         AL  34.179333  -85.629197     Cherokee     Cherokee County
10     1021         AL  32.877546  -86.687443      Chilton      Chilton County
11     1023         AL  32.016560  -88.264099      Choctaw      Choctaw County
12     1025         AL  31.685686  -87.815629       Clarke       Clarke County
13     1027         AL  33.272412  -85.820163         Clay         Clay County
14     1029         AL  33.629773  -85.494302     Cleburne     Cleburne County
15     1031         AL  31.354433  -85.904739       Coffee       Coffee County
16     1033         AL  34.723387  -87.685149      Colbert      Colbert County
17     1035         AL  31.418674  -86.996465      Conecuh      Conecuh County
18     1037         AL  32.975931  -86.155047        Coosa        Coosa County
19     1039         AL  31.282448  -86.410990    Covington    Covington County
20     1041         AL  31.743487  -86.297108     Crenshaw     Crenshaw County
21     1043         AL  34.162362  -86.831817      Cullman      Cullman County
22     1045         AL  31.383347  -85.641259         Dale         Dale County
23     1047         AL  32.408818  -87.034935       Dallas       Dallas County
24     1049         AL  34.455112  -85.817037       DeKalb       DeKalb County
25     1051         AL  32.559651  -86.225619       Elmore       Elmore County
26     1053         AL  31.088740  -87.282003     Escambia     Escambia County
27     1055         AL  34.013694  -86.025408       Etowah       Etowah County
28     1057         AL  33.726422  -87.770369      Fayette      Fayette County
29     1059         AL  34.460479  -87.793572     Franklin     Franklin County
...     ...        ...        ...         ...          ...                 ...
3079  54097         WV  38.953839  -80.228754       Upshur       Upshur County
3080  54099         WV  38.261890  -82.491343        Wayne        Wayne County
3081  54101         WV  38.469809  -80.479559      Webster      Webster County
3082  54103         WV  39.626810  -80.758657       Wetzel       Wetzel County
3083  54105         WV  39.052695  -81.392135         Wirt         Wirt County
3084  54107         WV  39.266170  -81.530371         Wood         Wood County
3085  54109         WV  37.628557  -81.564670      Wyoming      Wyoming County
3086  56001         WY  41.314993 -105.598313       Albany       Albany County
3087  56003         WY  44.629496 -108.245238     Big Horn     Big Horn County
3088  56005         WY  44.254398 -105.494889     Campbell     Campbell County
3089  56007         WY  41.670121 -107.083911       Carbon       Carbon County
3090  56009         WY  42.794108 -105.527759     Converse     Converse County
3091  56011         WY  44.432537 -104.624986        Crook        Crook County
3092  56013         WY  43.013591 -108.609169      Fremont      Fremont County
3093  56015         WY  42.046973 -104.220539       Goshen       Goshen County
3094  56017         WY  43.661836 -108.230451  Hot Springs  Hot Springs County
3095  56019         WY  44.290844 -106.693648      Johnson      Johnson County
3096  56021         WY  41.153227 -104.773190      Laramie      Laramie County
3097  56023         WY  42.580437 -110.842774      Lincoln      Lincoln County
3098  56025         WY  42.844219 -106.336872      Natrona      Natrona County
3099  56027         WY  42.809984 -104.465974     Niobrara     Niobrara County
3100  56029         WY  44.615172 -108.973283         Park         Park County
3101  56031         WY  42.102309 -104.928409       Platte       Platte County
3102  56033         WY  44.781090 -106.974427     Sheridan     Sheridan County
3103  56035         WY  42.780897 -109.961033     Sublette     Sublette County
3104  56037         WY  41.580269 -109.294956   Sweetwater   Sweetwater County
3105  56039         WY  43.494176 -110.784367        Teton        Teton County
3106  56041         WY  41.271860 -110.767416        Uinta        Uinta County
3107  56043         WY  44.012141 -107.911549     Washakie     Washakie County
3108  56045         WY  43.910216 -104.312642       Weston       Weston County

[3109 rows x 6 columns]

In [95]:
lats = []
longs = []
fips = []
for county in counties:
#     print(county)
    row = grouped.loc[county]
    name = county.replace(" County", "")
    name = name.replace(" city", "")
    name = name.replace(" Parish", "")
    print(name)
#     name = county.replace(" County", "")
    if len(row) > 1:
        for state in row.index:
            print(state)
            templat = latlong_df[(latlong_df.state_abbr == state) & (latlong_df.name == name)].lat.values[0]
            lats.append(templat)
            templong = latlong_df[(latlong_df.state_abbr == state) & (latlong_df.name == name)].lon.values[0]
            longs.append(templong)
            tempfips = latlong_df[(latlong_df.state_abbr == state) & (latlong_df.name == name)].fips.values[0]
            fips.append(tempfips)
    else:
        state = row.index[0]
        print(state)
#         print(county)
        if state == "PR":
            pass
        else:
            if state == "AK" or state == "HI":
                templat = 0
                templong=0
                tempfips = 0
            else:
                if county == "DoÌ±a Ana County":
                    name = "Doña Ana"
                templat = latlong_df[(latlong_df.state_abbr == state) & (latlong_df.name == name)].lat.values[0]
                templong = latlong_df[(latlong_df.state_abbr == state) & (latlong_df.name == name)].lon.values[0]
                tempfips = latlong_df[(latlong_df.state_abbr == state) & (latlong_df.name == name)].fips.values[0]
        lats.append(templat)
        longs.append(templong)
        fips.append(tempfips)

Ada
ID
Adair
MO
Adams
CO
IL
Aiken
SC
Alachua
FL
Alameda
CA
Alamosa
CO
Albany
NY
Albemarle
VA
Alexandria
VA
Allegan
MI
Allegany
MD
Allegheny
PA
Allen
IN
Anchorage Municipality
AK
Anderson
SC
TX
Androscoggin
ME
Angelina
TX
Anne Arundel
MD
Anoka
MN
Arapahoe
CO
Arlington
VA
Ascension
LA
Atlantic
NJ
Augusta
VA
Baldwin
AL
GA
Baltimore
MD
Baltimore
MD
Bannock
ID
Barnstable
MA
Bartholomew
IN
Bartow
GA
Bay
FL
MI
Beaver
PA
Bedford
VA
Bell
TX
Bennington
VT
Benton
AR
OR
WA
Bergen
NJ
Berks
PA
Berkshire
MA
Bernalillo
NM
Berrien
MI
Bexar
TX
Bibb
GA
Black Hawk
IA
Blair
PA
Blount
TN
Blue Earth
MN
Bonneville
ID
Boone
KY
MO
Bossier
LA
Botetourt
VA
Boulder
CO
Bowie
TX
Boyd
KY
Bradford
PA
Brazoria
TX
Brazos
TX
Brevard
FL
Bristol
MA
Bronx
NY
Broome
NY
Broward
FL
Brown
SD
WI
Bucks
PA
Buncombe
NC
Burke
NC
Burleigh
ND
Burlington
NJ
Butler
OH
Butte
CA
Cabell
WV
Cache
UT
Caddo
LA
Calcasieu
LA
Calhoun
AL
MI
Calvert
MD
Camden
NJ
Cameron
TX
Campbell
KY
Cape Girardeau
MO
Carroll
GA
Cascade
MT
Cass
ND
Catawba
NC
Cattaraugus
NY
Cayuga
NY
Cecil
MD
Centre
PA
Champaign
IL
Charles
MD
Charleston
SC
Charlotte
FL
Charlottesville
VA
Chatham
GA
Chelan
WA
Cherokee
GA
Chesapeake
VA
Cheshire
NH
Chester
PA
Chesterfield
VA
Chippewa
MI
Chisago
MN
Chittenden
VT
Christian
KY
Citrus
FL
Clackamas
OR
Clarion
PA
Clark
IN
NV
WA
Clarke
GA
Clay
FL
MO
Clinton
OH
Cobb
GA
Coffee
TN
Collier
FL
Collin
TX
Columbia
GA
Comal
TX
Comanche
OK
Contra Costa
CA
Cook
IL
Coos
OR
Coweta
GA
Craighead
AR
Craven
NC
Crow Wing
MN
Cumberland
ME
NC
NJ
PA
Cuyahoga
OH
Dakota
MN
Dallas
IA
TX
Dane
WI
Dauphin
PA
Davidson
TN
Daviess
KY
Davis
UT
DeKalb
GA
IL
Delaware
IN
PA
Denton
TX
Denver
CO
Deschutes
OR
Dickson
TN
District of Columbia
DC
Dorchester
SC
Douglas
CO
KS
NE
DoÌ±a Ana
NM
DuPage
IL
Dubuque
IA
Durham
NC
Dutchess
NY
Duval
FL
East Baton Rouge
LA
Eau Claire
WI
Ector
TX
Eddy
NM
El Paso
CO
TX
Elkhart
IN
Ellis
TX
Emmet
MI
Erie
NY
OH
PA
Escambia
FL
Essex
MA
NJ
Fairbanks North Star Borough
AK
Fairfax
VA
Fairfield
CT
Falls Church
VA
Fauquier
VA
Fayette
GA
KY
Florence
SC
Floyd
GA
IN
Forsyth
GA
NC
Fort Bend
TX
Franklin
MO
NY
OH
VT
Frederick
MD
Fredericksburg
VA
Fresno
CA
Fulton
GA
Gallatin
MT
Gallia
OH
Galveston
TX
Garfield
CO
OK
Garland
AR
Genesee
MI
Gloucester
NJ
Goodhue
MN
Grafton
NH
Grand Forks
ND
Grand Traverse
MI
Green
WI
Greene
MO
OH
Greenville
SC
Greenwood
SC
Gregg
TX
Guilford
NC
Gwinnett
GA
Hall
GA
Hamilton
IN
OH
TN
Hampden
MA
Hampshire
MA
Hancock
OH
WV
Hardin
KY
Harford
MD
Harris
TX
Harrison
KY
MS
Harrisonburg
VA
Hartford
CT
Hawaii
HI
Hennepin
MN
Henrico
VA
Henry
GA
IN
Hernando
FL
Hidalgo
TX
Hillsborough
FL
NH
Hinds
MS
Honolulu
HI
Horry
SC
Houston
AL
GA
Howard
IN
MD
Hudson
NJ
Humboldt
CA
Imperial
CA
Indian River
FL
Ingham
MI
Iredell
NC
Jackson
IL
MI
MO
MS
OR
Jasper
SC
Jefferson
AL
CO
KY
MO
NY
TX
Jefferson
LA
Johnson
IA
IN
KS
MO
Kalamazoo
MI
Kanawha
WV
Kandiyohi
MN
Kane
IL
Kankakee
IL
Kenai Peninsula Borough
AK
Kendall
IL
TX
Kennebec
ME
Kenosha
WI
Kent
DE
MI
RI
Kenton
KY
Kern
CA
Kerr
TX
King
WA
Kings
NY
Kitsap
WA
Knox
TN
Kootenai
ID
La Crosse
WI
La Plata
CO
LaPorte
IN
Lackawanna
PA
Lafayette
LA
Lake
FL
IL
IN
OH
Lamar
MS
Lancaster
NE
PA
Lane
OR
Laramie
WY
Larimer
CO
Lauderdale
AL
MS
Laurens
GA
Leavenworth
KS
Lee
AL
FL
GA
MS
Lehigh
PA
Lenoir
NC
Leon
FL
Lewis and Clark
MT
Lexington
SC
Licking
OH
Lincoln
SD
Linn
IA
Litchfield
CT
Livingston
MI
Lorain
OH
Los Alamos
NM
Los Angeles
CA
Loudoun
VA
Lowndes
GA
Lubbock
TX
Lucas
OH
Luzerne
PA
Lycoming
PA
Lynchburg
VA
Macomb
MI
Macon
IL
Madison
AL
IL
TN
Mahoning
OH
Manatee
FL
Marathon
WI
Maricopa
AZ
Marion
FL
IN
OH
OR
Marquette
MI
Matanuska-Susitna Borough
AK
Maury
TN
McCracken
KY
McHenry
IL
McLean
IL
McLennan
TX
Mecklenburg
NC
Medina
OH
TX
Mendocino
CA
Merced
CA
Mercer
NJ
PA
WV
Mesa
CO
Miami-Dade
FL
Middlesex
MA
NJ
Midland
MI
TX
Mifflin
PA
Milwaukee
WI
Minnehaha
SD
Missoula
MT
Mobile
AL
Mohave
AZ
Monmouth
NJ
Monongalia
WV
Monroe
IN
MI
NY
PA
Monterey
CA
Montgomery
AL
MD
OH
PA
TN
TX
VA
Montour
PA
Moore
NC
Morgan
AL
Morris
NJ
Multnomah
OR
Muscogee
GA
Muskegon
MI
Muskogee
OK
Nacogdoches
TX
Napa
CA
Nash
NC
Nassau
NY
Nevada
CA
New Castle
DE
New Hanover
NC
New Haven
CT
New London
CT
New York
NY
Newport News
VA
Niagara
NY
Norfolk
MA
Northampton
PA
Nueces
TX
Oakland
MI
Ocean
NJ
Ohio
WV
Okaloosa
FL
Oklahoma
OK
Olmsted
MN
Oneida
NY
Onondaga
NY
Onslow
NC
Ontario
NY
Orange
CA
FL
NC
NY
Orleans
LA
Osceola
FL
Otsego
NY
Ottawa
MI
Ouachita
LA
Outagamie
WI
Ozaukee
WI
Palm Beach
FL
Pasco
FL
Pasquotank
NC
Passaic
NJ
Pennington
SD
Penobscot
ME
Peoria
IL
Phelps
MO
Philadelphia
PA
Pierce
WA
Pike
KY
Pima
AZ
Pinellas
FL
Pitt
NC
Placer
CA
Plymouth
MA
Polk
FL
IA
Porter
IN
Pottawatomie
OK
Potter
TX
Prince George's
MD
Prince William
VA
Providence
RI
Pueblo
CO
Pulaski
AR
KY
Putnam
NY
TN
Queens
NY
Racine
WI
Ramsey
MN
Randolph
NC
Rapides
LA
Reno
KS
Richland
SC
Richmond
GA
NY
Richmond
VA
Riverside
CA
Roanoke
VA
Rock
WI
Rock Island
IL
Rockdale
GA
Rockingham
NH
Rockland
NY
Ross
OH
Rutherford
TN
Sacramento
CA
Saginaw
MI
Salem
VA
Saline
KS
Salt Lake
UT
San Bernardino
CA
San Diego
CA
San Francisco
CA
San Joaquin
CA
San Luis Obispo
CA
San Mateo
CA
Sangamon
IL
Santa Barbara
CA
Santa Clara
CA
Santa Cruz
CA
Santa Fe
NM
Sarasota
FL
Saratoga
NY
Sarpy
NE
Schenectady
NY
Schuylkill
PA
Scott
IA
Sebastian
AR
Sedgwick
KS
Seminole
FL
Sevier
TN
Shawnee
KS
Sheboygan
WI
Shelby
TN
Sherburne
MN
Skagit
WA
Smith
TX
Snohomish
WA
Solano
CA
Somerset
NJ
Sonoma
CA
Spartanburg
SC
Spokane
WA
St. Charles
MO
St. Clair
IL
MI
St. Joseph
IN
St. Landry
LA
St. Lawrence
NY
St. Louis
MN
MO
St. Louis
MO
St. Lucie
FL
St. Mary's
MD
St. Tammany
LA
Stanislaus
CA
Stark
OH
Stearns
MN
Stephenson
IL
Steuben
NY
Stevens
MN
Story
IA
Strafford
NH
Suffolk
MA
NY
Suffolk
VA
Sullivan
TN
Summit
OH
Sumner
TN
Sumter
SC
Sussex
DE
Tarrant
TX
Taylor
TX
Tazewell
VA
Terrebonne
LA
Thurston
WA
Tippecanoe
IN
Tompkins
NY
Towns
GA
Travis
TX
Trumbull
OH
Tulare
CA
Tulsa
OK
Tuscaloosa
AL
Tuscola
MI
Twin Falls
ID
Union
NJ
PA
Utah
UT
Vanderburgh
IN
Ventura
CA
Victoria
TX
Vigo
IN
Virginia Beach
VA
Volusia
FL
Wake
NC
Walker
TX
Walla Walla
WA
Ward
ND
Warren
KY
MS
NY
OH
Washington
AR
MD
MN
OH
OR
PA
TN
TX
UT
WI
Washoe
NV
Washtenaw
MI
Waukesha
WI
Wayne
IN
MI
Webb
TX
Weber
UT
Webster
IA
Weld
CO
Westchester
NY
Westmoreland
PA
Whatcom
WA
Wicomico
MD
Will
IL
Williamsburg
VA
Williamson
TN
TX
Winchester
VA
Winnebago
IL
WI
Worcester
MA
Wyandotte
KS
Yakima
WA
Yavapai
AZ
Yellowstone
MT
Yolo
CA
York
ME
PA
Yuma
AZ

In [66]:
[int(x.replace(',', '')) for x in pop_est_values]

[481587,
 25343,
 517421,
 65435,
 170872,
 269043,
 1671329,
 16233,
 305506,
 109330,
 159428,
 118081,
 70416,
 1216045,
 379299,
 288000,
 202558,
 57735,
 108277,
 86715,
 579234,
 356921,
 656590,
 236842,
 126604,
 263670,
 75558,
 223234,
 44890,
 827370,
 593490,
 87808,
 212990,
 83779,
 107738,
 174705,
 103126,
 163929,
 78997,
 362924,
 35470,
 279141,
 93053,
 204390,
 932202,
 421164,
 124944,
 679121,
 153401,
 2003554,
 153159,
 131228,
 121829,
 133088,
 67653,
 119062,
 133581,
 180463,
 127039,
 33419,
 326196,
 93245,
 46718,
 60323,
 374264,
 229211,
 601942,
 565217,
 1418207,
 190488,
 1952778,
 38839,
 264542,
 628270,
 261191,
 90485,
 95626,
 445349,
 383134,
 219186,
 91945,
 128289,
 240204,
 203436,
 113605,
 134159,
 92525,
 506471,
 423163,
 93584,
 78871,
 119992,
 81366,
 181923,
 159551,
 76117,
 76576,
 102855,
 162385,
 209689,
 163257,
 411406,
 188910,
 47266,
 289430,
 77200,
 258773,
 244835,
 76085,
 524989,
 352802,
 37349,
 56579,
 163774,
 70461,
 149657,
 418187,
 38438,
 118302,
 2266715,
 488241,
 128331,
 219252,
 249948,
 41968,
 760141,
 56520,
 384902,
 1034730,
 156714,
 156209,
 120749,
 1153526,
 5150233,
 64487,
 148509,
 110332,
 102139,
 65055,
 295003,
 335509,
 149527,
 253370,
 1235072,
 429021,
 93453,
 2635516,
 546695,
 278299,
 694144,
 101511,
 355481,
 759297,
 104897,
 114135,
 566747,
 887207,
 727211,
 197692,
 53948,
 705749,
 162809,
 351154,
 122259,
 571327,
 218195,
 922921,
 97311,
 321488,
 294218,
 957755,
 440059,
 104646,
 166223,
 58460,
 720403,
 839238,
 206341,
 184826,
 33415,
 918702,
 74266,
 269728,
 318316,
 789034,
 798975,
 96849,
 1147532,
 943332,
 14617,
 71222,
 114421,
 323152,
 138293,
 98498,
 78522,
 244252,
 382295,
 811688,
 103967,
 50022,
 1316756,
 49402,
 259547,
 29036,
 999101,
 1063937,
 114434,
 29898,
 342139,
 60061,
 61056,
 99386,
 405813,
 291636,
 46340,
 89886,
 69451,
 93088,
 36960,
 293086,
 168937,
 523542,
 70811,
 123945,
 537174,
 936250,
 204441,
 338011,
 817473,
 367804,
 466372,
 160830,
 75783,
 28810,
 110958,
 255441,
 4713325,
 18886,
 208080,
 53016,
 891720,
 201513,
 1265843,
 330818,
 234561,
 47972,
 193920,
 868707,
 1471968,
 417025,
 231840,
 974563,
 354081,
 105882,
 157863,
 82544,
 325690,
 672391,
 135558,
 181215,
 159923,
 292406,
 181806,
 56750,
 158510,
 703011,
 143617,
 220944,
 30073,
 658573,
 582881,
 766757,
 225081,
 109834,
 251565,
 432493,
 151140,
 158167,
 602401,
 54062,
 265066,
 178124,
 43199,
 532403,
 109862,
 58708,
 128990,
 47431,
 122302,
 169561,
 180786,
 656955,
 164292,
 166998,
 900202,
 52600,
 2252782,
 2559903,
 271473,
 470313,
 165697,
 118016,
 56221,
 109888,
 209674,
 244390,
 367118,
 696535,
 485493,
 230149,
 63343,
 319090,
 545724,
 382067,
 99500,
 356899,
 92729,
 74125,
 47546,
 81758,
 164542,
 770577,
 29992,
 85436,
 369318,
 55949,
 293582,
 69432,
 298750,
 176862,
 61128,
 226706,
 180333,
 191995,
 309833,
 19369,
 10039107,
 413538,
 117406,
 310569,
 428348,
 317417,
 113299,
 82168,
 873972,
 104009,
 372909,
 262966,
 97984,
 228683,
 403253,
 135692,
 4485414,
 365579,
 964582,
 65093,
 347818,
 66699,
 108317,
 96387,
 65418,
 307774,
 171517,
 256623,
 1110356,
 179746,
 51584,
 86749,
 277680,
 367430,
 109424,
 58758,
 154210,
 2716940,
 1611699,
 825062,
 83156,
 176832,
 46138,
 945726,
 193134,
 119600,
 413210,
 212181,
 618795,
 105612,
 148431,
 150500,
 741770,
 170271,
 434061,
 226486,
 1050688,
 531687,
 830915,
 208993,
 607391,
 98535,
 18230,
 100880,
 119679,
 491845,
 812855,
 195769,
 173566,
 67997,
 65204,
 137744,
 94298,
 1356924,
 99755,
 558753,
 234473,
 854757,
 265206,
 1628706,
 179225,
 209281,
 706775,
 305285,
 362294,
 1257584,
 607186,
 41411,
 210738,
 797434,
 158293,
 228671,
 460528,
 197938,
 109777,
 3175692,
 1393452,
 148476,
 384940,
 390144,
 375751,
 59493,
 291830,
 153279,
 187885,
 89221,
 1496770,
 553947,
 39824,
 501826,
 113775,
 152148,
 179179,
 44573,
 1584064,
 904980,
 57876,
 1047279,
 974996,
 180742,
 398329,
 521202,
 724777,
 490161,
 170389,
 72592,
 117415,
 909327,
 470335,
 638931,
 168424,
 391911,
 64979,
 98320,
 80245,
 2253858,
 196311,
 550321,
 143667,
 129648,
 61998,
 415759,
 202518,
 476143,
 230436,
 2470546,
 99143,
 163354,
 141879,
 90896,
 309769,
 325789,
 76666,
 332285,
 1552058,
 190539,
 25301,
 54224,
 1160437,
 2180085,
 3338330,
 881549,
 762148,
 283111,
 766573,
 194672,
 446499,
 1927852,
 273213,
 150358,
 433742,
 229863,
 187196,
 155299,
 141359,
 172943,
 127827,
 516042,
 471826,
 98250,
 176875,
 115340,
 937166,
 97238,
 129205,
 232751,
 822083,
 447643,
 328934,
 494336,
 319785,
 522798,
 402022,
 259686,
 159128,
 271826,
 82124,
 107740,
 199070,
 994205,
 300576,
 328297,
 113510,
 260419,
 550660,
 370606,
 161075,
 44498,
 95379,
 9805,
 97117,
 130633,
 803907,
 1476601,
 92108,
 158348,
 541013,
 191283,
 106721,
 234225,
 2102515,
 138034,
 40595,
 110461,
 290536,
 195732,
 102180,
 12037,
 1273954,
 197974,
 466195,
 651552,
 209355,
 52245,
 86878,
 556341,
 44923,
 636235,
 181451,
 846006,
 92084,
 107038,
 449974,
 553284,
 1111761,
 72971,
 60760,
 67641,
 132896,
 45381,
 63944,
 234602,
 239187,
 151049,
 262440,
 59911,
 601592,
 206865,
 129375,
 35882,
 177556,
 136034,
 471519,
 367601,
 404198,
 65884,
 1749343,
 276652,
 260213,
 35904,
 324492,
 967506,
 348899,
 229247,
 103609,
 690743,
 14954,
 238412,
 590551,
 28078,
 282572,
 171907,
 830622,
 165429,
 250873,
 235099,
 161300,
 220500,
 207641,
 449058,
 213787]

In [132]:
grouped["pop_est"] = [int(x.replace(',', '')) for x in pop_est_values]
grouped

                              National Provider Identifier  pop_est
County                 State
Ada County             ID                                5   481587
Adair County           MO                                1    25343
Adams County           CO                                9   517421
                       IL                                2    65435
Aiken County           SC                                1   170872
Alachua County         FL                                5   269043
Alameda County         CA                                9  1671329
Alamosa County         CO                                1    16233
Albany County          NY                               10   305506
Albemarle County       VA                               11   109330
Alexandria city        VA                                3   159428
Allegan County         MI                                1   118081
Allegany County        MD                                1    70416
Allegheny County       PA                               17  1216045
Allen County           IN                                7   379299
Anchorage Municipality AK                                5   288000
Anderson County        SC                                1   202558
                       TX                                1    57735
Androscoggin County    ME                                1   108277
Angelina County        TX                                1    86715
Anne Arundel County    MD                                9   579234
Anoka County           MN                                2   356921
Arapahoe County        CO                                5   656590
Arlington County       VA                                2   236842
Ascension Parish       LA                                1   126604
Atlantic County        NJ                                1   263670
Augusta County         VA                                1    75558
Baldwin County         AL                                2   223234
                       GA                                1    44890
Baltimore County       MD                               12   827370
...                                                    ...      ...
Washington County      WI                                1   136034
Washoe County          NV                                5   471519
Washtenaw County       MI                               14   367601
Waukesha County        WI                                2   404198
Wayne County           IN                                1    65884
                       MI                               21  1749343
Webb County            TX                                2   276652
Weber County           UT                                3   260213
Webster County         IA                                1    35904
Weld County            CO                                1   324492
Westchester County     NY                               25   967506
Westmoreland County    PA                                1   348899
Whatcom County         WA                                3   229247
Wicomico County        MD                                1   103609
Will County            IL                                5   690743
Williamsburg city      VA                                3    14954
Williamson County      TN                                8   238412
                       TX                                7   590551
Winchester city        VA                                2    28078
Winnebago County       IL                                2   282572
                       WI                                2   171907
Worcester County       MA                               12   830622
Wyandotte County       KS                                4   165429
Yakima County          WA                                1   250873
Yavapai County         AZ                                1   235099
Yellowstone County     MT                                3   161300
Yolo County            CA                                2   220500
York County            ME                                1   207641
                       PA                                3   449058
Yuma County            AZ                                1   213787

[628 rows x 2 columns]

In [135]:
grouped["normalized"] = 100000*grouped["National Provider Identifier"]/grouped["pop_est"]

In [136]:
grouped

                              National Provider Identifier  pop_est  \
County                 State
Ada County             ID                                5   481587
Adair County           MO                                1    25343
Adams County           CO                                9   517421
                       IL                                2    65435
Aiken County           SC                                1   170872
Alachua County         FL                                5   269043
Alameda County         CA                                9  1671329
Alamosa County         CO                                1    16233
Albany County          NY                               10   305506
Albemarle County       VA                               11   109330
Alexandria city        VA                                3   159428
Allegan County         MI                                1   118081
Allegany County        MD                                1    70416
Allegheny County       PA                               17  1216045
Allen County           IN                                7   379299
Anchorage Municipality AK                                5   288000
Anderson County        SC                                1   202558
                       TX                                1    57735
Androscoggin County    ME                                1   108277
Angelina County        TX                                1    86715
Anne Arundel County    MD                                9   579234
Anoka County           MN                                2   356921
Arapahoe County        CO                                5   656590
Arlington County       VA                                2   236842
Ascension Parish       LA                                1   126604
Atlantic County        NJ                                1   263670
Augusta County         VA                                1    75558
Baldwin County         AL                                2   223234
                       GA                                1    44890
Baltimore County       MD                               12   827370
...                                                    ...      ...
Washington County      WI                                1   136034
Washoe County          NV                                5   471519
Washtenaw County       MI                               14   367601
Waukesha County        WI                                2   404198
Wayne County           IN                                1    65884
                       MI                               21  1749343
Webb County            TX                                2   276652
Weber County           UT                                3   260213
Webster County         IA                                1    35904
Weld County            CO                                1   324492
Westchester County     NY                               25   967506
Westmoreland County    PA                                1   348899
Whatcom County         WA                                3   229247
Wicomico County        MD                                1   103609
Will County            IL                                5   690743
Williamsburg city      VA                                3    14954
Williamson County      TN                                8   238412
                       TX                                7   590551
Winchester city        VA                                2    28078
Winnebago County       IL                                2   282572
                       WI                                2   171907
Worcester County       MA                               12   830622
Wyandotte County       KS                                4   165429
Yakima County          WA                                1   250873
Yavapai County         AZ                                1   235099
Yellowstone County     MT                                3   161300
Yolo County            CA                                2   220500
York County            ME                                1   207641
                       PA                                3   449058
Yuma County            AZ                                1   213787

                              normalized
County                 State
Ada County             ID       1.038234
Adair County           MO       3.945863
Adams County           CO       1.739396
                       IL       3.056468
Aiken County           SC       0.585233
Alachua County         FL       1.858439
Alameda County         CA       0.538494
Alamosa County         CO       6.160291
Albany County          NY       3.273258
Albemarle County       VA      10.061282
Alexandria city        VA       1.881727
Allegan County         MI       0.846876
Allegany County        MD       1.420132
Allegheny County       PA       1.397975
Allen County           IN       1.845510
Anchorage Municipality AK       1.736111
Anderson County        SC       0.493686
                       TX       1.732052
Androscoggin County    ME       0.923557
Angelina County        TX       1.153203
Anne Arundel County    MD       1.553776
Anoka County           MN       0.560348
Arapahoe County        CO       0.761510
Arlington County       VA       0.844445
Ascension Parish       LA       0.789864
Atlantic County        NJ       0.379262
Augusta County         VA       1.323487
Baldwin County         AL       0.895921
                       GA       2.227668
Baltimore County       MD       1.450379
...                                  ...
Washington County      WI       0.735110
Washoe County          NV       1.060403
Washtenaw County       MI       3.808477
Waukesha County        WI       0.494807
Wayne County           IN       1.517819
                       MI       1.200451
Webb County            TX       0.722930
Weber County           UT       1.152902
Webster County         IA       2.785205
Weld County            CO       0.308174
Westchester County     NY       2.583963
Westmoreland County    PA       0.286616
Whatcom County         WA       1.308632
Wicomico County        MD       0.965167
Will County            IL       0.723858
Williamsburg city      VA      20.061522
Williamson County      TN       3.355536
                       TX       1.185334
Winchester city        VA       7.123014
Winnebago County       IL       0.707784
                       WI       1.163420
Worcester County       MA       1.444700
Wyandotte County       KS       2.417956
Yakima County          WA       0.398608
Yavapai County         AZ       0.425353
Yellowstone County     MT       1.859888
Yolo County            CA       0.907029
York County            ME       0.481600
                       PA       0.668065
Yuma County            AZ       0.467755

[628 rows x 3 columns]

In [137]:
grouped.to_csv("grouped_geocoded.csv")

In [100]:
grouped_df = pd.read_csv("grouped_geocoded_corrected.csv")
grouped_df

,County,State,National Provider Identifier,pop_est,normalized
0,Ada County,ID,5,481587,1.038234
1,Adair County,MO,1,25343,3.945863
2,Adams County,CO,9,517421,1.739396
3,Adams County,IL,2,65435,3.056468
4,Aiken County,SC,1,170872,0.585233
5,Alachua County,FL,5,269043,1.858439
6,Alameda County,CA,9,1671329,0.538494
7,Alamosa County,CO,1,16233,6.160291
8,Albany County,NY,10,305506,3.273258
9,Albemarle County,VA,11,109330,10.061282
10,Alexandria County,VA,3,159428,1.881727
11,Allegan County,MI,1,118081,0.846876
12,Allegany County,MD,1,70416,1.420132
13,Allegheny County,PA,17,1216045,1.397975
14,Allen County,IN,7,379299,1.845510
15,Anchorage County,AK,5,288000,1.736111
16,Anderson County,SC,1,202558,0.493686
17,Anderson County,TX,1,57735,1.732052
18,Androscoggin County,ME,1,108277,0.923557
19,Angelina County,TX,1,86715,1.153203
20,Anne Arundel County,MD,9,579234,1.553776
21,Anoka County,MN,2,356921,0.560348
22,Arapahoe County,CO,5,656590,0.761510
23,Arlington County,VA,2,236842,0.844445
24,Ascension County,LA,1,126604,0.789864
25,Atlantic County,NJ,1,263670,0.379262
26,Augusta County,VA,1,75558,1.323487
27,Baldwin County,AL,2,223234,0.895921
28,Baldwin County,GA,1,44890,2.227668
29,Baltimore County,MD,12,827370,1.450379
...,...,...,...,...,...
598,Washington County,WI,1,136034,0.735110
599,Washoe County,NV,5,471519,1.060403
600,Washtenaw County,MI,14,367601,3.808477
601,Waukesha County,WI,2,404198,0.494807
602,Wayne County,IN,1,65884,1.517819
603,Wayne County,MI,21,1749343,1.200451
604,Webb County,TX,2,276652,0.722930
605,Weber County,UT,3,260213,1.152902
606,Webster County,IA,1,35904,2.785205
607,Weld County,CO,1,324492,0.308174
608,Westchester County,NY,25,967506,2.583963
609,Westmoreland County,PA,1,348899,0.286616
610,Whatcom County,WA,3,229247,1.308632
611,Wicomico County,MD,1,103609,0.965167
612,Will County,IL,5,690743,0.723858
613,Williamsburg County,VA,3,14954,20.061522
614,Williamson County,TN,8,238412,3.355536
615,Williamson County,TX,7,590551,1.185334
616,Winchester County,VA,2,28078,7.123014
617,Winnebago County,IL,2,282572,0.707784
618,Winnebago County,WI,2,171907,1.163420
619,Worcester County,MA,12,830622,1.444700
620,Wyandotte County,KS,4,165429,2.417956
621,Yakima County,WA,1,250873,0.398608
622,Yavapai County,AZ,1,235099,0.425353
623,Yellowstone County,MT,3,161300,1.859888
624,Yolo County,CA,2,220500,0.907029
625,York County,ME,1,207641,0.481600
626,York County,PA,3,449058,0.668065
627,Yuma County,AZ,1,213787,0.467755

In [79]:
latlong_df = pd.read_csv('county_latlong_name.csv')
latlong_df

       fips state_abbr        lat         lon         name              county
0      1001         AL  32.500383  -86.494186      Autauga      Autauga County
1      1003         AL  30.548923  -87.762466      Baldwin      Baldwin County
2      1005         AL  31.844037  -85.309929      Barbour      Barbour County
3      1007         AL  33.030918  -87.127655         Bibb         Bibb County
4      1009         AL  33.955246  -86.591402       Blount       Blount County
5      1011         AL  32.116326  -85.701202      Bullock      Bullock County
6      1013         AL  31.773538  -86.653511       Butler       Butler County
7      1015         AL  33.725459  -85.819404      Calhoun      Calhoun County
8      1017         AL  32.860437  -85.266519     Chambers     Chambers County
9      1019         AL  34.179333  -85.629197     Cherokee     Cherokee County
10     1021         AL  32.877546  -86.687443      Chilton      Chilton County
11     1023         AL  32.016560  -88.264099      Choctaw      Choctaw County
12     1025         AL  31.685686  -87.815629       Clarke       Clarke County
13     1027         AL  33.272412  -85.820163         Clay         Clay County
14     1029         AL  33.629773  -85.494302     Cleburne     Cleburne County
15     1031         AL  31.354433  -85.904739       Coffee       Coffee County
16     1033         AL  34.723387  -87.685149      Colbert      Colbert County
17     1035         AL  31.418674  -86.996465      Conecuh      Conecuh County
18     1037         AL  32.975931  -86.155047        Coosa        Coosa County
19     1039         AL  31.282448  -86.410990    Covington    Covington County
20     1041         AL  31.743487  -86.297108     Crenshaw     Crenshaw County
21     1043         AL  34.162362  -86.831817      Cullman      Cullman County
22     1045         AL  31.383347  -85.641259         Dale         Dale County
23     1047         AL  32.408818  -87.034935       Dallas       Dallas County
24     1049         AL  34.455112  -85.817037       DeKalb       DeKalb County
25     1051         AL  32.559651  -86.225619       Elmore       Elmore County
26     1053         AL  31.088740  -87.282003     Escambia     Escambia County
27     1055         AL  34.013694  -86.025408       Etowah       Etowah County
28     1057         AL  33.726422  -87.770369      Fayette      Fayette County
29     1059         AL  34.460479  -87.793572     Franklin     Franklin County
...     ...        ...        ...         ...          ...                 ...
3079  54097         WV  38.953839  -80.228754       Upshur       Upshur County
3080  54099         WV  38.261890  -82.491343        Wayne        Wayne County
3081  54101         WV  38.469809  -80.479559      Webster      Webster County
3082  54103         WV  39.626810  -80.758657       Wetzel       Wetzel County
3083  54105         WV  39.052695  -81.392135         Wirt         Wirt County
3084  54107         WV  39.266170  -81.530371         Wood         Wood County
3085  54109         WV  37.628557  -81.564670      Wyoming      Wyoming County
3086  56001         WY  41.314993 -105.598313       Albany       Albany County
3087  56003         WY  44.629496 -108.245238     Big Horn     Big Horn County
3088  56005         WY  44.254398 -105.494889     Campbell     Campbell County
3089  56007         WY  41.670121 -107.083911       Carbon       Carbon County
3090  56009         WY  42.794108 -105.527759     Converse     Converse County
3091  56011         WY  44.432537 -104.624986        Crook        Crook County
3092  56013         WY  43.013591 -108.609169      Fremont      Fremont County
3093  56015         WY  42.046973 -104.220539       Goshen       Goshen County
3094  56017         WY  43.661836 -108.230451  Hot Springs  Hot Springs County
3095  56019         WY  44.290844 -106.693648      Johnson      Johnson County
3096  56021         WY  41.153227 -104.773190      Laramie      Laramie County
3097  56023         WY  42.580437 -110.842774      Lincoln      Lincoln County
3098  56025         WY  42.844219 -106.336872      Natrona      Natrona County
3099  56027         WY  42.809984 -104.465974     Niobrara     Niobrara County
3100  56029         WY  44.615172 -108.973283         Park         Park County
3101  56031         WY  42.102309 -104.928409       Platte       Platte County
3102  56033         WY  44.781090 -106.974427     Sheridan     Sheridan County
3103  56035         WY  42.780897 -109.961033     Sublette     Sublette County
3104  56037         WY  41.580269 -109.294956   Sweetwater   Sweetwater County
3105  56039         WY  43.494176 -110.784367        Teton        Teton County
3106  56041         WY  41.271860 -110.767416        Uinta        Uinta County
3107  56043         WY  44.012141 -107.911549     Washakie     Washakie County
3108  56045         WY  43.910216 -104.312642       Weston       Weston County

[3109 rows x 6 columns]

In [80]:
counties = np.unique(grouped_df['County'])

In [84]:
lats = []
longs = []
for county in counties:
    row = grouped_df[grouped_df.County == county]
    print(row)
    print(county)
    if len(row) > 1:
        for state in row.State:
            print(state)
            templat = latlong_df[(latlong_df.state_abbr == state) & (latlong_df.county == county)].lat.values[0]
            lats.append(templat)
            templong = latlong_df[(latlong_df.state_abbr == state) & (latlong_df.county == county)].lon.values[0]
            longs.append(templong)
    else:
        #print(row)
        state = row.iloc[0]['State']
        print(state)
        #print(county)
        if state == "PR":
            pass
        else:
            if state == "AK" or state == "HI":
                templat = 0
                templong=0
            else:
                if county == "DoÌÎå±a Ana County":
                    county = "Doña Ana County"
                print(county)
                templat = latlong_df[(latlong_df.state_abbr == state) & (latlong_df.county == county)].lat.values[0]
                templong = latlong_df[(latlong_df.state_abbr == state) & (latlong_df.county == county)].lon.values[0]
        lats.append(templat)
        longs.append(templong)

       County State  National Provider Identifier  pop_est  normalized
0  Ada County    ID                             5   481587    1.038234
Ada County
ID
Ada County
         County State  National Provider Identifier  pop_est  normalized
1  Adair County    MO                             1    25343    3.945863
Adair County
MO
Adair County
         County State  National Provider Identifier  pop_est  normalized
2  Adams County    CO                             9   517421    1.739396
3  Adams County    IL                             2    65435    3.056468
Adams County
CO
IL
         County State  National Provider Identifier  pop_est  normalized
4  Aiken County    SC                             1   170872    0.585233
Aiken County
SC
Aiken County
           County State  National Provider Identifier  pop_est  normalized
5  Alachua County    FL                             5   269043    1.858439
Alachua County
FL
Alachua County
           County State  National Provider Identifier  pop_est  normalized
6  Alameda County    CA                             9  1671329    0.538494
Alameda County
CA
Alameda County
           County State  National Provider Identifier  pop_est  normalized
7  Alamosa County    CO                             1    16233    6.160291
Alamosa County
CO
Alamosa County
          County State  National Provider Identifier  pop_est  normalized
8  Albany County    NY                            10   305506    3.273258
Albany County
NY
Albany County
             County State  National Provider Identifier  pop_est  normalized
9  Albemarle County    VA                            11   109330   10.061282
Albemarle County
VA
Albemarle County
               County State  National Provider Identifier  pop_est  normalized
10  Alexandria County    VA                             3   159428    1.881727
Alexandria County
VA
Alexandria County
            County State  National Provider Identifier  pop_est  normalized
11  Allegan County    MI                             1   118081    0.846876
Allegan County
MI
Allegan County
             County State  National Provider Identifier  pop_est  normalized
12  Allegany County    MD                             1    70416    1.420132
Allegany County
MD
Allegany County
              County State  National Provider Identifier  pop_est  normalized
13  Allegheny County    PA                            17  1216045    1.397975
Allegheny County
PA
Allegheny County
          County State  National Provider Identifier  pop_est  normalized
14  Allen County    IN                             7   379299     1.84551
Allen County
IN
Allen County
              County State  National Provider Identifier  pop_est  normalized
15  Anchorage County    AK                             5   288000    1.736111
Anchorage County
AK
             County State  National Provider Identifier  pop_est  normalized
16  Anderson County    SC                             1   202558    0.493686
17  Anderson County    TX                             1    57735    1.732052
Anderson County
SC
TX
                 County State  National Provider Identifier  pop_est  \
18  Androscoggin County    ME                             1   108277

    normalized
18    0.923557
Androscoggin County
ME
Androscoggin County
             County State  National Provider Identifier  pop_est  normalized
19  Angelina County    TX                             1    86715    1.153203
Angelina County
TX
Angelina County
                 County State  National Provider Identifier  pop_est  \
20  Anne Arundel County    MD                             9   579234

    normalized
20    1.553776
Anne Arundel County
MD
Anne Arundel County
          County State  National Provider Identifier  pop_est  normalized
21  Anoka County    MN                             2   356921    0.560348
Anoka County
MN
Anoka County
             County State  National Provider Identifier  pop_est  normalized
22  Arapahoe County    CO                             5   656590     0.76151
Arapahoe County
CO
Arapahoe County
              County State  National Provider Identifier  pop_est  normalized
23  Arlington County    VA                             2   236842    0.844445
Arlington County
VA
Arlington County
              County State  National Provider Identifier  pop_est  normalized
24  Ascension County    LA                             1   126604    0.789864
Ascension County
LA
Ascension County
             County State  National Provider Identifier  pop_est  normalized
25  Atlantic County    NJ                             1   263670    0.379262
Atlantic County
NJ
Atlantic County
            County State  National Provider Identifier  pop_est  normalized
26  Augusta County    VA                             1    75558    1.323487
Augusta County
VA
Augusta County
            County State  National Provider Identifier  pop_est  normalized
27  Baldwin County    AL                             2   223234    0.895921
28  Baldwin County    GA                             1    44890    2.227668
Baldwin County
AL
GA
              County State  National Provider Identifier  pop_est  normalized
29  Baltimore County    MD                            12   827370    1.450379
30  Baltimore County    MD                             9   593490    1.516454
Baltimore County
MD
MD
            County State  National Provider Identifier  pop_est  normalized
31  Bannock County    ID                             1    87808    1.138848
Bannock County
ID
Bannock County
               County State  National Provider Identifier  pop_est  normalized
32  Barnstable County    MA                             5   212990    2.347528
Barnstable County
MA
Barnstable County
                County State  National Provider Identifier  pop_est  \
33  Bartholomew County    IN                             2    83779

    normalized
33    2.387233
Bartholomew County
IN
Bartholomew County
           County State  National Provider Identifier  pop_est  normalized
34  Bartow County    GA                             1   107738    0.928178
Bartow County
GA
Bartow County
        County State  National Provider Identifier  pop_est  normalized
35  Bay County    FL                             3   174705    1.717180
36  Bay County    MI                             1   103126    0.969688
Bay County
FL
MI
           County State  National Provider Identifier  pop_est  normalized
37  Beaver County    PA                             1   163929     0.61002
Beaver County
PA
Beaver County
            County State  National Provider Identifier  pop_est  normalized
38  Bedford County    VA                             1    78997    1.265871
Bedford County
VA
Bedford County
         County State  National Provider Identifier  pop_est  normalized
39  Bell County    TX                             2   362924     0.55108
Bell County
TX
Bell County
               County State  National Provider Identifier  pop_est  normalized
40  Bennington County    VT                             1    35470    2.819284
Bennington County
VT
Bennington County
           County State  National Provider Identifier  pop_est  normalized
41  Benton County    AR                             4   279141    1.432968
42  Benton County    OR                             1    93053    1.074656
43  Benton County    WA                             2   204390    0.978521
Benton County
AR
OR
WA
           County State  National Provider Identifier  pop_est  normalized
44  Bergen County    NJ                            30   932202    3.218187
Bergen County
NJ
Bergen County
          County State  National Provider Identifier  pop_est  normalized
45  Berks County    PA                             6   421164    1.424623
Berks County
PA
Berks County
              County State  National Provider Identifier  pop_est  normalized
46  Berkshire County    MA                             1   124944    0.800359
Berkshire County
MA
Berkshire County
               County State  National Provider Identifier  pop_est  normalized
47  Bernalillo County    NM                            10   679121    1.472492
Bernalillo County
NM
Bernalillo County
            County State  National Provider Identifier  pop_est  normalized
48  Berrien County    MI                             2   153401    1.303772
Berrien County
MI
Berrien County
          County State  National Provider Identifier  pop_est  normalized
49  Bexar County    TX                            25  2003554    1.247783
Bexar County
TX
Bexar County
         County State  National Provider Identifier  pop_est  normalized
50  Bibb County    GA                             2   153159    1.305833
Bibb County
GA
Bibb County
               County State  National Provider Identifier  pop_est  normalized
51  Black Hawk County    IA                             2   131228    1.524065
Black Hawk County
IA
Black Hawk County
          County State  National Provider Identifier  pop_est  normalized
52  Blair County    PA                             3   121829    2.462468
Blair County
PA
Blair County
           County State  National Provider Identifier  pop_est  normalized
53  Blount County    TN                             1   133088    0.751383
Blount County
TN
Blount County
               County State  National Provider Identifier  pop_est  normalized
54  Blue Earth County    MN                             2    67653    2.956262
Blue Earth County
MN
Blue Earth County
               County State  National Provider Identifier  pop_est  normalized
55  Bonneville County    ID                             2   119062    1.679797
Bonneville County
ID
Bonneville County
          County State  National Provider Identifier  pop_est  normalized
56  Boone County    KY                             2   133581    1.497219
57  Boone County    MO                             2   180463    1.108260
Boone County
KY

MO
            County State  National Provider Identifier  pop_est  normalized
58  Bossier County    LA                             1   127039     0.78716
Bossier County
LA
Bossier County
              County State  National Provider Identifier  pop_est  normalized
59  Botetourt County    VA                             1    33419     2.99231
Botetourt County
VA
Botetourt County
            County State  National Provider Identifier  pop_est  normalized
60  Boulder County    CO                             4   326196    1.226257
Boulder County
CO
Boulder County
          County State  National Provider Identifier  pop_est  normalized
61  Bowie County    TX                             1    93245    1.072444
Bowie County
TX
Bowie County
         County State  National Provider Identifier  pop_est  normalized
62  Boyd County    KY                             2    46718    4.281005
Boyd County
KY
Boyd County
             County State  National Provider Identifier  pop_est  normalized
63  Bradford County    PA                             1    60323    1.657742
Bradford County
PA
Bradford County
             County State  National Provider Identifier  pop_est  normalized
64  Brazoria County    TX                             3   374264    0.801573
Brazoria County
TX
Brazoria County
           County State  National Provider Identifier  pop_est  normalized
65  Brazos County    TX                             4   229211    1.745117
Brazos County
TX
Brazos County
            County State  National Provider Identifier  pop_est  normalized
66  Brevard County    FL                             6   601942    0.996774
Brevard County
FL
Brevard County
            County State  National Provider Identifier  pop_est  normalized
67  Bristol County    MA                             8   565217    1.415386
Bristol County
MA
Bristol County
          County State  National Provider Identifier  pop_est  normalized
68  Bronx County    NY                            12  1418207    0.846139
Bronx County
NY
Bronx County
           County State  National Provider Identifier  pop_est  normalized
69  Broome County    NY                             2   190488    1.049935
Broome County
NY
Broome County
            County State  National Provider Identifier  pop_est  normalized
70  Broward County    FL                            16  1952778    0.819346
Broward County
FL
Broward County
          County State  National Provider Identifier  pop_est  normalized
71  Brown County    SD                             1    38839    2.574732
72  Brown County    WI                             5   264542    1.890059
Brown County
SD
WI
          County State  National Provider Identifier  pop_est  normalized
73  Bucks County    PA                             6   628270    0.955003
Bucks County
PA
Bucks County
             County State  National Provider Identifier  pop_est  normalized
74  Buncombe County    NC                            11   261191    4.211477
Buncombe County
NC
Buncombe County
          County State  National Provider Identifier  pop_est  normalized
75  Burke County    NC                             1    90485    1.105156
Burke County
NC
Burke County
             County State  National Provider Identifier  pop_est  normalized
76  Burleigh County    ND                             3    95626    3.137222
Burleigh County
ND
Burleigh County
               County State  National Provider Identifier  pop_est  normalized
77  Burlington County    NJ                             9   445349    2.020887
Burlington County
NJ
Burlington County
           County State  National Provider Identifier  pop_est  normalized
78  Butler County    OH                             3   383134    0.783016
Butler County
OH
Butler County
          County State  National Provider Identifier  pop_est  normalized
79  Butte County    CA                             2   219186    0.912467
Butte County
CA
Butte County
           County State  National Provider Identifier  pop_est  normalized
80  Cabell County    WV                             1    91945    1.087607
Cabell County
WV
Cabell County
          County State  National Provider Identifier  pop_est  normalized
81  Cache County    UT                             1   128289     0.77949
Cache County
UT
Cache County
          County State  National Provider Identifier  pop_est  normalized
82  Caddo County    LA                             4   240204    1.665251
Caddo County
LA
Caddo County
              County State  National Provider Identifier  pop_est  normalized
83  Calcasieu County    LA                             1   203436    0.491555
Calcasieu County
LA
Calcasieu County
            County State  National Provider Identifier  pop_est  normalized
84  Calhoun County    AL                             1   113605    0.880243
85  Calhoun County    MI                             3   134159    2.236153
Calhoun County
AL
MI
            County State  National Provider Identifier  pop_est  normalized
86  Calvert County    MD                             1    92525    1.080789
Calvert County
MD
Calvert County
           County State  National Provider Identifier  pop_est  normalized
87  Camden County    NJ                             3   506471    0.592334
Camden County
NJ
Camden County
            County State  National Provider Identifier  pop_est  normalized
88  Cameron County    TX                             3   423163    0.708947
Cameron County
TX
Cameron County
             County State  National Provider Identifier  pop_est  normalized
89  Campbell County    KY                             1    93584    1.068559
Campbell County
KY
Campbell County
                   County State  National Provider Identifier  pop_est  \
90  Cape Girardeau County    MO                             1    78871

    normalized
90    1.267893
Cape Girardeau County
MO
Cape Girardeau County
            County State  National Provider Identifier  pop_est  normalized
91  Carroll County    GA                             2   119992    1.666778
Carroll County
GA
Carroll County
            County State  National Provider Identifier  pop_est  normalized
92  Cascade County    MT                             1    81366    1.229015
Cascade County
MT
Cascade County
         County State  National Provider Identifier  pop_est  normalized
93  Cass County    ND                             2   181923    1.099366
Cass County
ND
Cass County
            County State  National Provider Identifier  pop_est  normalized
94  Catawba County    NC                             2   159551    1.253518
Catawba County
NC
Catawba County
                County State  National Provider Identifier  pop_est  \
95  Cattaraugus County    NY                             2    76117

    normalized
95    2.627534
Cattaraugus County
NY
Cattaraugus County
           County State  National Provider Identifier  pop_est  normalized
96  Cayuga County    NY                             1    76576    1.305892
Cayuga County
NY
Cayuga County
          County State  National Provider Identifier  pop_est  normalized
97  Cecil County    MD                             1   102855    0.972242
Cecil County
MD
Cecil County
           County State  National Provider Identifier  pop_est  normalized
98  Centre County    PA                             2   162385    1.231641
Centre County
PA
Centre County
              County State  National Provider Identifier  pop_est  normalized
99  Champaign County    IL                             1   209689    0.476897
Champaign County
IL
Champaign County
             County State  National Provider Identifier  pop_est  normalized
100  Charles County    MD                             1   163257    0.612531
Charles County
MD
Charles County
                County State  National Provider Identifier  pop_est  \
101  Charleston County    SC                            15   411406

     normalized
101    3.646033
Charleston County
SC
Charleston County
               County State  National Provider Identifier  pop_est  normalized
102  Charlotte County    FL                             2   188910    1.058705
Charlotte County
FL
Charlotte County
                     County State  National Provider Identifier  pop_est  \
103  Charlottesville County    VA                             3    47266

     normalized
103    6.347057
Charlottesville County
VA
Charlottesville County
             County State  National Provider Identifier  pop_est  normalized
104  Chatham County    GA                             6   289430     2.07304
Chatham County
GA
Chatham County
            County State  National Provider Identifier  pop_est  normalized
105  Chelan County    WA                             1    77200    1.295337
Chelan County
WA
Chelan County
              County State  National Provider Identifier  pop_est  normalized
106  Cherokee County    GA                             2   258773    0.772878
Cherokee County
GA
Cherokee County
                County State  National Provider Identifier  pop_est  \
107  Chesapeake County    VA                             1   244835

     normalized
107    0.408438
Chesapeake County
VA
Chesapeake County
              County State  National Provider Identifier  pop_est  normalized
108  Cheshire County    NH                             2    76085    2.628639
Cheshire County
NH
Cheshire County
             County State  National Provider Identifier  pop_est  normalized
109  Chester County    PA                             8   524989    1.523841
Chester County
PA
Chester County
                  County State  National Provider Identifier  pop_est  \
110  Chesterfield County    VA                             2   352802

     normalized
110     0.56689
Chesterfield County
VA
Chesterfield County
              County State  National Provider Identifier  pop_est  normalized
111  Chippewa County    MI                             1    37349    2.677448
Chippewa County
MI
Chippewa County
             County State  National Provider Identifier  pop_est  normalized
112  Chisago County    MN                             1    56579     1.76744
Chisago County
MN
Chisago County
                County State  National Provider Identifier  pop_est  \
113  Chittenden County    VT                             2   163774

     normalized
113    1.221195
Chittenden County
VT
Chittenden County
               County State  National Provider Identifier  pop_est  normalized
114  Christian County    KY                             1    70461    1.419225
Christian County
KY
Christian County
            County State  National Provider Identifier  pop_est  normalized
115  Citrus County    FL                             1   149657    0.668195
Citrus County
FL
Citrus County
               County State  National Provider Identifier  pop_est  normalized
116  Clackamas County    OR                             1   418187    0.239127
Clackamas County
OR
Clackamas County
             County State  National Provider Identifier  pop_est  normalized
117  Clarion County    PA                             1    38438    2.601592
Clarion County
PA
Clarion County
           County State  National Provider Identifier  pop_est  normalized
118  Clark County    IN                             1   118302    0.845294
119  Clark County    NV                             8  2266715    0.352934
120  Clark County    WA                             6   488241    1.228901
Clark County
IN
NV
WA
            County State  National Provider Identifier  pop_est  normalized
121  Clarke County    GA                             3   128331    2.337705
Clarke County
GA
Clarke County
          County State  National Provider Identifier  pop_est  normalized
122  Clay County    FL                             4   219252    1.824385
123  Clay County    MO                             3   249948    1.200250
Clay County
FL
MO
             County State  National Provider Identifier  pop_est  normalized
124  Clinton County    OH                             1    41968    2.382768
Clinton County
OH
Clinton County
          County State  National Provider Identifier  pop_est  normalized
125  Cobb County    GA                             6   760141    0.789327
Cobb County
GA
Cobb County
            County State  National Provider Identifier  pop_est  normalized
126  Coffee County    TN                             1    56520    1.769285
Coffee County
TN
Coffee County
             County State  National Provider Identifier  pop_est  normalized
127  Collier County    FL                             3   384902    0.779419
Collier County
FL
Collier County

            County State  National Provider Identifier  pop_est  normalized
128  Collin County    TX                            16  1034730    1.546297
Collin County
TX
Collin County
              County State  National Provider Identifier  pop_est  normalized
129  Columbia County    GA                             3   156714    1.914315
Columbia County
GA
Columbia County
           County State  National Provider Identifier  pop_est  normalized
130  Comal County    TX                             1   156209    0.640168
Comal County
TX
Comal County
              County State  National Provider Identifier  pop_est  normalized
131  Comanche County    OK                             1   120749    0.828164
Comanche County
OK
Comanche County
                  County State  National Provider Identifier  pop_est  \
132  Contra Costa County    CA                            13  1153526

     normalized
132    1.126979
Contra Costa County
CA
Contra Costa County
          County State  National Provider Identifier  pop_est  normalized
133  Cook County    IL                            78  5150233    1.514495
Cook County
IL
Cook County
          County State  National Provider Identifier  pop_est  normalized
134  Coos County    OR                             1    64487      1.5507
Coos County
OR
Coos County
            County State  National Provider Identifier  pop_est  normalized
135  Coweta County    GA                             1   148509     0.67336
Coweta County
GA
Coweta County
               County State  National Provider Identifier  pop_est  normalized
136  Craighead County    AR                             1   110332    0.906355
Craighead County
AR
Craighead County
            County State  National Provider Identifier  pop_est  normalized
137  Craven County    NC                             1   102139    0.979058
Craven County
NC
Craven County
               County State  National Provider Identifier  pop_est  normalized
138  Crow Wing County    MN                             1    65055    1.537161
Crow Wing County
MN
Crow Wing County
                County State  National Provider Identifier  pop_est  \
139  Cumberland County    ME                             5   295003
140  Cumberland County    NC                             3   335509
141  Cumberland County    NJ                             1   149527
142  Cumberland County    PA                             6   253370

     normalized
139    1.694898
140    0.894164
141    0.668776
142    2.368078
Cumberland County
ME
NC
NJ
PA
              County State  National Provider Identifier  pop_est  normalized
143  Cuyahoga County    OH                            28  1235072    2.267074
Cuyahoga County
OH
Cuyahoga County
            County State  National Provider Identifier  pop_est  normalized
144  Dakota County    MN                             2   429021    0.466178
Dakota County
MN
Dakota County
            County State  National Provider Identifier  pop_est  normalized
145  Dallas County    IA                             1    93453    1.070057
146  Dallas County    TX                            39  2635516    1.479786
Dallas County
IA
TX
          County State  National Provider Identifier  pop_est  normalized
147  Dane County    WI                            16   546695    2.926678
Dane County
WI
Dane County
             County State  National Provider Identifier  pop_est  normalized
148  Dauphin County    PA                             5   278299    1.796629
Dauphin County
PA
Dauphin County
              County State  National Provider Identifier  pop_est  normalized
149  Davidson County    TN                            17   694144     2.44906
Davidson County
TN
Davidson County
             County State  National Provider Identifier  pop_est  normalized
150  Daviess County    KY                             2   101511     1.97023
Daviess County
KY
Daviess County
           County State  National Provider Identifier  pop_est  normalized
151  Davis County    UT                             1   355481    0.281309
Davis County
UT
Davis County
            County State  National Provider Identifier  pop_est  normalized
152  DeKalb County    GA                             3   759297    0.395102
153  DeKalb County    IL                             2   104897    1.906632
DeKalb County
GA
IL
              County State  National Provider Identifier  pop_est  normalized
154  Delaware County    IN                             1   114135    0.876155
155  Delaware County    PA                             7   566747    1.235119
Delaware County
IN
PA
            County State  National Provider Identifier  pop_est  normalized
156  Denton County    TX                            10   887207    1.127133
Denton County
TX
Denton County
            County State  National Provider Identifier  pop_est  normalized
157  Denver County    CO                            21   727211    2.887745
Denver County
CO
Denver County
               County State  National Provider Identifier  pop_est  normalized
158  Deschutes County    OR                             1   197692    0.505837
Deschutes County
OR
Deschutes County
             County State  National Provider Identifier  pop_est  normalized
159  Dickson County    TN                             1    53948    1.853637
Dickson County
TN
Dickson County
                   County State  National Provider Identifier  pop_est  \
160  District of Columbia    DC                            14   705749

     normalized
160    1.983708
District of Columbia
DC
District of Columbia
                County State  National Provider Identifier  pop_est  \
161  Dorchester County    SC                             1   162809

     normalized
161    0.614217
Dorchester County
SC
Dorchester County
             County State  National Provider Identifier  pop_est  normalized
162  Douglas County    CO                             2   351154    0.569551
163  Douglas County    KS                             2   122259    1.635871
164  Douglas County    NE                            16   571327    2.800498
Douglas County
CO
KS
NE
                 County State  National Provider Identifier  pop_est  \
165  DoÌÎå±a Ana County    NM                             2   218195

     normalized
165    0.916611
DoÌÎå±a Ana County
NM
Doña Ana County
            County State  National Provider Identifier  pop_est  normalized
166  DuPage County    IL                            24   922921    2.600439
DuPage County
IL
DuPage County
             County State  National Provider Identifier  pop_est  normalized
167  Dubuque County    IA                             3    97311    3.082899
Dubuque County
IA
Dubuque County
            County State  National Provider Identifier  pop_est  normalized
168  Durham County    NC                             5   321488    1.555268
Durham County
NC
Durham County
              County State  National Provider Identifier  pop_est  normalized
169  Dutchess County    NY                             4   294218    1.359536
Dutchess County
NY
Dutchess County
           County State  National Provider Identifier  pop_est  normalized
170  Duval County    FL                             9   957755    0.939698
Duval County
FL
Duval County
                      County State  National Provider Identifier  pop_est  \
171  East Baton Rouge County    LA                             7   440059

     normalized
171    1.590696
East Baton Rouge County
LA
East Baton Rouge County
                County State  National Provider Identifier  pop_est  \
172  Eau Claire County    WI                             2   104646

     normalized
172    1.911205
Eau Claire County
WI
Eau Claire County
           County State  National Provider Identifier  pop_est  normalized
173  Ector County    TX                             2   166223    1.203203
Ector County
TX
Ector County
          County State  National Provider Identifier  pop_est  normalized
174  Eddy County    NM                             1    58460    1.710571
Eddy County
NM
Eddy County
             County State  National Provider Identifier  pop_est  normalized
175  El Paso County    CO                             9   720403    1.249301
176  El Paso County    TX                             5   839238    0.595779
El Paso County
CO
TX
             County State  National Provider Identifier  pop_est  normalized
177  Elkhart County    IN                             1   206341    0.484635
Elkhart County
IN
Elkhart County
           County State  National Provider Identifier  pop_est  normalized
178  Ellis County    TX                             1   184826    0.541049
Ellis County
TX
Ellis County
           County State  National Provider Identifier  pop_est  normalized
179  Emmet County    MI                             1    33415    2.992668
Emmet County
MI
Emmet County
          County State  National Provider Identifier  pop_est  normalized
180  Erie County    NY                            10   918702    1.088492
181  Erie County    OH                             1    74266    1.346511
182  Erie County    PA                             2   269728    0.741488
Erie County
NY
OH
PA
              County State  National Provider Identifier  pop_est  normalized
183  Escambia County    FL                             4   318316    1.256613
Escambia County
FL
Escambia County
           County State  National Provider Identifier  pop_est  normalized
184  Essex County    MA                             9   789034    1.140635
185  Essex County    NJ                            11   798975    1.376764
Essex County
MA
NJ
                           County State  National Provider Identifier  \
186  Fairbanks North Star Borough    AK                             1

     pop_est  normalized
186    96849    1.032535
Fairbanks North Star Borough
AK
             County State  National Provider Identifier  pop_est  normalized
187  Fairfax County    VA                            18  1147532    1.568584
Fairfax County
VA
Fairfax County
               County State  National Provider Identifier  pop_est  normalized
188  Fairfield County    CT                            19   943332    2.014137
Fairfield County
CT
Fairfield County
                  County State  National Provider Identifier  pop_est  \
189  Falls Church County    VA                             1    14617

     normalized
189    6.841349
Falls Church County
VA
Falls Church County
              County State  National Provider Identifier  pop_est  normalized
190  Fauquier County    VA                             1    71222    1.404061
Fauquier County
VA
Fauquier County
             County State  National Provider Identifier  pop_est  normalized
191  Fayette County    GA                             2   114421    1.747931
192  Fayette County    KY                            14   323152    4.332327
Fayette County
GA
KY
              County State  National Provider Identifier  pop_est  normalized
193  Florence County    SC                             5   138293    3.615512
Florence County
SC
Florence County
           County State  National Provider Identifier  pop_est  normalized
194  Floyd County    GA                             1    98498    1.015249
195  Floyd County    IN                             2    78522    2.547057
Floyd County
GA
IN
             County State  National Provider Identifier  pop_est  normalized
196  Forsyth County    GA                             2   244252    0.818826
197  Forsyth County    NC                             7   382295    1.831047
Forsyth County
GA
NC
               County State  National Provider Identifier  pop_est  normalized
198  Fort Bend County    TX                             5   811688       0.616
Fort Bend County
TX
Fort Bend County
              County State  National Provider Identifier  pop_est  normalized
199  Franklin County    MO                             1   103967    0.961844
200  Franklin County    NY                             1    50022    1.999120
201  Franklin County    OH                            23  1316756    1.746717
202  Franklin County    VT                             1    49402    2.024210
Franklin County
MO
NY
OH
VT
               County State  National Provider Identifier  pop_est  normalized
203  Frederick County    MD                             3   259547     1.15586
Frederick County
MD
Frederick County
                    County State  National Provider Identifier  pop_est  \
204  Fredericksburg County    VA                             7    29036

     normalized
204   24.108004
Fredericksburg County
VA
Fredericksburg County
            County State  National Provider Identifier  pop_est  normalized
205  Fresno County    CA                            18   999101     1.80162
Fresno County
CA
Fresno County
            County State  National Provider Identifier  pop_est  normalized
206  Fulton County    GA                            13  1063937    1.221877
Fulton County
GA
Fulton County
              County State  National Provider Identifier  pop_est  normalized
207  Gallatin County    MT                             1   114434    0.873866
Gallatin County
MT
Gallatin County
            County State  National Provider Identifier  pop_est  normalized
208  Gallia County    OH                             1    29898    3.344705
Gallia County
OH
Gallia County

               County State  National Provider Identifier  pop_est  normalized
209  Galveston County    TX                             7   342139    2.045952
Galveston County
TX
Galveston County
              County State  National Provider Identifier  pop_est  normalized
210  Garfield County    CO                             2    60061    3.329948
211  Garfield County    OK                             1    61056    1.637841
Garfield County
CO
OK
             County State  National Provider Identifier  pop_est  normalized
212  Garland County    AR                             1    99386    1.006178
Garland County
AR
Garland County
             County State  National Provider Identifier  pop_est  normalized
213  Genesee County    MI                             4   405813    0.985676
Genesee County
MI
Genesee County
                County State  National Provider Identifier  pop_est  \
214  Gloucester County    NJ                             5   291636

     normalized
214    1.714466
Gloucester County
NJ
Gloucester County
             County State  National Provider Identifier  pop_est  normalized
215  Goodhue County    MN                             1    46340    2.157963
Goodhue County
MN
Goodhue County
             County State  National Provider Identifier  pop_est  normalized
216  Grafton County    NH                             2    89886    2.225041
Grafton County
NH
Grafton County
                 County State  National Provider Identifier  pop_est  \
217  Grand Forks County    ND                             2    69451

     normalized
217    2.879728
Grand Forks County
ND
Grand Forks County
                    County State  National Provider Identifier  pop_est  \
218  Grand Traverse County    MI                             3    93088

     normalized
218    3.222757
Grand Traverse County
MI
Grand Traverse County
           County State  National Provider Identifier  pop_est  normalized
219  Green County    WI                             1    36960    2.705628
Green County
WI
Green County
            County State  National Provider Identifier  pop_est  normalized
220  Greene County    MO                             5   293086    1.705984
221  Greene County    OH                             2   168937    1.183873
Greene County
MO
OH
                County State  National Provider Identifier  pop_est  \
222  Greenville County    SC                             9   523542

     normalized
222     1.71906
Greenville County
SC
Greenville County
               County State  National Provider Identifier  pop_est  normalized
223  Greenwood County    SC                             1    70811     1.41221
Greenwood County
SC
Greenwood County
           County State  National Provider Identifier  pop_est  normalized
224  Gregg County    TX                             2   123945    1.613619
Gregg County
TX
Gregg County
              County State  National Provider Identifier  pop_est  normalized
225  Guilford County    NC                             7   537174    1.303116
Guilford County
NC
Guilford County
              County State  National Provider Identifier  pop_est  normalized
226  Gwinnett County    GA                             8   936250    0.854473
Gwinnett County
GA
Gwinnett County
          County State  National Provider Identifier  pop_est  normalized
227  Hall County    GA                             6   204441    2.934832
Hall County
GA
Hall County
              County State  National Provider Identifier  pop_est  normalized
228  Hamilton County    IN                             1   338011    0.295848
229  Hamilton County    OH                            17   817473    2.079579
230  Hamilton County    TN                            10   367804    2.718839
Hamilton County
IN
OH
TN
             County State  National Provider Identifier  pop_est  normalized
231  Hampden County    MA                             2   466372    0.428842
Hampden County
MA
Hampden County
               County State  National Provider Identifier  pop_est  normalized
232  Hampshire County    MA                             6   160830    3.730647
Hampshire County
MA
Hampshire County
             County State  National Provider Identifier  pop_est  normalized
233  Hancock County    OH                             1    75783    1.319557
234  Hancock County    WV                             1    28810    3.471017
Hancock County
OH
WV
            County State  National Provider Identifier  pop_est  normalized
235  Hardin County    KY                             3   110958    2.703726
Hardin County
KY
Hardin County
             County State  National Provider Identifier  pop_est  normalized
236  Harford County    MD                             2   255441     0.78296
Harford County
MD
Harford County
            County State  National Provider Identifier  pop_est  normalized
237  Harris County    TX                            43  4713325    0.912307
Harris County
TX
Harris County
              County State  National Provider Identifier  pop_est  normalized
238  Harrison County    KY                             1    18886    5.294927
239  Harrison County    MS                             1   208080    0.480584
Harrison County
KY
MS
                  County State  National Provider Identifier  pop_est  \
240  Harrisonburg County    VA                             1    53016

     normalized
240    1.886223
Harrisonburg County
VA
Harrisonburg County
              County State  National Provider Identifier  pop_est  normalized
241  Hartford County    CT                            11   891720    1.233571
Hartford County
CT
Hartford County
            County State  National Provider Identifier  pop_est  normalized
242  Hawaii County    HI                             1   201513    0.496246
Hawaii County
HI
              County State  National Provider Identifier  pop_est  normalized
243  Hennepin County    MN                            24  1265843     1.89597
Hennepin County
MN
Hennepin County
             County State  National Provider Identifier  pop_est  normalized
244  Henrico County    VA                            10   330818     3.02281
Henrico County
VA
Henrico County
           County State  National Provider Identifier  pop_est  normalized
245  Henry County    GA                             2   234561    0.852657
246  Henry County    IN                             1    47972    2.084549
Henry County
GA
IN
              County State  National Provider Identifier  pop_est  normalized
247  Hernando County    FL                             1   193920    0.515677
Hernando County
FL
Hernando County
             County State  National Provider Identifier  pop_est  normalized
248  Hidalgo County    TX                             1   868707    0.115114
Hidalgo County
TX
Hidalgo County
                  County State  National Provider Identifier  pop_est  \
249  Hillsborough County    FL                            21  1471968
250  Hillsborough County    NH                             6   417025

     normalized
249    1.426661
250    1.438763
Hillsborough County
FL
NH
           County State  National Provider Identifier  pop_est  normalized
251  Hinds County    MS                            12   231840    5.175983
Hinds County
MS
Hinds County
              County State  National Provider Identifier  pop_est  normalized
252  Honolulu County    HI                             8   974563    0.820881
Honolulu County
HI
           County State  National Provider Identifier  pop_est  normalized
253  Horry County    SC                             1   354081    0.282421
Horry County
SC
Horry County
             County State  National Provider Identifier  pop_est  normalized
254  Houston County    AL                             2   105882    1.888895
255  Houston County    GA                             1   157863    0.633461
Houston County
AL
GA
            County State  National Provider Identifier  pop_est  normalized
256  Howard County    IN                             1    82544    1.211475
257  Howard County    MD                             4   325690    1.228162
Howard County
IN
MD
            County State  National Provider Identifier  pop_est  normalized
258  Hudson County    NJ                             3   672391    0.446169
Hudson County
NJ
Hudson County
              County State  National Provider Identifier  pop_est  normalized
259  Humboldt County    CA                             1   135558    0.737692
Humboldt County
CA
Humboldt County
              County State  National Provider Identifier  pop_est  normalized
260  Imperial County    CA                             1   181215    0.551831
Imperial County
CA
Imperial County
                  County State  National Provider Identifier  pop_est  \
261  Indian River County    FL                             2   159923

     normalized
261    1.250602
Indian River County
FL
Indian River County
            County State  National Provider Identifier  pop_est  normalized
262  Ingham County    MI                             9   292406    3.077912
Ingham County
MI
Ingham County
             County State  National Provider Identifier  pop_est  normalized
263  Iredell County    NC                             3   181806    1.650111
Iredell County
NC
Iredell County
             County State  National Provider Identifier  pop_est  normalized
264  Jackson County    IL                             2    56750    3.524229
265  Jackson County    MI                             1   158510    0.630875
266  Jackson County    MO                             7   703011    0.995717
267  Jackson County    MS                             1   143617    0.696296
268  Jackson County    OR                             3   220944    1.357810
Jackson County
IL
MI
MO
MS
OR
            County State  National Provider Identifier  pop_est  normalized
269  Jasper County    SC                             1    30073    3.325242
Jasper County
SC
Jasper County
               County State  National Provider Identifier  pop_est  normalized
270  Jefferson County    AL                            10   658573    1.518435
271  Jefferson County    CO                             4   582881    0.686246
272  Jefferson County    KY                            26   766757    3.390905
273  Jefferson County    MO                             1   225081    0.444285
274  Jefferson County    NY                             2   109834    1.820930
275  Jefferson County    TX                             1   251565    0.397512
276  Jefferson County    LA                            11   432493    2.543394
Jefferson County
AL
CO
KY
MO
NY
TX
LA
             County State  National Provider Identifier  pop_est  normalized
277  Johnson County    IA                             7   151140    4.631468
278  Johnson County    IN                             2   158167    1.264486
279  Johnson County    KS                            14   602401    2.324033
280  Johnson County    MO                             1    54062    1.849728
Johnson County
IA
IN
KS
MO
               County State  National Provider Identifier  pop_est  normalized
281  Kalamazoo County    MI                             1   265066    0.377265
Kalamazoo County
MI
Kalamazoo County
             County State  National Provider Identifier  pop_est  normalized
282  Kanawha County    WV                             5   178124    2.807033
Kanawha County
WV
Kanawha County
               County State  National Provider Identifier  pop_est  normalized
283  Kandiyohi County    MN                             1    43199    2.314868
Kandiyohi County
MN
Kandiyohi County
          County State  National Provider Identifier  pop_est  normalized
284  Kane County    IL                             8   532403    1.502621
Kane County
IL
Kane County
              County State  National Provider Identifier  pop_est  normalized
285  Kankakee County    IL                             1   109862    0.910233
Kankakee County
IL
Kankakee County
                      County State  National Provider Identifier  pop_est  \
286  Kenai Peninsula Borough    AK                             1    58708

     normalized

286    1.703345
Kenai Peninsula Borough
AK
             County State  National Provider Identifier  pop_est  normalized
287  Kendall County    IL                             1   128990    0.775254
288  Kendall County    TX                             1    47431    2.108326
Kendall County
IL
TX
              County State  National Provider Identifier  pop_est  normalized
289  Kennebec County    ME                             1   122302    0.817648
Kennebec County
ME
Kennebec County
             County State  National Provider Identifier  pop_est  normalized
290  Kenosha County    WI                             2   169561    1.179517
Kenosha County
WI
Kenosha County
          County State  National Provider Identifier  pop_est  normalized
291  Kent County    DE                             2   180786    1.106280
292  Kent County    MI                            10   656955    1.522174
293  Kent County    RI                             2   164292    1.217345
Kent County
DE
MI
RI
            County State  National Provider Identifier  pop_est  normalized
294  Kenton County    KY                             2   166998    1.197619
Kenton County
KY
Kenton County
          County State  National Provider Identifier  pop_est  normalized
295  Kern County    CA                             2   900202    0.222172
Kern County
CA
Kern County
          County State  National Provider Identifier  pop_est  normalized
296  Kerr County    TX                             1    52600    1.901141
Kerr County
TX
Kerr County
          County State  National Provider Identifier  pop_est  normalized
297  King County    WA                            29  2252782    1.287297
King County
WA
King County
           County State  National Provider Identifier  pop_est  normalized
298  Kings County    NY                            19  2559903    0.742216
Kings County
NY
Kings County
            County State  National Provider Identifier  pop_est  normalized
299  Kitsap County    WA                             2   271473    0.736722
Kitsap County
WA
Kitsap County
          County State  National Provider Identifier  pop_est  normalized
300  Knox County    TN                            12   470313    2.551492
Knox County
TN
Knox County
              County State  National Provider Identifier  pop_est  normalized
301  Kootenai County    ID                             2   165697    1.207022
Kootenai County
ID
Kootenai County
               County State  National Provider Identifier  pop_est  normalized
302  La Crosse County    WI                             8   118016    6.778742
La Crosse County
WI
La Crosse County
              County State  National Provider Identifier  pop_est  normalized
303  La Plata County    CO                             1    56221    1.778695
La Plata County
CO
La Plata County
             County State  National Provider Identifier  pop_est  normalized
304  LaPorte County    IN                             1   109888    0.910017
LaPorte County
IN
LaPorte County
                County State  National Provider Identifier  pop_est  \
305  Lackawanna County    PA                             3   209674

     normalized
305    1.430793
Lackawanna County
PA
Lackawanna County
               County State  National Provider Identifier  pop_est  normalized
306  Lafayette County    LA                             4   244390    1.636728
Lafayette County
LA
Lafayette County
          County State  National Provider Identifier  pop_est  normalized
307  Lake County    FL                             1   367118    0.272392
308  Lake County    IL                             9   696535    1.292110
309  Lake County    IN                             5   485493    1.029881
310  Lake County    OH                             2   230149    0.869002
Lake County
FL
IL
IN
OH
           County State  National Provider Identifier  pop_est  normalized
311  Lamar County    MS                             5    63343    7.893532
Lamar County
MS
Lamar County
               County State  National Provider Identifier  pop_est  normalized
312  Lancaster County    NE                             4   319090    1.253565
313  Lancaster County    PA                             5   545724    0.916214
Lancaster County
NE
PA
          County State  National Provider Identifier  pop_est  normalized
314  Lane County    OR                             7   382067    1.832139
Lane County
OR
Lane County
             County State  National Provider Identifier  pop_est  normalized
315  Laramie County    WY                             1    99500    1.005025
Laramie County
WY
Laramie County
             County State  National Provider Identifier  pop_est  normalized
316  Larimer County    CO                             7   356899    1.961339
Larimer County
CO
Larimer County
                County State  National Provider Identifier  pop_est  \
317  Lauderdale County    AL                             2    92729
318  Lauderdale County    MS                             1    74125

     normalized
317    2.156823
318    1.349073
Lauderdale County
AL
MS
             County State  National Provider Identifier  pop_est  normalized
319  Laurens County    GA                             1    47546    2.103226
Laurens County
GA
Laurens County
                 County State  National Provider Identifier  pop_est  \
320  Leavenworth County    KS                             1    81758

     normalized
320    1.223122
Leavenworth County
KS
Leavenworth County
         County State  National Provider Identifier  pop_est  normalized
321  Lee County    AL                             1   164542    0.607748
322  Lee County    FL                             4   770577    0.519092
323  Lee County    GA                             3    29992   10.002667
324  Lee County    MS                             2    85436    2.340934
Lee County
AL
FL
GA
MS
            County State  National Provider Identifier  pop_est  normalized
325  Lehigh County    PA                             6   369318    1.624616
Lehigh County
PA
Lehigh County
            County State  National Provider Identifier  pop_est  normalized
326  Lenoir County    NC                             2    55949    3.574684
Lenoir County
NC
Lenoir County
          County State  National Provider Identifier  pop_est  normalized
327  Leon County    FL                             4   293582    1.362481
Leon County
FL
Leon County
                     County State  National Provider Identifier  pop_est  \
328  Lewis and Clark County    MT                             1    69432

     normalized
328    1.440258
Lewis and Clark County
MT
Lewis and Clark County
               County State  National Provider Identifier  pop_est  normalized
329  Lexington County    SC                             3   298750    1.004184
Lexington County
SC
Lexington County
             County State  National Provider Identifier  pop_est  normalized
330  Licking County    OH                             1   176862    0.565413
Licking County
OH
Licking County
             County State  National Provider Identifier  pop_est  normalized
331  Lincoln County    SD                             1    61128    1.635912
Lincoln County
SD
Lincoln County
          County State  National Provider Identifier  pop_est  normalized
332  Linn County    IA                             2   226706      0.8822
Linn County
IA
Linn County
                County State  National Provider Identifier  pop_est  \
333  Litchfield County    CT                             1   180333

     normalized
333     0.55453
Litchfield County
CT
Litchfield County
                County State  National Provider Identifier  pop_est  \
334  Livingston County    MI                             2   191995

     normalized
334    1.041694
Livingston County
MI
Livingston County
            County State  National Provider Identifier  pop_est  normalized
335  Lorain County    OH                             1   309833    0.322755
Lorain County
OH
Lorain County
                County State  National Provider Identifier  pop_est  \
336  Los Alamos County    NM                             1    19369

     normalized
336    5.162889
Los Alamos County
NM
Los Alamos County
                 County State  National Provider Identifier   pop_est  \
337  Los Angeles County    CA                            65  10039107

     normalized
337    0.647468
Los Angeles County
CA
Los Angeles County
             County State  National Provider Identifier  pop_est  normalized
338  Loudoun County    VA                            12   413538    2.901789
Loudoun County
VA
Loudoun County
             County State  National Provider Identifier  pop_est  normalized
339  Lowndes County    GA                             1   117406    0.851745
Lowndes County
GA
Lowndes County
             County State  National Provider Identifier  pop_est  normalized
340  Lubbock County    TX                             6   310569    1.931938
Lubbock County
TX
Lubbock County
           County State  National Provider Identifier  pop_est  normalized
341  Lucas County    OH                             9   428348    2.101095
Lucas County
OH
Lucas County
             County State  National Provider Identifier  pop_est  normalized
342  Luzerne County    PA                             3   317417    0.945129
Luzerne County
PA
Luzerne County
              County State  National Provider Identifier  pop_est  normalized
343  Lycoming County    PA                             1   113299     0.88262
Lycoming County
PA
Lycoming County
               County State  National Provider Identifier  pop_est  normalized
344  Lynchburg County    VA                             1    82168    1.217019
Lynchburg County
VA
Lynchburg County
            County State  National Provider Identifier  pop_est  normalized
345  Macomb County    MI                            12   873972    1.373042
Macomb County
MI
Macomb County
           County State  National Provider Identifier  pop_est  normalized
346  Macon County    IL                             1   104009    0.961455
Macon County
IL
Macon County
             County State  National Provider Identifier  pop_est  normalized
347  Madison County    AL                             4   372909    1.072648
348  Madison County    IL                             1   262966    0.380277
349  Madison County    TN                             1    97984    1.020575
Madison County
AL
IL
TN
              County State  National Provider Identifier  pop_est  normalized
350  Mahoning County    OH                             3   228683     1.31186
Mahoning County
OH
Mahoning County
             County State  National Provider Identifier  pop_est  normalized
351  Manatee County    FL                             2   403253    0.495967
Manatee County
FL
Manatee County
              County State  National Provider Identifier  pop_est  normalized
352  Marathon County    WI                             4   135692    2.947852
Marathon County
WI
Marathon County
              County State  National Provider Identifier  pop_est  normalized
353  Maricopa County    AZ                            42  4485414    0.936368
Maricopa County
AZ
Maricopa County
            County State  National Provider Identifier  pop_est  normalized
354  Marion County    FL                             2   365579    0.547077
355  Marion County    IN                            10   964582    1.036718
356  Marion County    OH                             1    65093    1.536264
357  Marion County    OR                             2   347818    0.575013
Marion County
FL
IN
OH
OR

               County State  National Provider Identifier  pop_est  normalized
358  Marquette County    MI                             1    66699    1.499273
Marquette County
MI
Marquette County
                        County State  National Provider Identifier  pop_est  \
359  Matanuska-Susitna Borough    AK                             1   108317

     normalized
359    0.923216
Matanuska-Susitna Borough
AK
           County State  National Provider Identifier  pop_est  normalized
360  Maury County    TN                             1    96387    1.037484
Maury County
TN
Maury County
               County State  National Provider Identifier  pop_est  normalized
361  McCracken County    KY                             2    65418    3.057263
McCracken County
KY
McCracken County
             County State  National Provider Identifier  pop_est  normalized
362  McHenry County    IL                             5   307774    1.624569
McHenry County
IL
McHenry County
            County State  National Provider Identifier  pop_est  normalized
363  McLean County    IL                             1   171517    0.583033
McLean County
IL
McLean County
              County State  National Provider Identifier  pop_est  normalized
364  McLennan County    TX                             4   256623    1.558707
McLennan County
TX
McLennan County
                 County State  National Provider Identifier  pop_est  \
365  Mecklenburg County    NC                            24  1110356

     normalized
365    2.161469
Mecklenburg County
NC
Mecklenburg County
            County State  National Provider Identifier  pop_est  normalized
366  Medina County    OH                             2   179746    1.112681
367  Medina County    TX                             1    51584    1.938586
Medina County
OH
TX
               County State  National Provider Identifier  pop_est  normalized
368  Mendocino County    CA                             2    86749    2.305502
Mendocino County
CA
Mendocino County
            County State  National Provider Identifier  pop_est  normalized
369  Merced County    CA                             1   277680    0.360127
Merced County
CA
Merced County
            County State  National Provider Identifier  pop_est  normalized
370  Mercer County    NJ                             4   367430    1.088643
371  Mercer County    PA                             1   109424    0.913876
372  Mercer County    WV                             1    58758    1.701896
Mercer County
NJ
PA
WV
          County State  National Provider Identifier  pop_est  normalized
373  Mesa County    CO                             2   154210    1.296933
Mesa County
CO
Mesa County
                County State  National Provider Identifier  pop_est  \
374  Miami-Dade County    FL                            29  2716940

     normalized
374    1.067377
Miami-Dade County
FL
Miami-Dade County
               County State  National Provider Identifier  pop_est  normalized
375  Middlesex County    MA                            16  1611699    0.992741
376  Middlesex County    NJ                            15   825062    1.818045
Middlesex County
MA
NJ
             County State  National Provider Identifier  pop_est  normalized
377  Midland County    MI                             1    83156    1.202559
378  Midland County    TX                             2   176832    1.131017
Midland County
MI
TX
             County State  National Provider Identifier  pop_est  normalized
379  Mifflin County    PA                             1    46138    2.167411
Mifflin County
PA
Mifflin County
               County State  National Provider Identifier  pop_est  normalized
380  Milwaukee County    WI                            16   945726    1.691822
Milwaukee County
WI
Milwaukee County
               County State  National Provider Identifier  pop_est  normalized
381  Minnehaha County    SD                             1   193134    0.517775
Minnehaha County
SD
Minnehaha County
              County State  National Provider Identifier  pop_est  normalized
382  Missoula County    MT                             2   119600    1.672241
Missoula County
MT
Missoula County
            County State  National Provider Identifier  pop_est  normalized
383  Mobile County    AL                             5   413210    1.210038
Mobile County
AL
Mobile County
            County State  National Provider Identifier  pop_est  normalized
384  Mohave County    AZ                             1   212181    0.471296
Mohave County
AZ
Mohave County
              County State  National Provider Identifier  pop_est  normalized
385  Monmouth County    NJ                             9   618795     1.45444
Monmouth County
NJ
Monmouth County
                County State  National Provider Identifier  pop_est  \
386  Monongalia County    WV                             1   105612

     normalized
386    0.946862
Monongalia County
WV
Monongalia County
            County State  National Provider Identifier  pop_est  normalized
387  Monroe County    IN                             3   148431    2.021141
388  Monroe County    MI                             1   150500    0.664452
389  Monroe County    NY                            18   741770    2.426628
390  Monroe County    PA                             1   170271    0.587299
Monroe County
IN
MI
NY
PA
              County State  National Provider Identifier  pop_est  normalized
391  Monterey County    CA                             3   434061    0.691147
Monterey County
CA
Monterey County
                County State  National Provider Identifier  pop_est  \
392  Montgomery County    AL                             4   226486
393  Montgomery County    MD                            19  1050688
394  Montgomery County    OH                             1   531687
395  Montgomery County    PA                            32   830915
396  Montgomery County    TN                             1   208993
397  Montgomery County    TX                             6   607391
398  Montgomery County    VA                             1    98535

     normalized
392    1.766114
393    1.808339
394    0.188081
395    3.851176
396    0.478485
397    0.987832
398    1.014868
Montgomery County
AL
MD
OH
PA
TN
TX
VA
             County State  National Provider Identifier  pop_est  normalized
399  Montour County    PA                             1    18230    5.485464
Montour County
PA
Montour County
           County State  National Provider Identifier  pop_est  normalized
400  Moore County    NC                             2   100880    1.982554
Moore County
NC
Moore County
            County State  National Provider Identifier  pop_est  normalized
401  Morgan County    AL                             2   119679    1.671137
Morgan County
AL
Morgan County
            County State  National Provider Identifier  pop_est  normalized
402  Morris County    NJ                            11   491845    2.236477
Morris County
NJ
Morris County
               County State  National Provider Identifier  pop_est  normalized
403  Multnomah County    OR                             6   812855    0.738139
Multnomah County
OR
Multnomah County
              County State  National Provider Identifier  pop_est  normalized
404  Muscogee County    GA                             2   195769    1.021612
Muscogee County
GA
Muscogee County
              County State  National Provider Identifier  pop_est  normalized
405  Muskegon County    MI                             1   173566     0.57615
Muskegon County
MI
Muskegon County
              County State  National Provider Identifier  pop_est  normalized
406  Muskogee County    OK                             1    67997    1.470653
Muskogee County
OK
Muskogee County
                 County State  National Provider Identifier  pop_est  \
407  Nacogdoches County    TX                             1    65204

     normalized
407    1.533648
Nacogdoches County
TX
Nacogdoches County
          County State  National Provider Identifier  pop_est  normalized
408  Napa County    CA                             3   137744    2.177953
Napa County
CA
Napa County
          County State  National Provider Identifier  pop_est  normalized
409  Nash County    NC                             2    94298    2.120936
Nash County
NC
Nash County
            County State  National Provider Identifier  pop_est  normalized
410  Nassau County    NY                            37  1356924    2.726756
Nassau County
NY
Nassau County
            County State  National Provider Identifier  pop_est  normalized
411  Nevada County    CA                             1    99755    1.002456
Nevada County
CA
Nevada County
                County State  National Provider Identifier  pop_est  \
412  New Castle County    DE                             8   558753

     normalized
412     1.43176
New Castle County
DE
New Castle County
                 County State  National Provider Identifier  pop_est  \
413  New Hanover County    NC                             3   234473

     normalized
413    1.279465
New Hanover County
NC
New Hanover County
               County State  National Provider Identifier  pop_est  normalized
414  New Haven County    CT                            14   854757    1.637892
New Haven County
CT
New Haven County
                County State  National Provider Identifier  pop_est  \
415  New London County    CT                             4   265206

     normalized
415    1.508262
New London County
CT
New London County
              County State  National Provider Identifier  pop_est  normalized
416  New York County    NY                            54  1628706    3.315516
New York County
NY
New York County
                  County State  National Provider Identifier  pop_est  \
417  Newport News County    VA                             1   179225

     normalized
417    0.557958
Newport News County
VA
Newport News County
             County State  National Provider Identifier  pop_est  normalized
418  Niagara County    NY                             2   209281    0.955653
Niagara County
NY
Niagara County
             County State  National Provider Identifier  pop_est  normalized
419  Norfolk County    MA                            21   706775    2.971243
Norfolk County
MA
Norfolk County
                 County State  National Provider Identifier  pop_est  \
420  Northampton County    PA                             5   305285

     normalized
420    1.637814
Northampton County
PA
Northampton County
            County State  National Provider Identifier  pop_est  normalized
421  Nueces County    TX                             4   362294    1.104076
Nueces County
TX
Nueces County
             County State  National Provider Identifier  pop_est  normalized
422  Oakland County    MI                            27  1257584    2.146974
Oakland County
MI
Oakland County
           County State  National Provider Identifier  pop_est  normalized
423  Ocean County    NJ                             7   607186    1.152859
Ocean County
NJ
Ocean County
          County State  National Provider Identifier  pop_est  normalized
424  Ohio County    WV                             1    41411    2.414817
Ohio County
WV
Ohio County
              County State  National Provider Identifier  pop_est  normalized
425  Okaloosa County    FL                             4   210738    1.898091
Okaloosa County
FL
Okaloosa County
              County State  National Provider Identifier  pop_est  normalized
426  Oklahoma County    OK                            10   797434    1.254022
Oklahoma County
OK
Oklahoma County
             County State  National Provider Identifier  pop_est  normalized
427  Olmsted County    MN                            13   158293    8.212618
Olmsted County
MN
Olmsted County
            County State  National Provider Identifier  pop_est  normalized
428  Oneida County    NY                             1   228671    0.437309
Oneida County
NY
Oneida County
              County State  National Provider Identifier  pop_est  normalized
429  Onondaga County    NY                             4   460528    0.868568
Onondaga County
NY
Onondaga County
            County State  National Provider Identifier  pop_est  normalized
430  Onslow County    NC                             3   197938    1.515626
Onslow County
NC
Onslow County
             County State  National Provider Identifier  pop_est  normalized
431  Ontario County    NY                             1   109777    0.910938
Ontario County
NY
Ontario County
            County State  National Provider Identifier  pop_est  normalized
432  Orange County    CA                            32  3175692    1.007654
433  Orange County    FL                             8  1393452    0.574114
434  Orange County    NC                             1   148476    0.673510
435  Orange County    NY                             6   384940    1.558684
Orange County
CA
FL
NC
NY
             County State  National Provider Identifier  pop_est  normalized
436  Orleans County    LA                             5   390144    1.281578
Orleans County
LA
Orleans County

             County State  National Provider Identifier  pop_est  normalized
437  Osceola County    FL                             2   375751    0.532267
Osceola County
FL
Osceola County
            County State  National Provider Identifier  pop_est  normalized
438  Otsego County    NY                             1    59493     1.68087
Otsego County
NY
Otsego County
            County State  National Provider Identifier  pop_est  normalized
439  Ottawa County    MI                             2   291830    0.685331
Ottawa County
MI
Ottawa County
              County State  National Provider Identifier  pop_est  normalized
440  Ouachita County    LA                             2   153279     1.30481
Ouachita County
LA
Ouachita County
               County State  National Provider Identifier  pop_est  normalized
441  Outagamie County    WI                             3   187885    1.596721
Outagamie County
WI
Outagamie County
             County State  National Provider Identifier  pop_est  normalized
442  Ozaukee County    WI                             1    89221    1.120812
Ozaukee County
WI
Ozaukee County
                County State  National Provider Identifier  pop_est  \
443  Palm Beach County    FL                            18  1496770

     normalized
443     1.20259
Palm Beach County
FL
Palm Beach County
           County State  National Provider Identifier  pop_est  normalized
444  Pasco County    FL                             5   553947    0.902613
Pasco County
FL
Pasco County
                County State  National Provider Identifier  pop_est  \
445  Pasquotank County    NC                             2    39824

     normalized
445    5.022097
Pasquotank County
NC
Pasquotank County
             County State  National Provider Identifier  pop_est  normalized
446  Passaic County    NJ                             4   501826    0.797089
Passaic County
NJ
Passaic County
                County State  National Provider Identifier  pop_est  \
447  Pennington County    SD                             2   113775

     normalized
447    1.757855
Pennington County
SD
Pennington County
               County State  National Provider Identifier  pop_est  normalized
448  Penobscot County    ME                             2   152148     1.31451
Penobscot County
ME
Penobscot County
            County State  National Provider Identifier  pop_est  normalized
449  Peoria County    IL                             3   179179    1.674303
Peoria County
IL
Peoria County
            County State  National Provider Identifier  pop_est  normalized
450  Phelps County    MO                             1    44573    2.243511
Phelps County
MO
Phelps County
                  County State  National Provider Identifier  pop_est  \
451  Philadelphia County    PA                            18  1584064

     normalized
451    1.136318
Philadelphia County
PA
Philadelphia County
            County State  National Provider Identifier  pop_est  normalized
452  Pierce County    WA                             8   904980    0.883997
Pierce County
WA
Pierce County
          County State  National Provider Identifier  pop_est  normalized
453  Pike County    KY                             2    57876    3.455664
Pike County
KY
Pike County
          County State  National Provider Identifier  pop_est  normalized
454  Pima County    AZ                            11  1047279    1.050341
Pima County
AZ
Pima County
              County State  National Provider Identifier  pop_est  normalized
455  Pinellas County    FL                            17   974996    1.743597
Pinellas County
FL
Pinellas County
          County State  National Provider Identifier  pop_est  normalized
456  Pitt County    NC                             2   180742     1.10655
Pitt County
NC
Pitt County
            County State  National Provider Identifier  pop_est  normalized
457  Placer County    CA                             5   398329    1.255244
Placer County
CA
Placer County
              County State  National Provider Identifier  pop_est  normalized
458  Plymouth County    MA                             2   521202    0.383728
Plymouth County
MA
Plymouth County
          County State  National Provider Identifier  pop_est  normalized
459  Polk County    FL                             3   724777    0.413920
460  Polk County    IA                             3   490161    0.612044
Polk County
FL
IA
            County State  National Provider Identifier  pop_est  normalized
461  Porter County    IN                             2   170389    1.173785
Porter County
IN
Porter County
                  County State  National Provider Identifier  pop_est  \
462  Pottawatomie County    OK                             1    72592

     normalized
462    1.377562
Pottawatomie County
OK
Pottawatomie County
            County State  National Provider Identifier  pop_est  normalized
463  Potter County    TX                             2   117415     1.70336
Potter County
TX
Potter County
                     County State  National Provider Identifier  pop_est  \
464  Prince George's County    MD                             8   909327

     normalized
464    0.879772
Prince George's County
MD
Prince George's County
                    County State  National Provider Identifier  pop_est  \
465  Prince William County    VA                             3   470335

     normalized
465    0.637843
Prince William County
VA
Prince William County
                County State  National Provider Identifier  pop_est  \
466  Providence County    RI                             6   638931

     normalized
466    0.939069
Providence County
RI
Providence County
            County State  National Provider Identifier  pop_est  normalized
467  Pueblo County    CO                             2   168424    1.187479
Pueblo County
CO
Pueblo County
             County State  National Provider Identifier  pop_est  normalized
468  Pulaski County    AR                            15   391911    3.827400
469  Pulaski County    KY                             1    64979    1.538959
Pulaski County
AR
KY
            County State  National Provider Identifier  pop_est  normalized
470  Putnam County    NY                             1    98320    1.017087
471  Putnam County    TN                             2    80245    2.492367
Putnam County
NY
TN
            County State  National Provider Identifier  pop_est  normalized
472  Queens County    NY                            18  2253858    0.798631
Queens County
NY
Queens County
            County State  National Provider Identifier  pop_est  normalized
473  Racine County    WI                             3   196311    1.528187
Racine County
WI
Racine County
            County State  National Provider Identifier  pop_est  normalized
474  Ramsey County    MN                            11   550321    1.998833
Ramsey County
MN
Ramsey County
              County State  National Provider Identifier  pop_est  normalized
475  Randolph County    NC                             1   143667    0.696054
Randolph County
NC
Randolph County
             County State  National Provider Identifier  pop_est  normalized
476  Rapides County    LA                             2   129648    1.542639
Rapides County
LA
Rapides County
          County State  National Provider Identifier  pop_est  normalized
477  Reno County    KS                             2    61998    3.225911
Reno County
KS
Reno County
              County State  National Provider Identifier  pop_est  normalized
478  Richland County    SC                             6   415759    1.443144
Richland County
SC
Richland County
              County State  National Provider Identifier  pop_est  normalized
479  Richmond County    GA                             6   202518    2.962700
480  Richmond County    NY                             6   476143    1.260126
481  Richmond County    VA                             2   230436    0.867920
Richmond County
GA
NY
VA
               County State  National Provider Identifier  pop_est  normalized
482  Riverside County    CA                             9  2470546    0.364292
Riverside County
CA
Riverside County
             County State  National Provider Identifier  pop_est  normalized
483  Roanoke County    VA                             3    99143    3.025932
Roanoke County
VA
Roanoke County
          County State  National Provider Identifier  pop_est  normalized
484  Rock County    WI                             1   163354    0.612167
Rock County
WI
Rock County
                 County State  National Provider Identifier  pop_est  \
485  Rock Island County    IL                             1   141879

     normalized
485    0.704826
Rock Island County
IL
Rock Island County
              County State  National Provider Identifier  pop_est  normalized
486  Rockdale County    GA                             2    90896    2.200317
Rockdale County
GA
Rockdale County
                County State  National Provider Identifier  pop_est  \
487  Rockingham County    NH                             5   309769

     normalized
487    1.614106
Rockingham County
NH
Rockingham County
              County State  National Provider Identifier  pop_est  normalized
488  Rockland County    NY                             5   325789    1.534736
Rockland County
NY
Rockland County
          County State  National Provider Identifier  pop_est  normalized
489  Ross County    OH                             1    76666    1.304359
Ross County
OH
Ross County
                County State  National Provider Identifier  pop_est  \
490  Rutherford County    TN                             3   332285

     normalized
490    0.902839
Rutherford County
TN
Rutherford County
                County State  National Provider Identifier  pop_est  \
491  Sacramento County    CA                             9  1552058

     normalized
491    0.579875
Sacramento County
CA
Sacramento County
             County State  National Provider Identifier  pop_est  normalized
492  Saginaw County    MI                             2   190539    1.049654
Saginaw County
MI
Saginaw County
           County State  National Provider Identifier  pop_est  normalized
493  Salem County    VA                             2    25301    7.904826
Salem County
VA
Salem County
            County State  National Provider Identifier  pop_est  normalized
494  Saline County    KS                             1    54224    1.844202
Saline County
KS
Saline County
               County State  National Provider Identifier  pop_est  normalized
495  Salt Lake County    UT                            15  1160437    1.292616
Salt Lake County
UT
Salt Lake County
                    County State  National Provider Identifier  pop_est  \
496  San Bernardino County    CA                             6  2180085

     normalized
496    0.275219
San Bernardino County
CA
San Bernardino County
               County State  National Provider Identifier  pop_est  normalized
497  San Diego County    CA                            27  3338330    0.808788
San Diego County
CA
San Diego County
                   County State  National Provider Identifier  pop_est  \
498  San Francisco County    CA                             9   881549

     normalized
498     1.02093
San Francisco County
CA
San Francisco County
                 County State  National Provider Identifier  pop_est  \
499  San Joaquin County    CA                             5   762148

     normalized
499    0.656041
San Joaquin County
CA
San Joaquin County
                     County State  National Provider Identifier  pop_est  \
500  San Luis Obispo County    CA                             4   283111

     normalized
500    1.412873
San Luis Obispo County
CA
San Luis Obispo County
               County State  National Provider Identifier  pop_est  normalized
501  San Mateo County    CA                            11   766573    1.434958
San Mateo County
CA
San Mateo County
              County State  National Provider Identifier  pop_est  normalized
502  Sangamon County    IL                             4   194672    2.054738
Sangamon County
IL
Sangamon County
                   County State  National Provider Identifier  pop_est  \
503  Santa Barbara County    CA                             4   446499

     normalized
503    0.895859
Santa Barbara County
CA
Santa Barbara County
                 County State  National Provider Identifier  pop_est  \
504  Santa Clara County    CA                            30  1927852

     normalized
504    1.556136
Santa Clara County
CA
Santa Clara County
                County State  National Provider Identifier  pop_est  \
505  Santa Cruz County    CA                             2   273213

     normalized
505     0.73203
Santa Cruz County
CA
Santa Cruz County
              County State  National Provider Identifier  pop_est  normalized
506  Santa Fe County    NM                             1   150358    0.665079
Santa Fe County
NM
Santa Fe County
              County State  National Provider Identifier  pop_est  normalized
507  Sarasota County    FL                             8   433742    1.844414
Sarasota County
FL
Sarasota County
              County State  National Provider Identifier  pop_est  normalized
508  Saratoga County    NY                             1   229863    0.435042
Saratoga County
NY
Saratoga County
           County State  National Provider Identifier  pop_est  normalized
509  Sarpy County    NE                             2   187196    1.068399
Sarpy County
NE
Sarpy County
                 County State  National Provider Identifier  pop_est  \
510  Schenectady County    NY                             1   155299

     normalized
510    0.643919
Schenectady County
NY
Schenectady County
                County State  National Provider Identifier  pop_est  \
511  Schuylkill County    PA                             1   141359

     normalized
511    0.707419
Schuylkill County
PA
Schuylkill County
           County State  National Provider Identifier  pop_est  normalized
512  Scott County    IA                             1   172943    0.578225
Scott County
IA
Scott County
               County State  National Provider Identifier  pop_est  normalized
513  Sebastian County    AR                             1   127827    0.782307
Sebastian County
AR
Sebastian County
              County State  National Provider Identifier  pop_est  normalized
514  Sedgwick County    KS                             3   516042    0.581348
Sedgwick County
KS
Sedgwick County
              County State  National Provider Identifier  pop_est  normalized
515  Seminole County    FL                             9   471826    1.907483
Seminole County
FL
Seminole County
            County State  National Provider Identifier  pop_est  normalized
516  Sevier County    TN                             1    98250    1.017812
Sevier County
TN
Sevier County
             County State  National Provider Identifier  pop_est  normalized
517  Shawnee County    KS                             3   176875    1.696113
Shawnee County
KS
Shawnee County
               County State  National Provider Identifier  pop_est  normalized
518  Sheboygan County    WI                             1   115340    0.867002
Sheboygan County
WI
Sheboygan County
            County State  National Provider Identifier  pop_est  normalized
519  Shelby County    TN                            10   937166    1.067047
Shelby County
TN
Shelby County
               County State  National Provider Identifier  pop_est  normalized
520  Sherburne County    MN                             1    97238    1.028405
Sherburne County
MN
Sherburne County
            County State  National Provider Identifier  pop_est  normalized
521  Skagit County    WA                             1   129205    0.773964
Skagit County
WA
Skagit County
           County State  National Provider Identifier  pop_est  normalized
522  Smith County    TX                             5   232751    2.148218
Smith County

TX
Smith County
               County State  National Provider Identifier  pop_est  normalized
523  Snohomish County    WA                             6   822083    0.729853
Snohomish County
WA
Snohomish County
            County State  National Provider Identifier  pop_est  normalized
524  Solano County    CA                             2   447643    0.446785
Solano County
CA
Solano County
              County State  National Provider Identifier  pop_est  normalized
525  Somerset County    NJ                            13   328934    3.952161
Somerset County
NJ
Somerset County
            County State  National Provider Identifier  pop_est  normalized
526  Sonoma County    CA                             1   494336    0.202292
Sonoma County
CA
Sonoma County
                 County State  National Provider Identifier  pop_est  \
527  Spartanburg County    SC                             3   319785

     normalized
527     0.93813
Spartanburg County
SC
Spartanburg County
             County State  National Provider Identifier  pop_est  normalized
528  Spokane County    WA                             6   522798    1.147671
Spokane County
WA
Spokane County
                 County State  National Provider Identifier  pop_est  \
529  St. Charles County    MO                             3   402022

     normalized
529    0.746228
St. Charles County
MO
St. Charles County
               County State  National Provider Identifier  pop_est  normalized
530  St. Clair County    IL                             3   259686    1.155241
531  St. Clair County    MI                             2   159128    1.256850
St. Clair County
IL
MI
                County State  National Provider Identifier  pop_est  \
532  St. Joseph County    IN                             3   271826

     normalized
532    1.103647
St. Joseph County
IN
St. Joseph County
                County State  National Provider Identifier  pop_est  \
533  St. Landry County    LA                             2    82124

     normalized
533    2.435342
St. Landry County
LA
St. Landry County
                  County State  National Provider Identifier  pop_est  \
534  St. Lawrence County    NY                             1   107740

     normalized
534     0.92816
St. Lawrence County
NY
St. Lawrence County
               County State  National Provider Identifier  pop_est  normalized
535  St. Louis County    MN                             2   199070    1.004672
536  St. Louis County    MO                            28   994205    2.816321
537  St. Louis County    MO                            11   300576    3.659640
St. Louis County
MN
MO
MO
               County State  National Provider Identifier  pop_est  normalized
538  St. Lucie County    FL                             2   328297    0.609204
St. Lucie County
FL
St. Lucie County
                County State  National Provider Identifier  pop_est  \
539  St. Mary's County    MD                             1   113510

     normalized
539     0.88098
St. Mary's County
MD
St. Mary's County
                 County State  National Provider Identifier  pop_est  \
540  St. Tammany County    LA                             4   260419

     normalized
540    1.535986
St. Tammany County
LA
St. Tammany County
                County State  National Provider Identifier  pop_est  \
541  Stanislaus County    CA                             2   550660

     normalized
541    0.363201
Stanislaus County
CA
Stanislaus County
           County State  National Provider Identifier  pop_est  normalized
542  Stark County    OH                             1   370606    0.269828
Stark County
OH
Stark County
             County State  National Provider Identifier  pop_est  normalized
543  Stearns County    MN                             2   161075    1.241658
Stearns County
MN
Stearns County
                County State  National Provider Identifier  pop_est  \
544  Stephenson County    IL                             1    44498

     normalized
544    2.247292
Stephenson County
IL
Stephenson County
             County State  National Provider Identifier  pop_est  normalized
545  Steuben County    NY                             2    95379    2.096898
Steuben County
NY
Steuben County
             County State  National Provider Identifier  pop_est  normalized
546  Stevens County    MN                             1     9805   10.198878
Stevens County
MN
Stevens County
           County State  National Provider Identifier  pop_est  normalized
547  Story County    IA                             3    97117    3.089058
Story County
IA
Story County
               County State  National Provider Identifier  pop_est  normalized
548  Strafford County    NH                             1   130633    0.765503
Strafford County
NH
Strafford County
             County State  National Provider Identifier  pop_est  normalized
549  Suffolk County    MA                            25   803907    3.109812
550  Suffolk County    NY                            27  1476601    1.828524
551  Suffolk County    VA                             1    92108    1.085682
Suffolk County
MA
NY
VA
              County State  National Provider Identifier  pop_est  normalized
552  Sullivan County    TN                             4   158348    2.526082
Sullivan County
TN
Sullivan County
            County State  National Provider Identifier  pop_est  normalized
553  Summit County    OH                             5   541013    0.924192
Summit County
OH
Summit County
            County State  National Provider Identifier  pop_est  normalized
554  Sumner County    TN                             1   191283    0.522786
Sumner County
TN
Sumner County
            County State  National Provider Identifier  pop_est  normalized
555  Sumter County    SC                             1   106721    0.937023
Sumter County
SC
Sumter County
            County State  National Provider Identifier  pop_est  normalized
556  Sussex County    DE                             1   234225     0.42694
Sussex County
DE
Sussex County
             County State  National Provider Identifier  pop_est  normalized
557  Tarrant County    TX                            14  2102515    0.665869
Tarrant County
TX
Tarrant County
            County State  National Provider Identifier  pop_est  normalized
558  Taylor County    TX                             2   138034    1.448918
Taylor County
TX
Taylor County
              County State  National Provider Identifier  pop_est  normalized
559  Tazewell County    VA                             2    40595    4.926715
Tazewell County
VA
Tazewell County
                County State  National Provider Identifier  pop_est  \
560  Terrebonne County    LA                             1   110461

     normalized
560    0.905297
Terrebonne County
LA
Terrebonne County
              County State  National Provider Identifier  pop_est  normalized
561  Thurston County    WA                             1   290536    0.344191
Thurston County
WA
Thurston County
                County State  National Provider Identifier  pop_est  \
562  Tippecanoe County    IN                             3   195732

     normalized
562    1.532708
Tippecanoe County
IN
Tippecanoe County
              County State  National Provider Identifier  pop_est  normalized
563  Tompkins County    NY                             5   102180    4.893326
Tompkins County
NY
Tompkins County
           County State  National Provider Identifier  pop_est  normalized
564  Towns County    GA                             1    12037    8.307718
Towns County
GA
Towns County
            County State  National Provider Identifier  pop_est  normalized
565  Travis County    TX                            26  1273954     2.04089
Travis County
TX
Travis County
              County State  National Provider Identifier  pop_est  normalized
566  Trumbull County    OH                             1   197974    0.505117
Trumbull County
OH
Trumbull County
            County State  National Provider Identifier  pop_est  normalized
567  Tulare County    CA                             2   466195    0.429005
Tulare County
CA
Tulare County
           County State  National Provider Identifier  pop_est  normalized
568  Tulsa County    OK                             8   651552    1.227838
Tulsa County
OK
Tulsa County
                County State  National Provider Identifier  pop_est  \
569  Tuscaloosa County    AL                             2   209355

     normalized
569    0.955315
Tuscaloosa County
AL
Tuscaloosa County
             County State  National Provider Identifier  pop_est  normalized
570  Tuscola County    MI                             1    52245    1.914059
Tuscola County
MI
Tuscola County
                County State  National Provider Identifier  pop_est  \
571  Twin Falls County    ID                             2    86878

     normalized
571    2.302079
Twin Falls County
ID
Twin Falls County

           County State  National Provider Identifier  pop_est  normalized
572  Union County    NJ                             7   556341    1.258221
573  Union County    PA                             1    44923    2.226031
Union County
NJ
PA
          County State  National Provider Identifier  pop_est  normalized
574  Utah County    UT                             3   636235    0.471524
Utah County
UT
Utah County
                 County State  National Provider Identifier  pop_est  \
575  Vanderburgh County    IN                             5   181451

     normalized
575    2.755565
Vanderburgh County
IN
Vanderburgh County
             County State  National Provider Identifier  pop_est  normalized
576  Ventura County    CA                             8   846006     0.94562
Ventura County
CA
Ventura County
              County State  National Provider Identifier  pop_est  normalized
577  Victoria County    TX                             2    92084     2.17193
Victoria County
TX
Victoria County
          County State  National Provider Identifier  pop_est  normalized
578  Vigo County    IN                             2   107038    1.868495
Vigo County
IN
Vigo County
                    County State  National Provider Identifier  pop_est  \
579  Virginia Beach County    VA                             4   449974

     normalized
579     0.88894
Virginia Beach County
VA
Virginia Beach County
             County State  National Provider Identifier  pop_est  normalized
580  Volusia County    FL                             6   553284    1.084434
Volusia County
FL
Volusia County
          County State  National Provider Identifier  pop_est  normalized
581  Wake County    NC                             8  1111761    0.719579
Wake County
NC
Wake County
            County State  National Provider Identifier  pop_est  normalized
582  Walker County    TX                             1    72971    1.370407
Walker County
TX
Walker County
                 County State  National Provider Identifier  pop_est  \
583  Walla Walla County    WA                             2    60760

     normalized
583    3.291639
Walla Walla County
WA
Walla Walla County
          County State  National Provider Identifier  pop_est  normalized
584  Ward County    ND                             2    67641    2.956787
Ward County
ND
Ward County
            County State  National Provider Identifier  pop_est  normalized
585  Warren County    KY                             6   132896    4.514809
586  Warren County    MS                             1    45381    2.203565
587  Warren County    NY                             1    63944    1.563868
588  Warren County    OH                             1   234602    0.426254
Warren County
KY
MS
NY
OH
                County State  National Provider Identifier  pop_est  \
589  Washington County    AR                             1   239187
590  Washington County    MD                             2   151049
591  Washington County    MN                             2   262440
592  Washington County    OH                             1    59911
593  Washington County    OR                             4   601592
594  Washington County    PA                             2   206865
595  Washington County    TN                             2   129375
596  Washington County    TX                             1    35882
597  Washington County    UT                             1   177556
598  Washington County    WI                             1   136034

     normalized
589    0.418083
590    1.324074
591    0.762079
592    1.669143
593    0.664902
594    0.966814
595    1.545894
596    2.786913
597    0.563203
598    0.735110
Washington County
AR
MD
MN
OH
OR
PA
TN
TX
UT
WI
            County State  National Provider Identifier  pop_est  normalized
599  Washoe County    NV                             5   471519    1.060403
Washoe County
NV
Washoe County
               County State  National Provider Identifier  pop_est  normalized
600  Washtenaw County    MI                            14   367601    3.808477
Washtenaw County
MI
Washtenaw County
              County State  National Provider Identifier  pop_est  normalized
601  Waukesha County    WI                             2   404198    0.494807
Waukesha County
WI
Waukesha County
           County State  National Provider Identifier  pop_est  normalized
602  Wayne County    IN                             1    65884    1.517819
603  Wayne County    MI                            21  1749343    1.200451
Wayne County
IN
MI
          County State  National Provider Identifier  pop_est  normalized
604  Webb County    TX                             2   276652     0.72293
Webb County
TX
Webb County
           County State  National Provider Identifier  pop_est  normalized
605  Weber County    UT                             3   260213    1.152902
Weber County
UT
Weber County
             County State  National Provider Identifier  pop_est  normalized
606  Webster County    IA                             1    35904    2.785205
Webster County
IA
Webster County
          County State  National Provider Identifier  pop_est  normalized
607  Weld County    CO                             1   324492    0.308174
Weld County
CO
Weld County
                 County State  National Provider Identifier  pop_est  \
608  Westchester County    NY                            25   967506

     normalized
608    2.583963
Westchester County
NY
Westchester County
                  County State  National Provider Identifier  pop_est  \
609  Westmoreland County    PA                             1   348899

     normalized
609    0.286616
Westmoreland County
PA
Westmoreland County
             County State  National Provider Identifier  pop_est  normalized
610  Whatcom County    WA                             3   229247    1.308632
Whatcom County
WA
Whatcom County
              County State  National Provider Identifier  pop_est  normalized
611  Wicomico County    MD                             1   103609    0.965167
Wicomico County
MD
Wicomico County
          County State  National Provider Identifier  pop_est  normalized
612  Will County    IL                             5   690743    0.723858
Will County
IL
Will County
                  County State  National Provider Identifier  pop_est  \
613  Williamsburg County    VA                             3    14954

     normalized
613   20.061522
Williamsburg County
VA
Williamsburg County
                County State  National Provider Identifier  pop_est  \
614  Williamson County    TN                             8   238412
615  Williamson County    TX                             7   590551

     normalized
614    3.355536
615    1.185334
Williamson County
TN
TX
                County State  National Provider Identifier  pop_est  \
616  Winchester County    VA                             2    28078

     normalized
616    7.123014
Winchester County
VA
Winchester County
               County State  National Provider Identifier  pop_est  normalized
617  Winnebago County    IL                             2   282572    0.707784
618  Winnebago County    WI                             2   171907    1.163420
Winnebago County
IL
WI
               County State  National Provider Identifier  pop_est  normalized
619  Worcester County    MA                            12   830622      1.4447
Worcester County
MA
Worcester County
               County State  National Provider Identifier  pop_est  normalized
620  Wyandotte County    KS                             4   165429    2.417956
Wyandotte County
KS
Wyandotte County
            County State  National Provider Identifier  pop_est  normalized
621  Yakima County    WA                             1   250873    0.398608
Yakima County
WA
Yakima County
             County State  National Provider Identifier  pop_est  normalized
622  Yavapai County    AZ                             1   235099    0.425353
Yavapai County
AZ
Yavapai County
                 County State  National Provider Identifier  pop_est  \
623  Yellowstone County    MT                             3   161300

     normalized
623    1.859888
Yellowstone County
MT
Yellowstone County
          County State  National Provider Identifier  pop_est  normalized
624  Yolo County    CA                             2   220500    0.907029
Yolo County
CA
Yolo County
          County State  National Provider Identifier  pop_est  normalized
625  York County    ME                             1   207641    0.481600
626  York County    PA                             3   449058    0.668065
York County
ME
PA
          County State  National Provider Identifier  pop_est  normalized
627  Yuma County    AZ                             1   213787    0.467755
Yuma County
AZ
Yuma County

In [96]:
len(lats)

628

In [98]:
len(fips)

628

In [101]:
grouped_df['lat'] = lats
grouped_df['long'] = longs
grouped_df['fips'] = fips
grouped_df

,County,State,National Provider Identifier,pop_est,normalized,lat,long,fips
0,Ada County,ID,5,481587,1.038234,43.611186,-116.304426,16001
1,Adair County,MO,1,25343,3.945863,40.195661,-92.582451,29001
2,Adams County,CO,9,517421,1.739396,39.874297,-104.927470,8001
3,Adams County,IL,2,65435,3.056468,39.943825,-91.328922,17001
4,Aiken County,SC,1,170872,0.585233,33.535417,-81.769470,45003
5,Alachua County,FL,5,269043,1.858439,29.665903,-82.386859,12001
6,Alameda County,CA,9,1671329,0.538494,37.705201,-122.100537,6001
7,Alamosa County,CO,1,16233,6.160291,37.483070,-105.877216,8003
8,Albany County,NY,10,305506,3.273258,42.678977,-73.813008,36001
9,Albemarle County,VA,11,109330,10.061282,38.050160,-78.516745,51003
10,Alexandria County,VA,3,159428,1.881727,38.820054,-77.092560,51510
11,Allegan County,MI,1,118081,0.846876,42.603138,-85.874378,26005
12,Allegany County,MD,1,70416,1.420132,39.629196,-78.822222,24001
13,Allegheny County,PA,17,1216045,1.397975,40.446250,-79.966543,42003
14,Allen County,IN,7,379299,1.845510,41.098643,-85.122309,18003
15,Anchorage County,AK,5,288000,1.736111,0.000000,0.000000,0
16,Anderson County,SC,1,202558,0.493686,34.557506,-82.618235,45007
17,Anderson County,TX,1,57735,1.732052,31.776145,-95.687077,48001
18,Androscoggin County,ME,1,108277,0.923557,44.119070,-70.201319,23001
19,Angelina County,TX,1,86715,1.153203,31.312607,-94.714142,48005
20,Anne Arundel County,MD,9,579234,1.553776,39.067301,-76.598955,24003
21,Anoka County,MN,2,356921,0.560348,45.195144,-93.270276,27003
22,Arapahoe County,CO,5,656590,0.761510,39.647529,-104.845956,8005
23,Arlington County,VA,2,236842,0.844445,38.874902,-77.100824,51013
24,Ascension County,LA,1,126604,0.789864,30.248524,-90.934024,22005
25,Atlantic County,NJ,1,263670,0.379262,39.427563,-74.583546,34001
26,Augusta County,VA,1,75558,1.323487,38.128030,-79.032118,51015
27,Baldwin County,AL,2,223234,0.895921,30.548923,-87.762466,1003
28,Baldwin County,GA,1,44890,2.227668,33.084849,-83.245661,13009
29,Baltimore County,MD,12,827370,1.450379,39.369253,-76.620394,24005
...,...,...,...,...,...,...,...,...
598,Washington County,WI,1,136034,0.735110,43.347345,-88.215168,55131
599,Washoe County,NV,5,471519,1.060403,39.535559,-119.795471,32031
600,Washtenaw County,MI,14,367601,3.808477,42.256944,-83.727176,26161
601,Waukesha County,WI,2,404198,0.494807,43.034419,-88.236907,55133
602,Wayne County,IN,1,65884,1.517819,39.842738,-84.949824,18177
603,Wayne County,MI,21,1749343,1.200451,42.332610,-83.217867,26163
604,Webb County,TX,2,276652,0.722930,27.520331,-99.476354,48479
605,Weber County,UT,3,260213,1.152902,41.224613,-111.990296,49057
606,Webster County,IA,1,35904,2.785205,42.480376,-94.179074,19187
607,Weld County,CO,1,324492,0.308174,40.328082,-104.788375,8123
608,Westchester County,NY,25,967506,2.583963,41.040536,-73.804508,36119
609,Westmoreland County,PA,1,348899,0.286616,40.339403,-79.591825,42129
610,Whatcom County,WA,3,229247,1.308632,48.820552,-122.485376,53073
611,Wicomico County,MD,1,103609,0.965167,38.371572,-75.595079,24045
612,Will County,IL,5,690743,0.723858,41.565138,-88.057340,17197
613,Williamsburg County,VA,3,14954,20.061522,37.275869,-76.713075,51830
614,Williamson County,TN,8,238412,3.355536,35.920355,-86.855511,47187
615,Williamson County,TX,7,590551,1.185334,30.554707,-97.711416,48491
616,Winchester County,VA,2,28078,7.123014,39.175176,-78.170345,51840
617,Winnebago County,IL,2,282572,0.707784,42.307129,-89.062238,17201
618,Winnebago County,WI,2,171907,1.163420,44.100643,-88.539995,55139
619,Worcester County,MA,12,830622,1.444700,42.303704,-71.805419,25027
620,Wyandotte County,KS,4,165429,2.417956,39.104143,-94.707944,20209
621,Yakima County,WA,1,250873,0.398608,46.515823,-120.416704,53077
622,Yavapai County,AZ,1,235099,0.425353,34.629014,-112.267658,4025
623,Yellowstone County,MT,3,161300,1.859888,45.791309,-108.539333,30111
624,Yolo County,CA,2,220500,0.907029,38.598913,-121.721152,6113
625,York County,ME,1,207641,0.481600,43.424107,-70.640467,23031
626,York County,PA,3,449058,0.668065,39.942113,-76.750877,42133
627,Yuma County,AZ,1,213787,0.467755,32.650039,-114.598588,4027

In [ ]:
grouped_df.to_csv('allergist_latlong.csv')

In [85]:
for county in counties:
    print(county)
    print(county.replace(" County", ""))

Ada County
Ada
Adair County
Adair
Adams County
Adams
Aiken County
Aiken
Alachua County
Alachua
Alameda County
Alameda
Alamosa County
Alamosa
Albany County
Albany
Albemarle County
Albemarle
Alexandria city
Alexandria city
Allegan County
Allegan
Allegany County
Allegany
Allegheny County
Allegheny
Allen County
Allen
Anchorage Municipality
Anchorage Municipality
Anderson County
Anderson
Androscoggin County
Androscoggin
Angelina County
Angelina
Anne Arundel County
Anne Arundel
Anoka County
Anoka
Arapahoe County
Arapahoe
Arlington County
Arlington
Ascension Parish
Ascension Parish
Atlantic County
Atlantic
Augusta County
Augusta
Baldwin County
Baldwin
Baltimore County
Baltimore
Baltimore city
Baltimore city
Bannock County
Bannock
Barnstable County
Barnstable
Bartholomew County
Bartholomew
Bartow County
Bartow
Bay County
Bay
Beaver County
Beaver
Bedford County
Bedford
Bell County
Bell
Bennington County
Bennington
Benton County
Benton
Bergen County
Bergen
Berks County
Berks
Berkshire County
Berkshire
Bernalillo County
Bernalillo
Berrien County
Berrien
Bexar County
Bexar
Bibb County
Bibb
Black Hawk County
Black Hawk
Blair County
Blair
Blount County
Blount
Blue Earth County
Blue Earth
Bonneville County
Bonneville
Boone County
Boone
Bossier Parish
Bossier Parish
Botetourt County
Botetourt
Boulder County
Boulder
Bowie County
Bowie
Boyd County
Boyd
Bradford County
Bradford
Brazoria County
Brazoria
Brazos County
Brazos
Brevard County
Brevard
Bristol County
Bristol
Bronx County
Bronx
Broome County
Broome
Broward County
Broward
Brown County
Brown
Bucks County
Bucks
Buncombe County
Buncombe
Burke County
Burke
Burleigh County
Burleigh
Burlington County
Burlington
Butler County
Butler
Butte County
Butte
Cabell County
Cabell
Cache County
Cache
Caddo Parish
Caddo Parish
Calcasieu Parish
Calcasieu Parish
Calhoun County
Calhoun
Calvert County
Calvert
Camden County
Camden
Cameron County
Cameron
Campbell County
Campbell
Cape Girardeau County
Cape Girardeau
Carroll County
Carroll
Cascade County
Cascade
Cass County
Cass
Catawba County
Catawba
Cattaraugus County
Cattaraugus
Cayuga County
Cayuga
Cecil County
Cecil
Centre County
Centre
Champaign County
Champaign
Charles County
Charles
Charleston County
Charleston
Charlotte County
Charlotte
Charlottesville city
Charlottesville city
Chatham County
Chatham
Chelan County
Chelan
Cherokee County
Cherokee
Chesapeake city
Chesapeake city
Cheshire County
Cheshire
Chester County
Chester
Chesterfield County
Chesterfield
Chippewa County
Chippewa
Chisago County
Chisago
Chittenden County
Chittenden
Christian County
Christian
Citrus County
Citrus
Clackamas County
Clackamas
Clarion County
Clarion
Clark County
Clark
Clarke County
Clarke
Clay County
Clay
Clinton County
Clinton
Cobb County
Cobb
Coffee County
Coffee
Collier County
Collier
Collin County
Collin
Columbia County
Columbia
Comal County
Comal
Comanche County
Comanche
Contra Costa County
Contra Costa
Cook County
Cook
Coos County
Coos
Coweta County
Coweta
Craighead County
Craighead
Craven County
Craven
Crow Wing County
Crow Wing
Cumberland County
Cumberland
Cuyahoga County
Cuyahoga
Dakota County
Dakota
Dallas County
Dallas
Dane County
Dane
Dauphin County
Dauphin
Davidson County
Davidson
Daviess County
Daviess
Davis County
Davis
DeKalb County
DeKalb
Delaware County
Delaware
Denton County
Denton
Denver County
Denver
Deschutes County
Deschutes
Dickson County
Dickson
District of Columbia
District of Columbia
Dorchester County
Dorchester
Douglas County
Douglas
DoÌ±a Ana County
DoÌ±a Ana
DuPage County
DuPage
Dubuque County
Dubuque
Durham County
Durham
Dutchess County
Dutchess
Duval County
Duval
East Baton Rouge Parish
East Baton Rouge Parish
Eau Claire County
Eau Claire
Ector County
Ector
Eddy County
Eddy
El Paso County
El Paso
Elkhart County
Elkhart
Ellis County
Ellis
Emmet County
Emmet
Erie County
Erie
Escambia County
Escambia
Essex County
Essex
Fairbanks North Star Borough
Fairbanks North Star Borough
Fairfax County
Fairfax
Fairfield County
Fairfield
Falls Church city
Falls Church city
Fauquier County
Fauquier
Fayette County
Fayette
Florence County
Florence
Floyd County
Floyd
Forsyth County
Forsyth
Fort Bend County
Fort Bend
Franklin County
Franklin
Frederick County
Frederick
Fredericksburg city
Fredericksburg city
Fresno County
Fresno
Fulton County
Fulton
Gallatin County
Gallatin
Gallia County
Gallia
Galveston County
Galveston
Garfield County
Garfield
Garland County
Garland
Genesee County
Genesee
Gloucester County
Gloucester
Goodhue County
Goodhue
Grafton County
Grafton
Grand Forks County
Grand Forks
Grand Traverse County
Grand Traverse
Green County
Green
Greene County
Greene
Greenville County
Greenville
Greenwood County
Greenwood
Gregg County
Gregg
Guilford County
Guilford
Gwinnett County
Gwinnett
Hall County
Hall
Hamilton County
Hamilton
Hampden County
Hampden
Hampshire County
Hampshire
Hancock County
Hancock
Hardin County
Hardin
Harford County
Harford
Harris County
Harris
Harrison County
Harrison
Harrisonburg city
Harrisonburg city
Hartford County
Hartford
Hawaii County
Hawaii
Hennepin County
Hennepin
Henrico County
Henrico
Henry County
Henry
Hernando County
Hernando
Hidalgo County
Hidalgo
Hillsborough County
Hillsborough
Hinds County
Hinds
Honolulu County
Honolulu
Horry County
Horry
Houston County
Houston
Howard County
Howard
Hudson County
Hudson
Humboldt County
Humboldt
Imperial County
Imperial
Indian River County
Indian River
Ingham County
Ingham
Iredell County
Iredell
Jackson County
Jackson
Jasper County
Jasper
Jefferson County
Jefferson
Jefferson Parish
Jefferson Parish
Johnson County
Johnson
Kalamazoo County
Kalamazoo
Kanawha County
Kanawha
Kandiyohi County
Kandiyohi
Kane County
Kane
Kankakee County
Kankakee
Kenai Peninsula Borough
Kenai Peninsula Borough
Kendall County
Kendall
Kennebec County
Kennebec
Kenosha County
Kenosha
Kent County
Kent
Kenton County
Kenton
Kern County
Kern
Kerr County
Kerr
King County
King
Kings County
Kings
Kitsap County
Kitsap
Knox County
Knox
Kootenai County
Kootenai
La Crosse County
La Crosse
La Plata County
La Plata
LaPorte County
LaPorte
Lackawanna County
Lackawanna
Lafayette Parish
Lafayette Parish
Lake County
Lake
Lamar County
Lamar
Lancaster County
Lancaster
Lane County
Lane
Laramie County
Laramie
Larimer County
Larimer
Lauderdale County
Lauderdale
Laurens County
Laurens
Leavenworth County
Leavenworth
Lee County
Lee
Lehigh County
Lehigh
Lenoir County
Lenoir
Leon County
Leon
Lewis and Clark County
Lewis and Clark
Lexington County
Lexington
Licking County
Licking
Lincoln County
Lincoln
Linn County
Linn
Litchfield County
Litchfield
Livingston County
Livingston
Lorain County
Lorain
Los Alamos County
Los Alamos
Los Angeles County
Los Angeles
Loudoun County
Loudoun
Lowndes County
Lowndes
Lubbock County
Lubbock
Lucas County
Lucas
Luzerne County
Luzerne
Lycoming County
Lycoming
Lynchburg city
Lynchburg city
Macomb County
Macomb
Macon County
Macon
Madison County
Madison
Mahoning County
Mahoning
Manatee County
Manatee
Marathon County
Marathon
Maricopa County
Maricopa
Marion County
Marion
Marquette County
Marquette
Matanuska-Susitna Borough
Matanuska-Susitna Borough
Maury County
Maury
McCracken County
McCracken
McHenry County
McHenry
McLean County
McLean
McLennan County
McLennan
Mecklenburg County
Mecklenburg
Medina County
Medina
Mendocino County
Mendocino
Merced County
Merced
Mercer County
Mercer
Mesa County
Mesa
Miami-Dade County
Miami-Dade
Middlesex County
Middlesex
Midland County
Midland
Mifflin County
Mifflin
Milwaukee County
Milwaukee
Minnehaha County
Minnehaha
Missoula County
Missoula
Mobile County
Mobile
Mohave County
Mohave
Monmouth County
Monmouth
Monongalia County
Monongalia
Monroe County
Monroe
Monterey County
Monterey
Montgomery County
Montgomery
Montour County
Montour
Moore County
Moore
Morgan County
Morgan
Morris County
Morris
Multnomah County
Multnomah
Muscogee County
Muscogee
Muskegon County
Muskegon
Muskogee County
Muskogee
Nacogdoches County
Nacogdoches
Napa County
Napa
Nash County
Nash
Nassau County
Nassau
Nevada County
Nevada
New Castle County
New Castle
New Hanover County
New Hanover
New Haven County
New Haven
New London County
New London
New York County
New York
Newport News city
Newport News city
Niagara County
Niagara
Norfolk County
Norfolk
Northampton County
Northampton
Nueces County
Nueces
Oakland County
Oakland
Ocean County
Ocean
Ohio County
Ohio
Okaloosa County
Okaloosa
Oklahoma County
Oklahoma
Olmsted County
Olmsted
Oneida County
Oneida
Onondaga County
Onondaga
Onslow County
Onslow
Ontario County
Ontario
Orange County
Orange
Orleans Parish
Orleans Parish
Osceola County
Osceola
Otsego County
Otsego
Ottawa County
Ottawa
Ouachita Parish
Ouachita Parish
Outagamie County
Outagamie
Ozaukee County
Ozaukee
Palm Beach County
Palm Beach
Pasco County
Pasco
Pasquotank County
Pasquotank
Passaic County
Passaic
Pennington County
Pennington
Penobscot County
Penobscot
Peoria County
Peoria
Phelps County
Phelps
Philadelphia County
Philadelphia
Pierce County
Pierce
Pike County
Pike
Pima County
Pima
Pinellas County
Pinellas
Pitt County
Pitt
Placer County
Placer
Plymouth County
Plymouth
Polk County
Polk
Porter County
Porter
Pottawatomie County
Pottawatomie
Potter County
Potter
Prince George's County
Prince George's
Prince William County
Prince William
Providence County
Providence
Pueblo County
Pueblo
Pulaski County
Pulaski
Putnam County
Putnam
Queens County
Queens
Racine County
Racine
Ramsey County
Ramsey
Randolph County
Randolph
Rapides Parish
Rapides Parish
Reno County
Reno
Richland County
Richland
Richmond County
Richmond
Richmond city
Richmond city
Riverside County
Riverside
Roanoke city
Roanoke city
Rock County
Rock
Rock Island County
Rock Island
Rockdale County
Rockdale
Rockingham County
Rockingham
Rockland County
Rockland
Ross County
Ross
Rutherford County
Rutherford
Sacramento County
Sacramento
Saginaw County
Saginaw
Salem city
Salem city
Saline County
Saline
Salt Lake County
Salt Lake
San Bernardino County
San Bernardino
San Diego County
San Diego
San Francisco County
San Francisco
San Joaquin County
San Joaquin
San Luis Obispo County
San Luis Obispo
San Mateo County
San Mateo
Sangamon County
Sangamon
Santa Barbara County
Santa Barbara
Santa Clara County
Santa Clara
Santa Cruz County
Santa Cruz
Santa Fe County
Santa Fe
Sarasota County
Sarasota
Saratoga County
Saratoga
Sarpy County
Sarpy
Schenectady County
Schenectady
Schuylkill County
Schuylkill
Scott County
Scott
Sebastian County
Sebastian
Sedgwick County
Sedgwick
Seminole County
Seminole
Sevier County
Sevier
Shawnee County
Shawnee
Sheboygan County
Sheboygan
Shelby County
Shelby
Sherburne County
Sherburne
Skagit County
Skagit
Smith County
Smith
Snohomish County
Snohomish
Solano County
Solano
Somerset County
Somerset
Sonoma County
Sonoma
Spartanburg County
Spartanburg
Spokane County
Spokane
St. Charles County
St. Charles
St. Clair County
St. Clair
St. Joseph County
St. Joseph
St. Landry Parish
St. Landry Parish
St. Lawrence County
St. Lawrence
St. Louis County
St. Louis
St. Louis city
St. Louis city
St. Lucie County
St. Lucie
St. Mary's County
St. Mary's
St. Tammany Parish
St. Tammany Parish
Stanislaus County
Stanislaus
Stark County
Stark
Stearns County
Stearns
Stephenson County
Stephenson
Steuben County
Steuben
Stevens County
Stevens
Story County
Story
Strafford County
Strafford
Suffolk County
Suffolk
Suffolk city
Suffolk city
Sullivan County
Sullivan
Summit County
Summit
Sumner County
Sumner
Sumter County
Sumter
Sussex County
Sussex
Tarrant County
Tarrant
Taylor County
Taylor
Tazewell County
Tazewell
Terrebonne Parish
Terrebonne Parish
Thurston County
Thurston
Tippecanoe County
Tippecanoe
Tompkins County
Tompkins
Towns County
Towns
Travis County
Travis
Trumbull County
Trumbull
Tulare County
Tulare
Tulsa County
Tulsa
Tuscaloosa County
Tuscaloosa
Tuscola County
Tuscola
Twin Falls County
Twin Falls
Union County
Union
Utah County
Utah
Vanderburgh County
Vanderburgh
Ventura County
Ventura
Victoria County
Victoria
Vigo County
Vigo
Virginia Beach city
Virginia Beach city
Volusia County
Volusia
Wake County
Wake
Walker County
Walker
Walla Walla County
Walla Walla
Ward County
Ward
Warren County
Warren
Washington County
Washington
Washoe County
Washoe
Washtenaw County
Washtenaw
Waukesha County
Waukesha
Wayne County
Wayne
Webb County
Webb
Weber County
Weber
Webster County
Webster
Weld County
Weld
Westchester County
Westchester
Westmoreland County
Westmoreland
Whatcom County
Whatcom
Wicomico County
Wicomico
Will County
Will
Williamsburg city
Williamsburg city
Williamson County
Williamson
Winchester city
Winchester city
Winnebago County
Winnebago
Worcester County
Worcester
Wyandotte County
Wyandotte
Yakima County
Yakima
Yavapai County
Yavapai
Yellowstone County
Yellowstone
Yolo County
Yolo
York County
York
Yuma County
Yuma