In [4]:
import requests
import pandas as pd
import json
import numpy as np
from datetime import datetime

token = 'gFDjDbFnzGphxnXxdePRQvmPQeXEOHRJ'

In [15]:
#Stations
richmond = 'GHCND:USW00013740'
scranton = 'GHCND:USW00014777'
springfield = 'GHCND:USC00190120'
hartford = 'GHCND:USW00014740'
mcallen = 'GHCND:USC00415701'
#mcallen = 'GHCND:USW00012959'
# newhaven = 'GHCND:USW00014758'
# # newhaven = 'GHCND:USC00065077'
# newhaven = 'GHCND:USW00054788'
newhaven = 'GHCND:USC00062169'
newhaven = 'GHCND:USW00094702'
milwaukee = 'GHCND:USC00479046'
milwaukee = 'GHCND:USC00475474'
milwaukee = 'GHCND:USW00014839'
stockton = 'GHCND:USC00048560'
labels = ['Richmond', 'Scranton','Springfield', 'Hartford', 'McAllen', 'New Haven']
cities = [richmond, scranton, springfield, hartford, mcallen, newhaven]

others = ['Stockton','Salt Lake City', 'Seattle', 'Provo', 'Durham']

In [16]:
#initialize lists to store data
dates_temp = []
dates_prcp = []
temps = []
prcp = []
min_temps_2 = []
#for each year from 2015-2019 ...
# year_range = list(range(1950,2021))
# year_range.remove(1978)
for year in range(1950, 2021):
# for year in year_range:
    year = str(year)
    print('working on year '+year)
    r = requests.get('https://www.ncdc.noaa.gov/cdo-web/api/v2/data?datasetid=GHCND&datatypeid=TMIN&limit=1000&stationid='+milwaukee+'&startdate='+year+'-01-01&enddate='+year+'-12-31', headers={'token':token})
    d = json.loads(r.text)
    min_temps = [item for item in d['results'] if item['datatype']=='TMIN']
    dates_temp += [item['date'] for item in min_temps]
    temps += [item['value'] for item in min_temps]

working on year 1950
working on year 1951
working on year 1952
working on year 1953
working on year 1954
working on year 1955
working on year 1956
working on year 1957
working on year 1958
working on year 1959
working on year 1960
working on year 1961
working on year 1962
working on year 1963
working on year 1964
working on year 1965
working on year 1966
working on year 1967
working on year 1968
working on year 1969
working on year 1970
working on year 1971
working on year 1972
working on year 1973
working on year 1974
working on year 1975
working on year 1976
working on year 1977
working on year 1978
working on year 1979
working on year 1980
working on year 1981
working on year 1982
working on year 1983
working on year 1984
working on year 1985
working on year 1986
working on year 1987
working on year 1988
working on year 1989
working on year 1990
working on year 1991
working on year 1992
working on year 1993
working on year 1994
working on year 1995
working on year 1996
working on year 1997
working on year 1998
working on year 1999
working on year 2000
working on year 2001
working on year 2002
working on year 2003
working on year 2004
working on year 2005
working on year 2006
working on year 2007
working on year 2008
working on year 2009
working on year 2010
working on year 2011
working on year 2012
working on year 2013
working on year 2014
working on year 2015
working on year 2016
working on year 2017
working on year 2018
working on year 2019
working on year 2020

In [17]:
temps

[28,
 44,
 -33,
 -128,
 -150,
 -94,
 -111,
 -111,
 -6,
 -100,
 -139,
 -22,
 -33,
 -122,
 -144,
 -150,
 -100,
 -194,
 -194,
 -139,
 -56,
 -6,
 -17,
 -17,
 -11,
 -172,
 -189,
 -50,
 -178,
 -194,
 -122,
 -133,
 -111,
 -139,
 -100,
 -39,
 6,
 -11,
 -6,
 -28,
 -17,
 -56,
 -33,
 -28,
 -33,
 -61,
 -61,
 -83,
 -78,
 -106,
 -94,
 -44,
 -89,
 -117,
 -200,
 -217,
 -161,
 -139,
 -78,
 -144,
 -200,
 -133,
 -28,
 -6,
 -17,
 17,
 -117,
 -133,
 -83,
 -50,
 -94,
 -133,
 -144,
 -94,
 -39,
 -61,
 -94,
 -50,
 0,
 0,
 6,
 11,
 0,
 -11,
 17,
 33,
 -44,
 -56,
 -33,
 0,
 0,
 -22,
 0,
 -6,
 -33,
 -50,
 -22,
 -39,
 -39,
 11,
 6,
 -67,
 -72,
 -39,
 -17,
 6,
 72,
 83,
 39,
 11,
 0,
 6,
 22,
 28,
 28,
 17,
 6,
 11,
 17,
 22,
 11,
 6,
 61,
 39,
 83,
 94,
 22,
 17,
 67,
 56,
 56,
 100,
 56,
 67,
 44,
 33,
 61,
 61,
 56,
 72,
 72,
 72,
 89,
 133,
 78,
 72,
 67,
 83,
 89,
 111,
 122,
 106,
 139,
 83,
 78,
 150,
 183,
 156,
 172,
 189,
 139,
 111,
 156,
 139,
 128,
 133,
 83,
 72,
 89,
 89,
 111,
 94,
 194,
 200,
 156,
 150,
 156,
 133,
 133,
 111,
 117,
 100,
 117,
 111,
 128,
 144,
 139,
 139,
 150,
 156,
 178,
 161,
 194,
 117,
 89,
 128,
 167,
 156,
 139,
 133,
 128,
 94,
 150,
 161,
 150,
 167,
 172,
 178,
 183,
 200,
 206,
 194,
 178,
 122,
 106,
 128,
 117,
 128,
 122,
 172,
 167,
 144,
 128,
 128,
 111,
 156,
 172,
 183,
 150,
 128,
 106,
 67,
 78,
 139,
 167,
 167,
 139,
 150,
 156,
 161,
 144,
 161,
 144,
 156,
 133,
 106,
 100,
 83,
 72,
 78,
 128,
 156,
 167,
 139,
 133,
 128,
 133,
 111,
 111,
 117,
 117,
 150,
 150,
 139,
 106,
 67,
 28,
 67,
 83,
 144,
 133,
 156,
 144,
 167,
 78,
 44,
 17,
 17,
 100,
 111,
 100,
 89,
 78,
 111,
 67,
 44,
 83,
 44,
 122,
 94,
 83,
 117,
 61,
 50,
 83,
 67,
 50,
 11,
 22,
 100,
 94,
 72,
 94,
 117,
 56,
 28,
 6,
 -39,
 -33,
 28,
 33,
 17,
 -22,
 -67,
 -89,
 -67,
 -67,
 -28,
 83,
 22,
 -28,
 0,
 6,
 -72,
 -78,
 -56,
 -200,
 -206,
 -178,
 -28,
 -28,
 -33,
 -50,
 -94,
 -111,
 11,
 -89,
 -117,
 -44,
 -6,
 -122,
 -83,
 -83,
 -133,
 -128,
 -72,
 -117,
 -156,
 -144,
 -161,
 -194,
 -200,
 -189,
 -144,
 -128,
 -83,
 -72,
 -144,
 -161,
 -200,
 -244,
 -144,
 -106,
 -111,
 -72,
 -22,
 -22,
 -39,
 -89,
 -67,
 -156,
 -222,
 -194,
 -128,
 -67,
 -117,
 -133,
 -6,
 -44,
 -44,
 -78,
 -39,
 -50,
 -11,
 -89,
 -178,
 -189,
 -128,
 -133,
 -128,
 -161,
 -106,
 -211,
 -272,
 -311,
 -206,
 -228,
 -283,
 -161,
 -78,
 -89,
 -144,
 -217,
 -256,
 -233,
 -133,
 0,
 -56,
 -106,
 -128,
 -117,
 -17,
 -11,
 -11,
 -6,
 -17,
 -17,
 -33,
 -39,
 -33,
 17,
 28,
 -44,
 -44,
 -44,
 -67,
 -44,
 -78,
 -28,
 33,
 -22,
 -117,
 -133,
 -39,
 -28,
 -17,
 0,
 6,
 -28,
 -67,
 -50,
 -72,
 -100,
 -111,
 -122,
 -94,
 -61,
 -89,
 -89,
 -39,
 28,
 39,
 33,
 -6,
 -11,
 -6,
 6,
 -6,
 17,
 -6,
 17,
 44,
 11,
 0,
 22,
 6,
 22,
 6,
 17,
 -17,
 -17,
 -6,
 22,
 -6,
 -17,
 33,
 17,
 6,
 44,
 44,
 17,
 28,
 150,
 67,
 72,
 78,
 150,
 67,
 50,
 39,
 39,
 44,
 111,
 50,
 33,
 39,
 44,
 33,
 83,
 144,
 94,
 67,
 78,
 128,
 144,
 167,
 67,
 61,
 122,
 122,
 111,
 100,
 106,
 83,
 133,
 144,
 78,
 72,
 94,
 67,
 72,
 67,
 78,
 94,
 106,
 111,
 111,
 128,
 100,
 106,
 89,
 150,
 144,
 156,
 139,
 150,
 122,
 106,
 144,
 133,
 128,
 144,
 139,
 144,
 122,
 144,
 139,
 128,
 167,
 128,
 117,
 106,
 139,
 161,
 161,
 133,
 128,
 133,
 167,
 167,
 189,
 144,
 150,
 161,
 139,
 122,
 206,
 189,
 167,
 183,
 200,
 206,
 172,
 167,
 150,
 167,
 211,
 183,
 172,
 139,
 111,
 122,
 144,
 167,
 167,
 161,
 133,
 156,
 139,
 133,
 150,
 161,
 156,
 156,
 144,
 128,
 156,
 139,
 122,
 106,
 89,
 133,
 167,
 178,
 189,
 194,
 211,
 156,
 144,
 144,
 117,
 100,
 117,
 150,
 89,
 78,
 89,
 156,
 144,
 150,
 117,
 100,
 89,
 78,
 89,
 89,
 128,
 150,
 111,
 61,
 56,
 117,
 78,
 133,
 61,
 28,
 22,
 111,
 111,
 167,
 172,
 117,
 89,
 72,
 50,
 0,
 33,
 28,
 44,
 56,
 94,
 72,
 94,
 94,
 78,
 39,
 17,
 17,
 100,
 67,
 61,
 22,
 28,
 56,
 11,
 0,
 -6,
 17,
 -11,
 -67,
 -106,
 -128,
 -106,
 -150,
 -89,
 -67,
 -72,
 -17,
 11,
 -11,
 61,
 72,
 17,
 0,
 -28,
 -61,
 -78,
 -83,
 -83,
 -17,
 -44,
 -83,
 -106,
 -94,
 -61,
 -94,
 -22,
 -28,
 -22,
 28,
 28,
 56,
 17,
 6,
 28,
 28,
 -6,
 -44,
 -67,
 -89,
 -122,
 -156,
 -100,
 -217,
 -233,
 -222,
 -156,
 -161,
 -56,
 -161,
 -178,
 -194,
 -228,
 -83,
 -156,
 -172,
 -94,
 -94,
 -11,
 17,
 -128,
 -144,
 -133,
 -100,
 -72,
 -44,
 -89,
 -22,
 -44,
 -117,
 -100,
 -78,
 -111,
 -28,
 -22,
 -33,
 -39,
 -44,
 0,
 -117,
 -111,
 -78,
 -150,
 -222,
 -89,
 -72,
 -111,
 -194,
 -228,
 -194,
 -44,
 11,
 -22,
 11,
 -22,
 -33,
 -61,
 -72,
 -67,
 -61,
 -61,
 -50,
 -39,
 -44,
 -56,
 -50,
 -61,
 -44,
 -44,
 -44,
 -61,
 -78,
 -128,
 -94,
 -67,
 -94,
 -33,
 -50,
 -22,
 -50,
 -83,
 -39,
 -17,
 -106,
 -128,
 -94,
 -94,
 -50,
 0,
 11,
 -17,
 -11,
 -33,
 -72,
 -83,
 -67,
 -67,
 17,
 28,
 -6,
 6,
 -11,
 -61,
 -67,
 -72,
 -50,
 -39,
 -22,
 -39,
 22,
 83,
 44,
 11,
 -11,
 -11,
 0,
 0,
 -28,
 -22,
 11,
 -17,
 -22,
 0,
 17,
 11,
 17,
 11,
 83,
 89,
 94,
 122,
 128,
 56,
 39,
 39,
 39,
 44,
 100,
 100,
 100,
 117,
 89,
 61,
 61,
 128,
 172,
 56,
 44,
 50,
 72,
 44,
 33,
 61,
 72,
 100,
 72,
 56,
 39,
 61,
 78,
 72,
 50,
 89,
 94,
 94,
 117,
 94,
 111,
 89,
 56,
 111,
 78,
 78,
 94,
 106,
 89,
 117,
 167,
 144,
 194,
 139,
 144,
 122,
 133,
 133,
 178,
 139,
 139,
 167,
 150,
 122,
 117,
 128,
 128,
 139,
 178,
 217,
 150,
 139,
 161,
 167,
 167,
 156,
 167,
 189,
 167,
 178,
 167,
 167,
 128,
 117,
 172,
 194,
 228,
 217,
 150,
 156,
 189,
 228,
 211,
 222,
 228,
 233,
 228,
 167,
 144,
 156,
 217,
 194,
 144,
 128,
 150,
 122,
 150,
 161,
 156,
 167,
 150,
 139,
 144,
 172,
 194,
 167,
 144,
 122,
 133,
 178,
 200,
 178,
 156,
 150,
 139,
 178,
 150,
 117,
 100,
 111,
 133,
 161,
 183,
 178,
 183,
 189,
 206,
 128,
 117,
 89,
 106,
 122,
 133,
 144,
 133,
 161,
 178,
 178,
 156,
 172,
 144,
 106,
 100,
 100,
 100,
 72,
 67,
 61,
 83,
 56,
 67,
 117,
 72,
 ...]

In [18]:
#initialize dataframe
df_temp = pd.DataFrame()

#populate date and average temperature fields (cast string date to datetime and convert temperature from tenths of Celsius to Fahrenheit)
df_temp['date'] = [datetime.strptime(d, "%Y-%m-%dT%H:%M:%S") for d in dates_temp]
df_temp['minTemp'] = [float(v)/10.0*1.8 + 32 for v in temps]

In [19]:
df_temp['year'] = pd.DatetimeIndex(df_temp['date']).year
df_temp['month'] = pd.DatetimeIndex(df_temp['date']).month

In [20]:
def label_season (row):
    if row['month'] <= 5 and row['month'] >= 3:
        return 'Spring'
    else:
        if row['month'] <= 8 and row['month'] >= 6:
            return 'Summer'
        else:
            if row['month'] <= 11 and row['month'] >= 9:
                return 'Fall'
            else:
                return 'Winter'

df_temp['season'] = df_temp.apply(lambda row: label_season(row), axis=1)

In [21]:
df_temp

            date  minTemp  year  month  season
0     1950-01-01    37.04  1950      1  Winter
1     1950-01-02    39.92  1950      1  Winter
2     1950-01-03    26.06  1950      1  Winter
3     1950-01-04     8.96  1950      1  Winter
4     1950-01-05     5.00  1950      1  Winter
5     1950-01-06    15.08  1950      1  Winter
6     1950-01-07    12.02  1950      1  Winter
7     1950-01-08    12.02  1950      1  Winter
8     1950-01-09    30.92  1950      1  Winter
9     1950-01-10    14.00  1950      1  Winter
10    1950-01-11     6.98  1950      1  Winter
11    1950-01-12    28.04  1950      1  Winter
12    1950-01-13    26.06  1950      1  Winter
13    1950-01-14    10.04  1950      1  Winter
14    1950-01-15     6.08  1950      1  Winter
15    1950-01-16     5.00  1950      1  Winter
16    1950-01-17    14.00  1950      1  Winter
17    1950-01-18    -2.92  1950      1  Winter
18    1950-01-19    -2.92  1950      1  Winter
19    1950-01-20     6.98  1950      1  Winter
20    1950-01-21    21.92  1950      1  Winter
21    1950-01-22    30.92  1950      1  Winter
22    1950-01-23    28.94  1950      1  Winter
23    1950-01-24    28.94  1950      1  Winter
24    1950-01-25    30.02  1950      1  Winter
25    1950-01-26     1.04  1950      1  Winter
26    1950-01-27    -2.02  1950      1  Winter
27    1950-01-28    23.00  1950      1  Winter
28    1950-01-29    -0.04  1950      1  Winter
29    1950-01-30    -2.92  1950      1  Winter
...          ...      ...   ...    ...     ...
25692 2020-05-05    39.92  2020      5  Spring
25693 2020-05-06    39.02  2020      5  Spring
25694 2020-05-07    39.02  2020      5  Spring
25695 2020-05-08    32.00  2020      5  Spring
25696 2020-05-09    30.92  2020      5  Spring
25697 2020-05-10    37.04  2020      5  Spring
25698 2020-05-11    37.04  2020      5  Spring
25699 2020-05-12    37.04  2020      5  Spring
25700 2020-05-13    37.04  2020      5  Spring
25701 2020-05-14    51.08  2020      5  Spring
25702 2020-05-15    46.94  2020      5  Spring
25703 2020-05-16    44.96  2020      5  Spring
25704 2020-05-17    48.92  2020      5  Spring
25705 2020-05-18    46.94  2020      5  Spring
25706 2020-05-19    46.94  2020      5  Spring
25707 2020-05-20    48.02  2020      5  Spring
25708 2020-05-21    48.92  2020      5  Spring
25709 2020-05-22    51.08  2020      5  Spring
25710 2020-05-23    50.00  2020      5  Spring
25711 2020-05-24    55.04  2020      5  Spring
25712 2020-05-25    59.00  2020      5  Spring
25713 2020-05-26    64.04  2020      5  Spring
25714 2020-05-27    69.08  2020      5  Spring
25715 2020-05-28    62.96  2020      5  Spring
25716 2020-05-29    59.00  2020      5  Spring
25717 2020-05-30    50.00  2020      5  Spring
25718 2020-05-31    44.96  2020      5  Spring
25719 2020-06-01    48.02  2020      6  Summer
25720 2020-06-02    68.00  2020      6  Summer
25721 2020-06-03    66.92  2020      6  Summer

[25722 rows x 5 columns]

In [22]:
(df_temp[(df_temp.month == 12)])

            date  minTemp  year  month  season
334   1950-12-01    12.02  1950     12  Winter
335   1950-12-02    33.98  1950     12  Winter
336   1950-12-03    15.98  1950     12  Winter
337   1950-12-04    10.94  1950     12  Winter
338   1950-12-05    24.08  1950     12  Winter
339   1950-12-06    30.92  1950     12  Winter
340   1950-12-07    10.04  1950     12  Winter
341   1950-12-08    17.06  1950     12  Winter
342   1950-12-09    17.06  1950     12  Winter
343   1950-12-10     8.06  1950     12  Winter
344   1950-12-11     8.96  1950     12  Winter
345   1950-12-12    19.04  1950     12  Winter
346   1950-12-13    10.94  1950     12  Winter
347   1950-12-14     3.92  1950     12  Winter
348   1950-12-15     6.08  1950     12  Winter
349   1950-12-16     3.02  1950     12  Winter
350   1950-12-17    -2.92  1950     12  Winter
351   1950-12-18    -4.00  1950     12  Winter
352   1950-12-19    -2.02  1950     12  Winter
353   1950-12-20     6.08  1950     12  Winter
354   1950-12-21     8.96  1950     12  Winter
355   1950-12-22    17.06  1950     12  Winter
356   1950-12-23    19.04  1950     12  Winter
357   1950-12-24     6.08  1950     12  Winter
358   1950-12-25     3.02  1950     12  Winter
359   1950-12-26    -4.00  1950     12  Winter
360   1950-12-27   -11.92  1950     12  Winter
361   1950-12-28     6.08  1950     12  Winter
362   1950-12-29    12.92  1950     12  Winter
363   1950-12-30    12.02  1950     12  Winter
...          ...      ...   ...    ...     ...
25537 2019-12-02    24.26  2019     12  Winter
25538 2019-12-03    26.24  2019     12  Winter
25539 2019-12-04    33.08  2019     12  Winter
25540 2019-12-05    29.12  2019     12  Winter
25541 2019-12-06    25.16  2019     12  Winter
25542 2019-12-07    27.14  2019     12  Winter
25543 2019-12-08    35.06  2019     12  Winter
25544 2019-12-09    26.24  2019     12  Winter
25545 2019-12-10    14.18  2019     12  Winter
25546 2019-12-11    11.12  2019     12  Winter
25547 2019-12-12    17.24  2019     12  Winter
25548 2019-12-13    30.20  2019     12  Winter
25549 2019-12-14    23.18  2019     12  Winter
25550 2019-12-15    14.18  2019     12  Winter
25551 2019-12-16    23.18  2019     12  Winter
25552 2019-12-17    18.14  2019     12  Winter
25553 2019-12-18     7.16  2019     12  Winter
25554 2019-12-19    17.24  2019     12  Winter
25555 2019-12-20    30.20  2019     12  Winter
25556 2019-12-21    30.20  2019     12  Winter
25557 2019-12-22    37.04  2019     12  Winter
25558 2019-12-23    37.04  2019     12  Winter
25559 2019-12-24    37.94  2019     12  Winter
25560 2019-12-25    37.04  2019     12  Winter
25561 2019-12-26    37.04  2019     12  Winter
25562 2019-12-27    26.24  2019     12  Winter
25563 2019-12-28    24.26  2019     12  Winter
25564 2019-12-29    41.00  2019     12  Winter
25565 2019-12-30    26.24  2019     12  Winter
25566 2019-12-31    21.20  2019     12  Winter

[2170 rows x 5 columns]

In [23]:
df_temp[(df_temp.year==1986) & (df_temp.season == 'Fall')]

            date  minTemp  year  month season
13392 1986-09-01    55.94  1986      9   Fall
13393 1986-09-02    55.94  1986      9   Fall
13394 1986-09-03    64.94  1986      9   Fall
13395 1986-09-04    57.02  1986      9   Fall
13396 1986-09-05    51.98  1986      9   Fall
13397 1986-09-06    48.92  1986      9   Fall
13398 1986-09-07    44.96  1986      9   Fall
13399 1986-09-08    44.96  1986      9   Fall
13400 1986-09-09    44.06  1986      9   Fall
13401 1986-09-10    64.04  1986      9   Fall
13402 1986-09-11    60.08  1986      9   Fall
13403 1986-09-12    55.04  1986      9   Fall
13404 1986-09-13    53.96  1986      9   Fall
13405 1986-09-14    53.06  1986      9   Fall
13406 1986-09-15    51.08  1986      9   Fall
13407 1986-09-16    50.00  1986      9   Fall
13408 1986-09-17    53.96  1986      9   Fall
13409 1986-09-18    57.02  1986      9   Fall
13410 1986-09-19    59.00  1986      9   Fall
13411 1986-09-20    57.92  1986      9   Fall
13412 1986-09-21    57.92  1986      9   Fall
13413 1986-09-22    64.04  1986      9   Fall
13414 1986-09-23    60.98  1986      9   Fall
13415 1986-09-24    59.00  1986      9   Fall
13416 1986-09-25    64.94  1986      9   Fall
13417 1986-09-26    69.08  1986      9   Fall
13418 1986-09-27    66.92  1986      9   Fall
13419 1986-09-28    62.96  1986      9   Fall
13420 1986-09-29    64.04  1986      9   Fall
13421 1986-09-30    51.08  1986      9   Fall
...          ...      ...   ...    ...    ...
13453 1986-11-01    35.96  1986     11   Fall
13454 1986-11-02    28.04  1986     11   Fall
13455 1986-11-03    32.00  1986     11   Fall
13456 1986-11-04    32.00  1986     11   Fall
13457 1986-11-05    32.00  1986     11   Fall
13458 1986-11-06    30.92  1986     11   Fall
13459 1986-11-07    44.96  1986     11   Fall
13460 1986-11-08    39.92  1986     11   Fall
13461 1986-11-09    23.00  1986     11   Fall
13462 1986-11-10    21.02  1986     11   Fall
13463 1986-11-11    15.08  1986     11   Fall
13464 1986-11-12     8.96  1986     11   Fall
13465 1986-11-13     5.00  1986     11   Fall
13466 1986-11-14    15.08  1986     11   Fall
13467 1986-11-15    28.04  1986     11   Fall
13468 1986-11-16    30.02  1986     11   Fall
13469 1986-11-17    32.00  1986     11   Fall
13470 1986-11-18    23.00  1986     11   Fall
13471 1986-11-19    23.00  1986     11   Fall
13472 1986-11-20    32.00  1986     11   Fall
13473 1986-11-21    26.96  1986     11   Fall
13474 1986-11-22    30.92  1986     11   Fall
13475 1986-11-23    30.02  1986     11   Fall
13476 1986-11-24    26.06  1986     11   Fall
13477 1986-11-25    28.94  1986     11   Fall
13478 1986-11-26    26.96  1986     11   Fall
13479 1986-11-27    24.08  1986     11   Fall
13480 1986-11-28    28.94  1986     11   Fall
13481 1986-11-29    26.06  1986     11   Fall
13482 1986-11-30    33.98  1986     11   Fall

[91 rows x 5 columns]

In [13]:
years = range(1950,2020)
startdates = []
enddates = []
frost = []
growing = []
for year in years:
    #print(year)
    start = np.min(df_temp[(df_temp.year == year) & (df_temp.season == 'Fall') & (df_temp.minTemp <= 32)].date)
    end = np.max(df_temp[(df_temp.year == year+1) & (df_temp.season == 'Spring') & (df_temp.minTemp <= 32)].date)
    if pd.isnull(start):
        start = np.min(df_temp[(df_temp.year == year) & (df_temp.month == 12) & (df_temp.minTemp <= 32)].date)
    startdates.append(start)
    enddates.append(end)
    length = end - start
    grow = 365 - length.days
    frost.append(length)
    growing.append(grow)

In [14]:
df_richmond = pd.DataFrame()

In [15]:
df_richmond['year']=years
df_richmond['startdate'] = startdates
df_richmond['enddate'] = enddates
df_richmond['frost_season'] = frost
df_richmond['growing_season'] = growing
df_richmond['city'] = 'Richmond'
df_richmond

    year  startdate    enddate frost_season  growing_season      city
0   1950 1950-11-06 1951-04-18     163 days             202  Richmond
1   1951 1951-11-03 1952-04-08     157 days             208  Richmond
2   1952 1952-10-20 1953-04-20     182 days             183  Richmond
3   1953 1953-11-06 1954-04-10     155 days             210  Richmond
4   1954 1954-10-31 1955-04-08     159 days             206  Richmond
5   1955 1955-11-05 1956-05-09     186 days             179  Richmond
6   1956 1956-11-10 1957-04-15     156 days             209  Richmond
7   1957 1957-10-28 1958-04-04     158 days             207  Richmond
8   1958 1958-11-08 1959-03-29     141 days             224  Richmond
9   1959 1959-11-09 1960-04-11     154 days             211  Richmond
10  1960 1960-10-22 1961-04-30     190 days             175  Richmond
11  1961 1961-10-27 1962-04-17     172 days             193  Richmond
12  1962 1962-10-24 1963-03-23     150 days             215  Richmond
13  1963 1963-10-30 1964-04-10     163 days             202  Richmond
14  1964 1964-10-11 1965-04-05     176 days             189  Richmond
15  1965 1965-10-05 1966-05-11     218 days             147  Richmond
16  1966 1966-11-04 1967-03-31     147 days             218  Richmond
17  1967 1967-10-20 1968-03-25     157 days             208  Richmond
18  1968 1968-10-30 1969-04-01     153 days             212  Richmond
19  1969 1969-10-24 1970-04-08     166 days             199  Richmond
20  1970 1970-10-18 1971-03-31     164 days             201  Richmond
21  1971 1971-11-05 1972-04-10     157 days             208  Richmond
22  1972 1972-10-20 1973-04-15     177 days             188  Richmond
23  1973 1973-10-18 1974-04-11     175 days             190  Richmond
24  1974 1974-10-03 1975-04-14     193 days             172  Richmond
25  1975 1975-10-31 1976-04-27     179 days             186  Richmond
26  1976 1976-10-18 1977-04-10     174 days             191  Richmond
27  1977 1977-10-18 1978-03-18     151 days             214  Richmond
28  1978 1978-10-25 1979-04-07     164 days             201  Richmond
29  1979 1979-10-27 1980-03-19     144 days             221  Richmond
..   ...        ...        ...          ...             ...       ...
40  1990 1990-10-29 1991-03-31     153 days             212  Richmond
41  1991 1991-11-04 1992-04-06     154 days             211  Richmond
42  1992 1992-10-19 1993-03-20     152 days             213  Richmond
43  1993 1993-11-02 1994-03-20     138 days             227  Richmond
44  1994 1994-11-11 1995-04-05     145 days             220  Richmond
45  1995 1995-11-04 1996-04-08     156 days             209  Richmond
46  1996 1996-11-03 1997-04-10     158 days             207  Richmond
47  1997 1997-10-23 1998-03-25     153 days             212  Richmond
48  1998 1998-11-05 1999-03-23     138 days             227  Richmond
49  1999 1999-11-04 2000-03-19     136 days             229  Richmond
50  2000 2000-11-15 2001-04-19     155 days             210  Richmond
51  2001 2001-10-29 2002-04-07     160 days             205  Richmond
52  2002 2002-11-02 2003-03-31     149 days             216  Richmond
53  2003 2003-10-24 2004-04-06     165 days             200  Richmond
54  2004 2004-11-10 2005-03-21     131 days             234  Richmond
55  2005 2005-11-12 2006-04-10     149 days             216  Richmond
56  2006 2006-11-04 2007-04-10     157 days             208  Richmond
57  2007 2007-11-07 2008-04-16     161 days             204  Richmond
58  2008 2008-10-31 2009-03-25     145 days             220  Richmond
59  2009 2009-12-01 2010-03-27     116 days             249  Richmond
60  2010 2010-11-08 2011-04-06     149 days             216  Richmond
61  2011 2011-10-31 2012-03-11     132 days             233  Richmond
62  2012 2012-11-03 2013-04-04     152 days             213  Richmond
63  2013 2013-10-26 2014-03-27     152 days             213  Richmond
64  2014 2014-11-03 2015-03-29     146 days             219  Richmond
65  2015 2015-11-15 2016-04-10     147 days             218  Richmond
66  2016 2016-11-12 2017-03-24     132 days             233  Richmond
67  2017 2017-11-10 2018-03-27     137 days             228  Richmond
68  2018 2018-11-10 2019-04-03     144 days             221  Richmond
69  2019 2019-11-04 2020-05-10     188 days             177  Richmond

[70 rows x 6 columns]

In [24]:
#initialize lists to store data
dates_array = []
temps_array = []
#for each year from 2015-2019 ...
for city in cities:
    print(city)
    dates_temp = []
    temps = []
    for year in range(1950, 2021):
        year = str(year)
        print('working on year '+year)
        r = requests.get('https://www.ncdc.noaa.gov/cdo-web/api/v2/data?datasetid=GHCND&datatypeid=TMIN&limit=1000&stationid='+city+'&startdate='+year+'-01-01&enddate='+year+'-12-31', headers={'token':token})
        d = json.loads(r.text)
        min_temps = [item for item in d['results'] if item['datatype']=='TMIN']
        dates_temp += [item['date'] for item in min_temps]
        temps += [item['value'] for item in min_temps]
    dates_array.append([datetime.strptime(d, "%Y-%m-%dT%H:%M:%S") for d in dates_temp])
    temps_array.append([float(v)/10.0*1.8 + 32 for v in temps])

GHCND:USW00013740
working on year 1950
working on year 1951
working on year 1952
working on year 1953
working on year 1954
working on year 1955
working on year 1956
working on year 1957
working on year 1958
working on year 1959
working on year 1960
working on year 1961
working on year 1962
working on year 1963
working on year 1964
working on year 1965
working on year 1966
working on year 1967
working on year 1968
working on year 1969
working on year 1970
working on year 1971
working on year 1972
working on year 1973
working on year 1974
working on year 1975
working on year 1976
working on year 1977
working on year 1978
working on year 1979
working on year 1980
working on year 1981
working on year 1982
working on year 1983
working on year 1984
working on year 1985
working on year 1986
working on year 1987
working on year 1988
working on year 1989
working on year 1990
working on year 1991
working on year 1992
working on year 1993
working on year 1994
working on year 1995
working on year 1996
working on year 1997
working on year 1998
working on year 1999
working on year 2000
working on year 2001
working on year 2002
working on year 2003
working on year 2004
working on year 2005
working on year 2006
working on year 2007
working on year 2008
working on year 2009
working on year 2010
working on year 2011
working on year 2012
working on year 2013
working on year 2014
working on year 2015
working on year 2016
working on year 2017
working on year 2018
working on year 2019
working on year 2020
GHCND:USW00014777
working on year 1950
working on year 1951
working on year 1952
working on year 1953
working on year 1954
working on year 1955
working on year 1956
working on year 1957
working on year 1958
working on year 1959
working on year 1960
working on year 1961
working on year 1962
working on year 1963
working on year 1964
working on year 1965
working on year 1966
working on year 1967
working on year 1968
working on year 1969
working on year 1970
working on year 1971
working on year 1972
working on year 1973
working on year 1974
working on year 1975
working on year 1976
working on year 1977
working on year 1978
working on year 1979
working on year 1980
working on year 1981
working on year 1982
working on year 1983
working on year 1984
working on year 1985
working on year 1986
working on year 1987
working on year 1988
working on year 1989
working on year 1990
working on year 1991
working on year 1992
working on year 1993
working on year 1994
working on year 1995
working on year 1996
working on year 1997
working on year 1998
working on year 1999
working on year 2000
working on year 2001
working on year 2002
working on year 2003
working on year 2004
working on year 2005
working on year 2006
working on year 2007
working on year 2008
working on year 2009
working on year 2010
working on year 2011
working on year 2012
working on year 2013
working on year 2014
working on year 2015
working on year 2016
working on year 2017
working on year 2018
working on year 2019
working on year 2020
GHCND:USC00190120
working on year 1950
working on year 1951
working on year 1952
working on year 1953
working on year 1954
working on year 1955
working on year 1956
working on year 1957
working on year 1958
working on year 1959
working on year 1960
working on year 1961
working on year 1962
working on year 1963
working on year 1964
working on year 1965
working on year 1966
working on year 1967
working on year 1968
working on year 1969
working on year 1970
working on year 1971
working on year 1972
working on year 1973
working on year 1974
working on year 1975
working on year 1976
working on year 1977
working on year 1978
working on year 1979
working on year 1980
working on year 1981
working on year 1982
working on year 1983
working on year 1984
working on year 1985
working on year 1986
working on year 1987
working on year 1988
working on year 1989
working on year 1990
working on year 1991
working on year 1992
working on year 1993
working on year 1994
working on year 1995
working on year 1996
working on year 1997
working on year 1998
working on year 1999
working on year 2000
working on year 2001
working on year 2002
working on year 2003
working on year 2004
working on year 2005
working on year 2006
working on year 2007
working on year 2008
working on year 2009
working on year 2010
working on year 2011
working on year 2012
working on year 2013
working on year 2014
working on year 2015
working on year 2016
working on year 2017
working on year 2018
working on year 2019
working on year 2020
GHCND:USW00014740
working on year 1950
working on year 1951
working on year 1952
working on year 1953
working on year 1954
working on year 1955
working on year 1956
working on year 1957
working on year 1958
working on year 1959
working on year 1960
working on year 1961
working on year 1962
working on year 1963
working on year 1964
working on year 1965
working on year 1966
working on year 1967
working on year 1968
working on year 1969
working on year 1970
working on year 1971
working on year 1972
working on year 1973
working on year 1974
working on year 1975
working on year 1976
working on year 1977
working on year 1978
working on year 1979
working on year 1980
working on year 1981
working on year 1982
working on year 1983
working on year 1984
working on year 1985
working on year 1986
working on year 1987
working on year 1988
working on year 1989
working on year 1990
working on year 1991
working on year 1992
working on year 1993
working on year 1994
working on year 1995
working on year 1996
working on year 1997
working on year 1998
working on year 1999
working on year 2000
working on year 2001
working on year 2002
working on year 2003
working on year 2004
working on year 2005
working on year 2006
working on year 2007
working on year 2008
working on year 2009
working on year 2010
working on year 2011
working on year 2012
working on year 2013
working on year 2014
working on year 2015
working on year 2016
working on year 2017
working on year 2018
working on year 2019
working on year 2020
GHCND:USC00415701
working on year 1950
working on year 1951
working on year 1952
working on year 1953
working on year 1954
working on year 1955
working on year 1956
working on year 1957
working on year 1958
working on year 1959
working on year 1960
working on year 1961
working on year 1962
working on year 1963
working on year 1964
working on year 1965
working on year 1966
working on year 1967
working on year 1968
working on year 1969
working on year 1970
working on year 1971
working on year 1972
working on year 1973
working on year 1974
working on year 1975
working on year 1976
working on year 1977
working on year 1978
working on year 1979
working on year 1980
working on year 1981
working on year 1982
working on year 1983
working on year 1984
working on year 1985
working on year 1986
working on year 1987
working on year 1988
working on year 1989
working on year 1990
working on year 1991
working on year 1992
working on year 1993
working on year 1994
working on year 1995
working on year 1996
working on year 1997
working on year 1998
working on year 1999
working on year 2000
working on year 2001
working on year 2002
working on year 2003
working on year 2004
working on year 2005
working on year 2006
working on year 2007
working on year 2008
working on year 2009
working on year 2010
working on year 2011
working on year 2012
working on year 2013
working on year 2014
working on year 2015
working on year 2016
working on year 2017
working on year 2018
working on year 2019
working on year 2020
GHCND:USW00094702
working on year 1950
working on year 1951
working on year 1952
working on year 1953
working on year 1954
working on year 1955
working on year 1956
working on year 1957
working on year 1958
working on year 1959
working on year 1960
working on year 1961
working on year 1962
working on year 1963
working on year 1964
working on year 1965
working on year 1966
working on year 1967
working on year 1968
working on year 1969
working on year 1970
working on year 1971
working on year 1972
working on year 1973
working on year 1974
working on year 1975
working on year 1976
working on year 1977
working on year 1978
working on year 1979

working on year 1980
working on year 1981
working on year 1982
working on year 1983
working on year 1984
working on year 1985
working on year 1986
working on year 1987
working on year 1988
working on year 1989
working on year 1990
working on year 1991
working on year 1992
working on year 1993
working on year 1994
working on year 1995
working on year 1996
working on year 1997
working on year 1998
working on year 1999
working on year 2000
working on year 2001
working on year 2002
working on year 2003
working on year 2004
working on year 2005
working on year 2006
working on year 2007
working on year 2008
working on year 2009
working on year 2010
working on year 2011
working on year 2012
working on year 2013
working on year 2014
working on year 2015
working on year 2016
working on year 2017
working on year 2018
working on year 2019
working on year 2020

In [25]:
temps_array[3]

[19.939999999999998,
 28.94,
 32.0,
 46.94,
 41.0,
 35.96,
 24.08,
 1.9400000000000013,
 1.9400000000000013,
 21.92,
 21.92,
 15.079999999999998,
 24.98,
 33.98,
 23.0,
 28.94,
 21.92,
 24.08,
 12.920000000000002,
 10.940000000000001,
 12.920000000000002,
 19.939999999999998,
 28.04,
 30.02,
 28.04,
 32.0,
 19.939999999999998,
 12.920000000000002,
 30.02,
 26.060000000000002,
 19.04,
 21.02,
 28.04,
 15.079999999999998,
 10.04,
 15.98,
 17.06,
 10.04,
 1.9400000000000013,
 24.08,
 26.96,
 26.060000000000002,
 19.939999999999998,
 26.96,
 24.08,
 26.96,
 26.96,
 28.04,
 19.04,
 17.96,
 -5.080000000000005,
 -5.080000000000005,
 8.959999999999997,
 17.96,
 10.04,
 6.079999999999998,
 1.0399999999999991,
 -2.019999999999996,
 -2.9200000000000017,
 19.04,
 8.959999999999997,
 -2.019999999999996,
 -7.960000000000001,
 10.04,
 14.0,
 3.9200000000000017,
 24.98,
 15.98,
 14.0,
 12.920000000000002,
 26.96,
 24.08,
 15.079999999999998,
 10.940000000000001,
 12.920000000000002,
 19.04,
 17.96,
 14.0,
 15.98,
 28.94,
 21.02,
 33.08,
 35.06,
 28.94,
 24.98,
 35.06,
 37.04,
 32.0,
 24.08,
 21.02,
 19.939999999999998,
 33.08,
 32.0,
 46.94,
 37.94,
 26.060000000000002,
 24.08,
 24.08,
 30.92,
 24.98,
 26.96,
 28.94,
 28.94,
 28.94,
 28.04,
 32.0,
 28.94,
 41.0,
 41.0,
 42.08,
 35.06,
 32.0,
 30.02,
 33.08,
 30.02,
 41.0,
 42.08,
 42.08,
 35.06,
 33.08,
 41.0,
 39.92,
 44.06,
 42.08,
 48.019999999999996,
 48.019999999999996,
 42.980000000000004,
 32.0,
 35.06,
 46.04,
 48.92,
 46.04,
 42.08,
 39.92,
 37.94,
 48.92,
 46.04,
 46.94,
 44.06,
 42.08,
 35.96,
 37.94,
 39.92,
 53.96,
 57.92,
 55.040000000000006,
 46.04,
 44.96,
 53.06,
 55.94,
 55.040000000000006,
 51.980000000000004,
 46.94,
 57.019999999999996,
 48.92,
 44.96,
 48.92,
 53.96,
 57.92,
 60.08,
 60.980000000000004,
 55.94,
 46.94,
 44.96,
 51.08,
 57.019999999999996,
 60.980000000000004,
 50.0,
 46.04,
 44.06,
 55.040000000000006,
 60.08,
 48.92,
 51.08,
 60.08,
 64.03999999999999,
 60.980000000000004,
 60.980000000000004,
 55.040000000000006,
 53.06,
 57.92,
 59.0,
 51.08,
 64.94,
 64.03999999999999,
 60.980000000000004,
 62.06,
 57.019999999999996,
 55.94,
 62.96,
 62.06,
 62.06,
 68.0,
 62.96,
 57.92,
 48.92,
 57.92,
 64.03999999999999,
 66.92,
 60.08,
 57.019999999999996,
 51.08,
 53.96,
 53.96,
 53.96,
 64.03999999999999,
 59.0,
 51.980000000000004,
 55.94,
 55.94,
 60.980000000000004,
 60.980000000000004,
 62.96,
 59.0,
 60.980000000000004,
 57.92,
 51.980000000000004,
 57.92,
 53.06,
 46.04,
 53.06,
 64.94,
 62.06,
 55.040000000000006,
 51.980000000000004,
 53.06,
 51.980000000000004,
 57.92,
 59.0,
 62.96,
 64.03999999999999,
 62.06,
 53.06,
 46.94,
 59.0,
 55.94,
 57.019999999999996,
 59.0,
 62.06,
 64.03999999999999,
 66.02,
 62.96,
 62.06,
 66.92,
 64.03999999999999,
 55.94,
 53.96,
 46.94,
 46.94,
 46.94,
 51.980000000000004,
 55.94,
 60.08,
 55.040000000000006,
 51.980000000000004,
 46.04,
 51.980000000000004,
 60.08,
 44.96,
 33.98,
 35.96,
 48.019999999999996,
 53.06,
 50.0,
 48.92,
 37.04,
 32.0,
 30.02,
 35.06,
 44.06,
 46.94,
 42.980000000000004,
 50.0,
 50.0,
 55.040000000000006,
 55.040000000000006,
 44.06,
 30.92,
 28.04,
 42.980000000000004,
 46.94,
 55.94,
 51.980000000000004,
 48.019999999999996,
 48.92,
 44.96,
 37.94,
 37.94,
 33.98,
 30.92,
 50.0,
 55.94,
 42.980000000000004,
 30.92,
 39.92,
 39.019999999999996,
 42.980000000000004,
 42.08,
 33.08,
 21.92,
 24.98,
 48.92,
 48.019999999999996,
 39.92,
 41.0,
 44.96,
 42.980000000000004,
 42.980000000000004,
 37.94,
 28.94,
 33.98,
 48.019999999999996,
 51.08,
 33.08,
 26.96,
 19.939999999999998,
 21.02,
 21.92,
 19.939999999999998,
 42.08,
 39.019999999999996,
 24.98,
 19.04,
 39.019999999999996,
 30.92,
 19.939999999999998,
 17.96,
 28.04,
 42.980000000000004,
 35.06,
 32.0,
 32.0,
 30.92,
 30.02,
 28.94,
 21.02,
 32.0,
 42.08,
 30.02,
 24.08,
 28.94,
 42.980000000000004,
 30.02,
 24.98,
 37.04,
 32.0,
 21.02,
 21.02,
 24.98,
 30.92,
 19.939999999999998,
 17.96,
 10.940000000000001,
 6.98,
 8.059999999999999,
 14.0,
 26.96,
 28.94,
 12.02,
 3.9200000000000017,
 -0.9400000000000048,
 -5.980000000000004,
 10.940000000000001,
 19.939999999999998,
 24.08,
 14.0,
 15.98,
 35.96,
 35.06,
 24.08,
 24.98,
 21.02,
 12.02,
 -0.9400000000000048,
 15.079999999999998,
 12.920000000000002,
 30.02,
 21.02,
 8.959999999999997,
 32.0,
 26.96,
 19.939999999999998,
 26.96,
 26.96,
 26.96,
 19.04,
 8.959999999999997,
 10.940000000000001,
 28.94,
 24.98,
 21.92,
 15.98,
 15.98,
 21.02,
 5.0,
 1.9400000000000013,
 14.0,
 14.0,
 10.04,
 17.06,
 19.04,
 14.0,
 24.08,
 6.079999999999998,
 -0.03999999999999915,
 -2.9200000000000017,
 15.079999999999998,
 26.060000000000002,
 35.06,
 24.98,
 17.96,
 12.920000000000002,
 19.04,
 35.06,
 35.06,
 33.08,
 33.98,
 35.06,
 24.98,
 23.0,
 32.0,
 28.04,
 33.98,
 32.0,
 23.0,
 21.92,
 24.08,
 28.04,
 28.94,
 21.92,
 35.06,
 32.0,
 23.0,
 19.04,
 24.98,
 35.06,
 35.06,
 35.96,
 33.98,
 33.08,
 28.94,
 24.98,
 26.060000000000002,
 26.96,
 26.060000000000002,
 21.02,
 17.96,
 35.06,
 24.98,
 23.0,
 15.079999999999998,
 30.92,
 44.06,
 42.980000000000004,
 37.94,
 30.92,
 42.08,
 35.96,
 33.08,
 30.02,
 33.98,
 30.92,
 39.92,
 37.94,
 37.94,
 42.08,
 35.96,
 39.92,
 39.92,
 37.04,
 30.92,
 32.0,
 28.04,
 39.92,
 37.94,
 37.94,
 35.06,
 39.019999999999996,
 30.02,
 44.06,
 46.04,
 39.92,
 37.04,
 48.019999999999996,
 46.94,
 39.019999999999996,
 42.08,
 41.0,
 37.94,
 35.06,
 35.96,
 46.94,
 44.06,
 42.08,
 48.019999999999996,
 42.980000000000004,
 44.06,
 39.019999999999996,
 46.94,
 44.96,
 50.0,
 48.019999999999996,
 44.96,
 39.92,
 57.92,
 62.96,
 60.08,
 51.980000000000004,
 48.92,
 46.04,
 44.06,
 51.980000000000004,
 51.980000000000004,
 53.06,
 53.96,
 53.06,
 55.94,
 60.980000000000004,
 62.06,
 55.94,
 55.94,
 51.980000000000004,
 50.0,
 42.08,
 53.96,
 51.980000000000004,
 50.0,
 46.94,
 46.94,
 48.92,
 48.92,
 53.96,
 53.06,
 59.0,
 57.019999999999996,
 57.92,
 62.96,
 57.92,
 66.02,
 59.0,
 62.06,
 55.040000000000006,
 60.980000000000004,
 60.08,
 60.980000000000004,
 60.980000000000004,
 62.96,
 55.040000000000006,
 55.040000000000006,
 60.08,
 60.08,
 60.08,
 53.96,
 60.08,
 59.0,
 64.03999999999999,
 62.96,
 66.02,
 64.94,
 62.96,
 57.92,
 62.06,
 64.94,
 64.03999999999999,
 62.96,
 57.92,
 50.0,
 69.98,
 69.08000000000001,
 60.980000000000004,
 57.019999999999996,
 57.019999999999996,
 66.92,
 66.92,
 66.02,
 68.0,
 66.02,
 66.02,
 51.08,
 53.96,
 57.019999999999996,
 51.980000000000004,
 44.96,
 53.06,
 59.0,
 60.08,
 71.06,
 69.98,
 69.98,
 68.0,
 64.03999999999999,
 66.92,
 64.03999999999999,
 64.03999999999999,
 57.019999999999996,
 51.08,
 55.94,
 60.980000000000004,
 57.019999999999996,
 51.08,
 53.06,
 57.92,
 55.040000000000006,
 59.0,
 59.0,
 62.06,
 60.980000000000004,
 64.03999999999999,
 53.96,
 51.08,
 53.96,
 51.980000000000004,
 46.94,
 51.08,
 57.92,
 51.980000000000004,
 44.96,
 51.08,
 53.96,
 62.96,
 64.94,
 64.03999999999999,
 53.96,
 48.019999999999996,
 55.040000000000006,
 51.08,
 48.92,
 48.019999999999996,
 57.019999999999996,
 55.94,
 53.96,
 42.980000000000004,
 51.980000000000004,
 42.08,
 35.96,
 46.04,
 37.04,
 26.96,
 44.96,
 48.92,
 55.94,
 55.040000000000006,
 57.92,
 53.06,
 46.04,
 42.980000000000004,
 39.019999999999996,
 35.06,
 42.08,
 39.92,
 30.02,
 28.04,
 33.98,
 44.96,
 42.980000000000004,
 48.019999999999996,
 44.06,
 41.0,
 33.98,
 48.019999999999996,
 50.0,
 55.040000000000006,
 48.019999999999996,
 39.019999999999996,
 46.04,
 35.06,
 30.02,
 28.04,
 44.06,
 33.08,
 30.02,
 28.94,
 21.92,
 21.02,
 21.02,
 33.98,
 37.04,
 26.96,
 26.060000000000002,
 30.92,
 21.92,
 28.04,
 46.94,
 44.06,
 41.0,
 33.98,
 24.98,
 19.939999999999998,
 15.079999999999998,
 15.079999999999998,
 17.06,
 37.94,
 32.0,
 23.0,
 28.94,
 17.06,
 10.04,
 23.0,
 19.04,
 23.0,
 30.02,
 24.08,
 24.98,
 39.92,
 48.92,
 44.06,
 53.96,
 39.92,
 24.98,
 19.04,
 19.939999999999998,
 17.06,
 12.02,
 15.98,
 1.0399999999999991,
 -5.980000000000004,
 5.0,
 5.0,
 -0.03999999999999915,
 30.92,
 21.92,
 17.06,
 24.98,
 15.98,
 19.939999999999998,
 8.059999999999999,
 -5.080000000000005,
 19.939999999999998,
 33.98,
 33.08,
 33.98,
 33.98,
 21.92,
 17.96,
 26.96,
 26.96,
 15.079999999999998,
 3.9200000000000017,
 17.96,
 23.0,
 10.940000000000001,
 10.940000000000001,
 24.98,
 32.0,
 33.08,
 23.0,
 17.06,
 32.0,
 21.02,
 30.92,
 15.079999999999998,
 10.04,
 30.92,
 14.0,
 8.959999999999997,
 26.060000000000002,
 39.019999999999996,
 26.060000000000002,
 3.019999999999996,
 -7.060000000000002,
 -5.080000000000005,
 15.079999999999998,
 33.08,
 23.0,
 35.96,
 35.96,
 24.08,
 24.08,
 19.939999999999998,
 24.98,
 23.0,
 24.08,
 17.96,
 10.940000000000001,
 10.940000000000001,
 10.940000000000001,
 10.940000000000001,
 28.04,
 26.96,
 19.04,
 15.079999999999998,
 28.94,
 26.060000000000002,
 15.079999999999998,
 12.02,
 12.920000000000002,
 15.98,
 23.0,
 26.96,
 26.96,
 19.04,
 8.059999999999999,
 21.02,
 30.02,
 30.92,
 32.0,
 30.02,
 30.02,
 26.96,
 28.94,
 33.98,
 30.92,
 24.98,
 24.98,
 21.02,
 21.02,
 28.04,
 28.04,
 30.92,
 32.0,
 30.02,
 35.96,
 35.96,
 35.06,
 28.04,
 28.04,
 30.02,
 28.04,
 26.96,
 28.04,
 28.94,
 39.92,
 37.94,
 35.06,
 35.06,
 42.980000000000004,
 41.0,
 35.06,
 37.04,
 37.04,
 32.0,
 35.06,
 28.04,
 39.92,
 42.980000000000004,
 42.980000000000004,
 35.96,
 33.98,
 39.92,
 44.96,
 53.06,
 44.06,
 37.94,
 51.980000000000004,
 44.96,
 42.08,
 42.08,
 48.019999999999996,
 48.019999999999996,
 46.04,
 42.980000000000004,
 35.06,
 37.94,
 35.96,
 35.96,
 35.06,
 35.96,
 44.96,
 41.0,
 41.0,
 44.06,
 48.019999999999996,
 46.94,
 44.96,
 46.04,
 48.019999999999996,
 42.08,
 35.06,
 46.04,
 42.980000000000004,
 50.0,
 51.08,
 51.980000000000004,
 42.08,
 46.94,
 48.019999999999996,
 48.92,
 50.0,
 41.0,
 57.019999999999996,
 55.040000000000006,
 57.019999999999996,
 60.08,
 60.08,
 51.980000000000004,
 55.040000000000006,
 60.980000000000004,
 55.94,
 60.980000000000004,
 55.94,
 57.019999999999996,
 51.980000000000004,
 57.019999999999996,
 59.0,
 50.0,
 53.06,
 60.980000000000004,
 64.94,
 64.03999999999999,
 60.980000000000004,
 55.040000000000006,
 55.94,
 55.94,
 53.96,
 51.980000000000004,
 60.08,
 66.92,
 69.98,
 64.94,
 64.94,
 62.96,
 57.92,
 53.06,
 53.06,
 55.94,
 68.0,
 64.03999999999999,
 62.06,
 62.06,
 64.03999999999999,
 66.02,
 64.94,
 64.94,
 60.980000000000004,
 64.94,
 64.03999999999999,
 68.0,
 71.96000000000001,
 68.0,
 66.02,
 73.03999999999999,
 73.03999999999999,
 69.98,
 71.06,
 64.03999999999999,
 66.02,
 53.96,
 55.94,
 64.94,
 59.0,
 64.94,
 55.040000000000006,
 66.02,
 60.08,
 60.08,
 60.08,
 64.03999999999999,
 69.98,
 66.92,
 66.02,
 62.96,
 62.06,
 62.96,
 66.02,
 64.94,
 66.92,
 59.0,
 57.019999999999996,
 66.92,
 64.94,
 60.980000000000004,
 53.96,
 53.96,
 57.92,
 53.06,
 46.94,
 46.94,
 46.94,
 53.06,
 62.96,
 60.980000000000004,
 71.06,
 62.96,
 60.08,
 60.980000000000004,
 64.03999999999999,
 55.040000000000006,
 48.019999999999996,
 50.0,
 51.980000000000004,
 51.08,
 44.96,
 42.980000000000004,
 48.92,
 59.0,
 62.96,
 62.96,
 57.92,
 55.040000000000006,
 53.96,
 50.0,
 46.94,
 60.08,
 51.08,
 48.019999999999996,
 46.04,
 46.04,
 44.96,
 50.0,
 46.04,
 ...]

In [165]:
temps_array[4]

[62.96,
 68.0,
 69.08000000000001,
 42.980000000000004,
 39.92,
 42.980000000000004,
 42.08,
 39.92,
 55.040000000000006,
 62.96,
 68.0,
 66.92,
 69.08000000000001,
 66.02,
 68.0,
 68.0,
 69.08000000000001,
 68.0,
 64.03999999999999,
 53.96,
 60.08,
 60.980000000000004,
 64.94,
 68.0,
 69.98,
 57.019999999999996,
 48.019999999999996,
 51.08,
 66.02,
 69.08000000000001,
 69.98,
 68.0,
 62.06,
 46.04,
 46.04,
 53.96,
 62.06,
 66.02,
 66.02,
 69.08000000000001,
 59.0,
 64.94,
 69.98,
 51.08,
 42.08,
 39.019999999999996,
 46.94,
 55.94,
 57.019999999999996,
 59.0,
 60.08,
 64.03999999999999,
 53.06,
 48.019999999999996,
 57.019999999999996,
 64.94,
 68.0,
 69.08000000000001,
 71.96000000000001,
 57.92,
 50.0,
 48.019999999999996,
 50.0,
 50.0,
 50.0,
 62.96,
 57.019999999999996,
 57.019999999999996,
 64.94,
 69.08000000000001,
 64.94,
 42.08,
 44.06,
 48.019999999999996,
 55.94,
 60.08,
 60.980000000000004,
 55.040000000000006,
 50.0,
 68.0,
 53.06,
 53.06,
 69.08000000000001,
 71.06,
 71.96000000000001,
 60.980000000000004,
 59.0,
 59.0,
 59.0,
 62.96,
 66.92,
 69.98,
 71.96000000000001,
 60.08,
 60.08,
 57.019999999999996,
 62.96,
 66.92,
 66.92,
 69.98,
 69.08000000000001,
 64.94,
 69.08000000000001,
 69.98,
 66.92,
 68.0,
 68.0,
 66.92,
 71.06,
 62.96,
 64.03999999999999,
 69.08000000000001,
 73.03999999999999,
 68.0,
 66.92,
 59.0,
 71.96000000000001,
 75.02,
 75.92,
 75.02,
 73.94,
 77.0,
 77.0,
 75.92,
 75.92,
 75.02,
 75.92,
 75.02,
 75.02,
 75.92,
 69.98,
 69.08000000000001,
 71.06,
 75.02,
 73.03999999999999,
 73.03999999999999,
 73.94,
 73.94,
 64.94,
 64.94,
 64.94,
 69.98,
 69.08000000000001,
 71.06,
 73.03999999999999,
 71.96000000000001,
 71.06,
 68.0,
 71.06,
 75.02,
 75.02,
 75.02,
 73.03999999999999,
 77.0,
 73.94,
 73.94,
 73.03999999999999,
 75.02,
 75.92,
 75.02,
 75.02,
 73.03999999999999,
 71.06,
 73.03999999999999,
 73.03999999999999,
 71.96000000000001,
 71.06,
 75.02,
 71.96000000000001,
 78.98,
 77.0,
 75.92,
 73.94,
 75.92,
 73.94,
 75.92,
 75.02,
 73.03999999999999,
 71.06,
 71.96000000000001,
 69.98,
 71.96000000000001,
 73.03999999999999,
 73.94,
 73.94,
 75.02,
 75.92,
 77.0,
 75.92,
 73.03999999999999,
 75.92,
 77.0,
 78.98,
 78.08000000000001,
 75.92,
 75.02,
 77.0,
 78.08000000000001,
 75.02,
 75.02,
 73.94,
 73.03999999999999,
 71.96000000000001,
 73.03999999999999,
 71.96000000000001,
 73.94,
 73.94,
 75.02,
 77.0,
 77.0,
 78.08000000000001,
 77.0,
 75.02,
 73.03999999999999,
 73.03999999999999,
 75.02,
 73.94,
 75.02,
 69.98,
 73.03999999999999,
 68.0,
 69.08000000000001,
 69.08000000000001,
 68.0,
 71.96000000000001,
 75.92,
 73.94,
 75.02,
 75.02,
 69.98,
 73.94,
 69.98,
 71.96000000000001,
 73.94,
 73.03999999999999,
 75.92,
 75.92,
 75.02,
 75.02,
 75.02,
 75.92,
 73.94,
 73.03999999999999,
 69.98,
 69.08000000000001,
 66.92,
 71.06,
 71.06,
 71.06,
 69.08000000000001,
 69.98,
 71.96000000000001,
 75.02,
 73.03999999999999,
 73.03999999999999,
 75.92,
 77.0,
 75.92,
 78.98,
 78.08000000000001,
 75.02,
 75.02,
 73.94,
 71.96000000000001,
 71.96000000000001,
 71.06,
 73.03999999999999,
 71.96000000000001,
 69.98,
 71.06,
 73.03999999999999,
 73.03999999999999,
 73.03999999999999,
 73.03999999999999,
 71.96000000000001,
 69.98,
 71.06,
 69.08000000000001,
 69.08000000000001,
 71.96000000000001,
 66.92,
 64.94,
 59.0,
 69.98,
 69.98,
 66.02,
 62.96,
 62.96,
 64.03999999999999,
 64.94,
 64.03999999999999,
 62.06,
 66.92,
 62.06,
 60.980000000000004,
 64.03999999999999,
 66.02,
 62.06,
 60.08,
 64.03999999999999,
 64.03999999999999,
 66.92,
 64.94,
 66.02,
 64.94,
 64.94,
 57.019999999999996,
 41.0,
 37.94,
 51.08,
 60.08,
 64.94,
 53.96,
 42.08,
 37.94,
 37.94,
 60.980000000000004,
 71.06,
 69.98,
 69.08000000000001,
 66.02,
 64.94,
 69.08000000000001,
 66.02,
 57.92,
 55.94,
 62.96,
 44.96,
 35.06,
 39.92,
 44.06,
 46.04,
 55.94,
 59.0,
 64.94,
 66.92,
 48.019999999999996,
 42.08,
 39.92,
 28.04,
 26.060000000000002,
 46.04,
 51.08,
 48.019999999999996,
 41.0,
 44.96,
 62.06,
 60.980000000000004,
 62.96,
 62.06,
 48.019999999999996,
 39.92,
 48.019999999999996,
 57.92,
 57.019999999999996,
 48.92,
 44.96,
 48.019999999999996,
 46.94,
 55.94,
 46.04,
 42.08,
 42.08,
 44.06,
 37.94,
 57.019999999999996,
 62.96,
 48.92,
 39.019999999999996,
 50.0,
 57.019999999999996,
 37.94,
 30.02,
 37.94,
 48.019999999999996,
 51.980000000000004,
 62.06,
 66.02,
 44.96,
 35.96,
 37.94,
 57.92,
 50.0,
 59.0,
 64.03999999999999,
 53.06,
 51.980000000000004,
 51.980000000000004,
 48.019999999999996,
 44.06,
 48.92,
 60.08,
 62.96,
 28.94,
 26.060000000000002,
 26.060000000000002,
 21.02,
 24.08,
 19.04,
 35.06,
 51.980000000000004,
 60.08,
 48.92,
 46.04,
 57.019999999999996,
 53.06,
 55.040000000000006,
 60.08,
 41.0,
 33.08,
 37.94,
 33.08,
 51.08,
 62.96,
 66.92,
 55.040000000000006,
 46.94,
 50.0,
 66.92,
 66.02,
 66.02,
 68.0,
 66.92,
 69.08000000000001,
 68.0,
 69.98,
 62.96,
 62.06,
 59.0,
 69.08000000000001,
 69.98,
 66.92,
 68.0,
 69.08000000000001,
 69.08000000000001,
 42.980000000000004,
 30.92,
 42.08,
 60.08,
 64.03999999999999,
 66.92,
 44.96,
 42.08,
 46.94,
 42.980000000000004,
 57.92,
 66.02,
 62.06,
 55.040000000000006,
 55.040000000000006,
 66.92,
 64.94,
 50.0,
 44.96,
 57.92,
 64.94,
 55.040000000000006,
 55.94,
 55.040000000000006,
 66.92,
 68.0,
 64.94,
 60.980000000000004,
 57.92,
 59.0,
 51.08,
 48.019999999999996,
 48.019999999999996,
 60.980000000000004,
 68.0,
 62.96,
 60.980000000000004,
 64.94,
 66.92,
 71.06,
 69.98,
 66.92,
 64.94,
 64.94,
 71.06,
 71.96000000000001,
 71.06,
 71.96000000000001,
 69.08000000000001,
 73.03999999999999,
 64.94,
 64.03999999999999,
 73.94,
 66.92,
 68.0,
 69.98,
 66.92,
 64.03999999999999,
 66.02,
 71.96000000000001,
 64.03999999999999,
 68.0,
 69.98,
 73.94,
 75.92,
 73.94,
 71.96000000000001,
 71.96000000000001,
 69.98,
 71.96000000000001,
 71.06,
 73.94,
 71.96000000000001,
 73.03999999999999,
 64.94,
 62.96,
 66.02,
 60.08,
 73.03999999999999,
 73.94,
 77.0,
 75.02,
 75.92,
 71.06,
 71.06,
 69.98,
 73.94,
 75.02,
 75.92,
 77.0,
 75.92,
 77.0,
 77.0,
 77.0,
 75.92,
 75.92,
 75.92,
 77.0,
 75.92,
 75.92,
 77.0,
 77.0,
 77.0,
 73.94,
 75.02,
 73.03999999999999,
 71.96000000000001,
 73.94,
 73.94,
 75.02,
 75.02,
 77.0,
 77.0,
 78.08000000000001,
 73.94,
 75.02,
 73.94,
 73.03999999999999,
 73.03999999999999,
 73.03999999999999,
 75.02,
 73.03999999999999,
 75.92,
 73.94,
 75.02,
 73.94,
 75.02,
 71.96000000000001,
 71.06,
 71.96000000000001,
 73.94,
 75.02,
 77.0,
 77.0,
 75.02,
 73.03999999999999,
 75.92,
 77.0,
 75.02,
 75.92,
 78.98,
 75.92,
 75.02,
 71.96000000000001,
 73.94,
 75.02,
 73.94,
 75.02,
 75.92,
 77.0,
 77.0,
 77.0,
 78.08000000000001,
 73.94,
 69.98,
 73.94,
 73.03999999999999,
 73.94,
 73.94,
 73.94,
 73.03999999999999,
 73.94,
 73.94,
 75.02,
 75.02,
 75.02,
 73.94,
 73.94,
 73.03999999999999,
 73.94,
 73.94,
 73.03999999999999,
 73.94,
 75.02,
 73.03999999999999,
 73.94,
 75.02,
 75.02,
 75.92,
 73.94,
 73.03999999999999,
 75.02,
 75.02,
 75.92,
 73.94,
 75.02,
 71.96000000000001,
 69.98,
 71.06,
 64.03999999999999,
 60.980000000000004,
 62.06,
 62.06,
 73.03999999999999,
 73.94,
 75.02,
 75.02,
 73.94,
 75.02,
 75.02,
 73.03999999999999,
 71.96000000000001,
 69.98,
 69.08000000000001,
 66.92,
 71.06,
 71.96000000000001,
 71.06,
 73.03999999999999,
 66.02,
 60.08,
 57.019999999999996,
 57.019999999999996,
 59.0,
 60.980000000000004,
 64.94,
 62.06,
 60.980000000000004,
 64.03999999999999,
 64.94,
 66.02,
 66.92,
 62.96,
 64.03999999999999,
 69.98,
 68.0,
 60.980000000000004,
 60.980000000000004,
 69.98,
 69.98,
 68.0,
 71.06,
 71.96000000000001,
 73.94,
 51.08,
 39.92,
 32.0,
 46.94,
 59.0,
 46.04,
 41.0,
 39.92,
 55.040000000000006,
 62.06,
 64.94,
 66.92,
 68.0,
 69.98,
 69.08000000000001,
 57.019999999999996,
 48.019999999999996,
 44.06,
 46.04,
 51.08,
 60.980000000000004,
 66.02,
 66.02,
 66.02,
 69.08000000000001,
 55.040000000000006,
 53.06,
 51.08,
 51.980000000000004,
 59.0,
 57.019999999999996,
 64.03999999999999,
 66.02,
 59.0,
 53.06,
 68.0,
 62.96,
 60.08,
 50.0,
 48.019999999999996,
 44.06,
 44.06,
 60.08,
 59.0,
 41.0,
 41.0,
 46.94,
 57.019999999999996,
 59.0,
 66.02,
 42.08,
 32.0,
 48.019999999999996,
 57.92,
 66.92,
 53.96,
 44.06,
 42.980000000000004,
 55.94,
 62.96,
 66.92,
 68.0,
 69.98,
 44.06,
 44.96,
 51.08,
 41.0,
 37.04,
 57.92,
 64.03999999999999,
 42.980000000000004,
 39.019999999999996,
 51.980000000000004,
 66.02,
 66.02,
 68.0,
 68.0,
 64.94,
 66.02,
 66.92,
 66.02,
 68.0,
 62.06,
 55.040000000000006,
 51.08,
 60.08,
 68.0,
 60.980000000000004,
 44.96,
 42.08,
 44.96,
 59.0,
 64.03999999999999,
 55.94,
 48.92,
 46.04,
 37.04,
 46.04,
 35.96,
 42.980000000000004,
 55.040000000000006,
 62.06,
 64.94,
 64.94,
 64.03999999999999,
 62.96,
 51.08,
 44.06,
 39.92,
 60.08,
 64.94,
 64.03999999999999,
 62.96,
 69.08000000000001,
 62.06,
 60.08,
 44.96,
 39.019999999999996,
 33.98,
 48.019999999999996,
 59.0,
 62.96,
 68.0,
 55.94,
 51.08,
 55.040000000000006,
 60.08,
 60.08,
 60.980000000000004,
 64.94,
 57.92,
 51.980000000000004,
 60.980000000000004,
 60.980000000000004,
 64.94,
 60.08,
 57.92,
 68.0,
 62.06,
 57.92,
 64.94,
 71.06,
 51.980000000000004,
 44.96,
 37.04,
 53.96,
 57.92,
 55.94,
 55.94,
 57.019999999999996,
 69.08000000000001,
 69.98,
 69.08000000000001,
 66.92,
 66.92,
 62.96,
 55.94,
 51.08,
 57.019999999999996,
 66.02,
 64.03999999999999,
 51.08,
 57.92,
 62.06,
 57.92,
 53.96,
 60.980000000000004,
 64.03999999999999,
 66.02,
 68.0,
 64.03999999999999,
 66.92,
 71.96000000000001,
 71.96000000000001,
 66.02,
 64.03999999999999,
 60.980000000000004,
 53.96,
 57.92,
 62.06,
 69.08000000000001,
 64.94,
 66.02,
 64.03999999999999,
 62.06,
 64.03999999999999,
 64.03999999999999,
 64.03999999999999,
 66.02,
 69.98,
 71.06,
 66.02,
 59.0,
 50.0,
 57.019999999999996,
 62.06,
 66.02,
 68.0,
 73.94,
 66.92,
 64.03999999999999,
 60.08,
 66.02,
 73.94,
 75.92,
 68.0,
 66.92,
 71.06,
 71.96000000000001,
 66.02,
 68.0,
 66.02,
 69.08000000000001,
 69.08000000000001,
 64.03999999999999,
 69.08000000000001,
 71.06,
 71.06,
 64.03999999999999,
 68.0,
 71.06,
 71.96000000000001,
 73.03999999999999,
 73.94,
 73.94,
 69.98,
 73.03999999999999,
 73.94,
 73.03999999999999,
 73.94,
 71.06,
 73.03999999999999,
 73.94,
 71.06,
 71.06,
 71.06,
 75.02,
 75.02,
 75.92,
 73.03999999999999,
 71.96000000000001,
 73.03999999999999,
 71.96000000000001,
 73.03999999999999,
 75.02,
 71.06,
 71.96000000000001,
 71.96000000000001,
 71.96000000000001,
 73.03999999999999,
 75.02,
 71.96000000000001,
 73.94,
 73.03999999999999,
 73.03999999999999,
 71.96000000000001,
 73.03999999999999,
 71.96000000000001,
 73.94,
 73.03999999999999,
 73.94,
 73.03999999999999,
 73.94,
 71.96000000000001,
 73.03999999999999,
 69.08000000000001,
 68.0,
 71.06,
 69.98,
 71.06,
 69.98,
 71.06,
 69.98,
 71.96000000000001,
 69.98,
 71.06,
 71.96000000000001,
 75.02,
 73.94,
 73.94,
 75.02,
 75.92,
 75.02,
 75.02,
 75.92,
 75.92,
 75.02,
 75.02,
 75.92,
 77.0,
 75.92,
 73.94,
 75.02,
 75.02,
 75.02,
 73.94,
 73.03999999999999,
 71.96000000000001,
 73.03999999999999,
 73.03999999999999,
 73.03999999999999,
 71.96000000000001,
 66.92,
 69.98,
 73.03999999999999,
 78.08000000000001,
 78.08000000000001,
 71.96000000000001,
 71.06,
 64.94,
 64.03999999999999,
 69.98,
 66.92,
 69.98,
 71.06,
 73.03999999999999,
 69.98,
 66.92,
 71.96000000000001,
 71.96000000000001,
 71.96000000000001,
 71.06,
 73.03999999999999,
 71.06,
 71.06,
 71.06,
 71.06,
 69.98,
 66.02,
 64.94,
 64.03999999999999,
 ...]

In [26]:
df_array = []
for i in range(len(dates_array)):
    df_temp = pd.DataFrame()
    df_temp['date'] = dates_array[i]
    df_temp['minTemp'] = temps_array[i]
    df_temp['year'] = pd.DatetimeIndex(df_temp['date']).year
    df_temp['month'] = pd.DatetimeIndex(df_temp['date']).month
    df_temp['season'] = df_temp.apply(lambda row: label_season(row), axis=1)
    df_temp['city'] = labels[i]
    df_array.append(df_temp)

In [27]:
mega_df = pd.concat(df_array)
mega_df

            date  minTemp  year  month  season       city
0     1950-01-01    30.92  1950      1  Winter   Richmond
1     1950-01-02    44.06  1950      1  Winter   Richmond
2     1950-01-03    55.04  1950      1  Winter   Richmond
3     1950-01-04    57.02  1950      1  Winter   Richmond
4     1950-01-05    57.92  1950      1  Winter   Richmond
5     1950-01-06    59.00  1950      1  Winter   Richmond
6     1950-01-07    28.94  1950      1  Winter   Richmond
7     1950-01-08    26.06  1950      1  Winter   Richmond
8     1950-01-09    28.04  1950      1  Winter   Richmond
9     1950-01-10    46.94  1950      1  Winter   Richmond
10    1950-01-11    37.94  1950      1  Winter   Richmond
11    1950-01-12    32.00  1950      1  Winter   Richmond
12    1950-01-13    33.98  1950      1  Winter   Richmond
13    1950-01-14    42.98  1950      1  Winter   Richmond
14    1950-01-15    30.92  1950      1  Winter   Richmond
15    1950-01-16    39.02  1950      1  Winter   Richmond
16    1950-01-17    32.00  1950      1  Winter   Richmond
17    1950-01-18    35.06  1950      1  Winter   Richmond
18    1950-01-19    28.94  1950      1  Winter   Richmond
19    1950-01-20    21.92  1950      1  Winter   Richmond
20    1950-01-21    19.94  1950      1  Winter   Richmond
21    1950-01-22    35.96  1950      1  Winter   Richmond
22    1950-01-23    42.98  1950      1  Winter   Richmond
23    1950-01-24    55.04  1950      1  Winter   Richmond
24    1950-01-25    51.98  1950      1  Winter   Richmond
25    1950-01-26    57.92  1950      1  Winter   Richmond
26    1950-01-27    32.00  1950      1  Winter   Richmond
27    1950-01-28    28.04  1950      1  Winter   Richmond
28    1950-01-29    35.96  1950      1  Winter   Richmond
29    1950-01-30    39.02  1950      1  Winter   Richmond
...          ...      ...   ...    ...     ...        ...
25692 2020-05-05    44.96  2020      5  Spring  New Haven
25693 2020-05-06    42.08  2020      5  Spring  New Haven
25694 2020-05-07    42.98  2020      5  Spring  New Haven
25695 2020-05-08    37.94  2020      5  Spring  New Haven
25696 2020-05-09    35.06  2020      5  Spring  New Haven
25697 2020-05-10    37.94  2020      5  Spring  New Haven
25698 2020-05-11    46.04  2020      5  Spring  New Haven
25699 2020-05-12    42.98  2020      5  Spring  New Haven
25700 2020-05-13    37.04  2020      5  Spring  New Haven
25701 2020-05-14    39.92  2020      5  Spring  New Haven
25702 2020-05-15    53.06  2020      5  Spring  New Haven
25703 2020-05-16    53.96  2020      5  Spring  New Haven
25704 2020-05-17    53.06  2020      5  Spring  New Haven
25705 2020-05-18    53.96  2020      5  Spring  New Haven
25706 2020-05-19    53.06  2020      5  Spring  New Haven
25707 2020-05-20    48.02  2020      5  Spring  New Haven
25708 2020-05-21    41.00  2020      5  Spring  New Haven
25709 2020-05-22    53.06  2020      5  Spring  New Haven
25710 2020-05-23    53.96  2020      5  Spring  New Haven
25711 2020-05-24    50.00  2020      5  Spring  New Haven
25712 2020-05-25    55.94  2020      5  Spring  New Haven
25713 2020-05-26    55.94  2020      5  Spring  New Haven
25714 2020-05-27    59.00  2020      5  Spring  New Haven
25715 2020-05-28    62.06  2020      5  Spring  New Haven
25716 2020-05-29    62.96  2020      5  Spring  New Haven
25717 2020-05-30    64.04  2020      5  Spring  New Haven
25718 2020-05-31    51.98  2020      5  Spring  New Haven
25719 2020-06-01    46.04  2020      6  Summer  New Haven
25720 2020-06-02    51.08  2020      6  Summer  New Haven
25721 2020-06-03    60.08  2020      6  Summer  New Haven

[152552 rows x 6 columns]

In [28]:
years = range(1950,2020)
startdates_array = []
enddates_array = []
frost_array = []
growing_array = []
for label in labels:
    df_temp = mega_df[mega_df.city==label]
    startdates = []
    enddates = []
    frost = []
    growing = []
    for year in years:
        #print(year)
        start = np.min(df_temp[(df_temp.year == year) & (df_temp.season == 'Fall') & (df_temp.minTemp <= 32)].date)
        end = np.max(df_temp[(df_temp.year == year+1) & (df_temp.season == 'Spring') & (df_temp.minTemp <= 32)].date)
        if pd.isnull(start):
            start = np.min(df_temp[(df_temp.year == year) & (df_temp.month == 12) & (df_temp.minTemp <= 32)].date)
            if pd.isnull(start):
                start = np.min(df_temp[(df_temp.year == year+1) & (df_temp.month == 1) & (df_temp.minTemp <= 32)].date)
        if pd.isnull(end):
            end = np.max(df_temp[(df_temp.year == year+1) & (df_temp.month == 2) & (df_temp.minTemp <= 32)].date)
            if pd.isnull(end):
                end = np.max(df_temp[(df_temp.year == year+1) & (df_temp.month == 1) & (df_temp.minTemp <= 32)].date)
                if pd.isnull(end):
                    end = end = np.max(df_temp[(df_temp.year == year) & (df_temp.month == 12) & (df_temp.minTemp <= 32)].date)
        startdates.append(start)
        enddates.append(end)
        length = end - start
        grow = 365 - length.days
        frost.append(length)
        growing.append(grow)
    startdates_array.append(startdates)
    enddates_array.append(enddates)
    frost_array.append(frost)
    growing_array.append(growing)

In [175]:
frost_array[2]

[Timedelta('231 days 00:00:00'),
 Timedelta('230 days 00:00:00'),
 Timedelta('187 days 00:00:00'),
 Timedelta('217 days 00:00:00'),
 Timedelta('184 days 00:00:00'),
 Timedelta('216 days 00:00:00'),
 Timedelta('209 days 00:00:00'),
 Timedelta('229 days 00:00:00'),
 Timedelta('200 days 00:00:00'),
 Timedelta('188 days 00:00:00'),
 Timedelta('241 days 00:00:00'),
 Timedelta('220 days 00:00:00'),
 Timedelta('245 days 00:00:00'),
 Timedelta('232 days 00:00:00'),
 Timedelta('221 days 00:00:00'),
 Timedelta('228 days 00:00:00'),
 Timedelta('243 days 00:00:00'),
 Timedelta('225 days 00:00:00'),
 Timedelta('234 days 00:00:00'),
 Timedelta('204 days 00:00:00'),
 Timedelta('231 days 00:00:00'),
 Timedelta('244 days 00:00:00'),
 Timedelta('217 days 00:00:00'),
 Timedelta('229 days 00:00:00'),
 Timedelta('218 days 00:00:00'),
 Timedelta('237 days 00:00:00'),
 Timedelta('228 days 00:00:00'),
 Timedelta('209 days 00:00:00'),
 Timedelta('208 days 00:00:00'),
 Timedelta('234 days 00:00:00'),
 Timedelta('233 days 00:00:00'),
 Timedelta('218 days 00:00:00'),
 Timedelta('227 days 00:00:00'),
 Timedelta('218 days 00:00:00'),
 Timedelta('235 days 00:00:00'),
 Timedelta('214 days 00:00:00'),
 Timedelta('239 days 00:00:00'),
 Timedelta('213 days 00:00:00'),
 Timedelta('212 days 00:00:00'),
 Timedelta('203 days 00:00:00'),
 Timedelta('213 days 00:00:00'),
 Timedelta('222 days 00:00:00'),
 Timedelta('241 days 00:00:00'),
 Timedelta('250 days 00:00:00'),
 Timedelta('185 days 00:00:00'),
 Timedelta('247 days 00:00:00'),
 Timedelta('216 days 00:00:00'),
 Timedelta('219 days 00:00:00'),
 Timedelta('220 days 00:00:00'),
 Timedelta('222 days 00:00:00'),
 Timedelta('228 days 00:00:00'),
 Timedelta('226 days 00:00:00'),
 Timedelta('193 days 00:00:00'),
 Timedelta('215 days 00:00:00'),
 Timedelta('219 days 00:00:00'),
 Timedelta('198 days 00:00:00'),
 Timedelta('213 days 00:00:00'),
 Timedelta('202 days 00:00:00'),
 Timedelta('208 days 00:00:00'),
 Timedelta('212 days 00:00:00'),
 Timedelta('208 days 00:00:00'),
 Timedelta('207 days 00:00:00'),
 Timedelta('214 days 00:00:00'),
 Timedelta('195 days 00:00:00'),
 Timedelta('187 days 00:00:00'),
 Timedelta('207 days 00:00:00'),
 Timedelta('205 days 00:00:00'),
 Timedelta('189 days 00:00:00'),
 Timedelta('192 days 00:00:00'),
 Timedelta('222 days 00:00:00')]

In [29]:
tempdf_array = []
for i in range(len(startdates_array)):
    tempdf = pd.DataFrame()
    tempdf['year'] = years
    tempdf['startdate'] = startdates_array[i]
    tempdf['enddate'] = enddates_array[i]
    tempdf['frost_season'] = frost_array[i]
    tempdf['growing_season'] = growing_array[i]
    tempdf['city'] = labels[i]
    tempdf['rank'] = i +1
    tempdf_array.append(tempdf)

In [30]:
worst_cities = pd.concat(tempdf_array)
worst_cities[worst_cities.city == "New Haven"]

    year  startdate    enddate frost_season  growing_season       city  rank
0   1950 1950-10-27 1951-03-27     151 days           214.0  New Haven     6
1   1951 1951-11-03 1952-04-12     161 days           204.0  New Haven     6
2   1952 1952-10-20 1953-03-22     153 days           212.0  New Haven     6
3   1953 1953-11-06 1954-03-22     136 days           229.0  New Haven     6
4   1954 1954-11-08 1955-04-09     152 days           213.0  New Haven     6
5   1955 1955-11-09 1956-04-25     168 days           197.0  New Haven     6
6   1956 1956-11-10 1957-04-16     157 days           208.0  New Haven     6
7   1957 1957-11-11 1958-04-11     151 days           214.0  New Haven     6
8   1958 1958-11-08 1959-03-29     141 days           224.0  New Haven     6
9   1959 1959-10-29 1960-04-11     165 days           200.0  New Haven     6
10  1960 1960-11-07 1961-04-04     148 days           217.0  New Haven     6
11  1961 1961-10-28 1962-04-18     172 days           193.0  New Haven     6
12  1962 1962-10-25 1963-04-06     163 days           202.0  New Haven     6
13  1963 1963-11-15 1964-04-06     143 days           222.0  New Haven     6
14  1964 1964-10-12 1965-04-03     173 days           192.0  New Haven     6
15  1965 1965-11-02 1966-05-11     190 days           175.0  New Haven     6
16  1966 1966-10-30 1967-04-13     165 days           200.0  New Haven     6
17  1967 1967-10-30 1968-04-06     159 days           206.0  New Haven     6
18  1968 1968-11-26 1969-04-07     132 days           233.0  New Haven     6
19  1969 1969-10-23 1970-04-11     170 days           195.0  New Haven     6
20  1970 1970-10-28 1971-04-17     171 days           194.0  New Haven     6
21  1971 1971-11-07 1972-04-09     154 days           211.0  New Haven     6
22  1972 1972-10-20 1973-04-15     177 days           188.0  New Haven     6
23  1973 1973-11-08 1974-04-10     153 days           212.0  New Haven     6
24  1974 1974-10-18 1975-04-22     186 days           179.0  New Haven     6
25  1975 1975-11-23 1976-04-13     142 days           223.0  New Haven     6
26  1976 1976-10-28 1977-04-10     164 days           201.0  New Haven     6
27  1977 1977-11-14 1978-04-03     140 days           225.0  New Haven     6
28  1978 1978-11-25 1979-04-08     134 days           231.0  New Haven     6
29  1979 1979-10-27 1980-04-17     173 days           192.0  New Haven     6
..   ...        ...        ...          ...             ...        ...   ...
40  1990 1990-11-09 1991-04-03     145 days           220.0  New Haven     6
41  1991 1991-11-06 1992-04-13     159 days           206.0  New Haven     6
42  1992 1992-11-08 1993-03-23     135 days           230.0  New Haven     6
43  1993 1993-10-14 1994-04-08     176 days           189.0  New Haven     6
44  1994 1994-11-12 1995-04-06     145 days           220.0  New Haven     6
45  1995 1995-11-06 1996-04-09     155 days           210.0  New Haven     6
46  1996 1996-11-12 1997-04-11     150 days           215.0  New Haven     6
47  1997 1997-10-23 1998-03-25     153 days           212.0  New Haven     6
48  1998 1998-11-04 1999-04-05     152 days           213.0  New Haven     6
49  1999 1999-11-08 2000-04-13     157 days           208.0  New Haven     6
50  2000 2000-11-19 2001-04-19     151 days           214.0  New Haven     6
51  2001 2001-11-11 2002-04-07     147 days           218.0  New Haven     6
52  2002 2002-10-24 2003-04-10     168 days           197.0  New Haven     6
53  2003 2003-11-08 2004-04-06     150 days           215.0  New Haven     6
54  2004 2004-11-09 2005-03-22     133 days           232.0  New Haven     6
55  2005 2005-11-12 2006-04-07     146 days           219.0  New Haven     6
56  2006 2006-10-27 2007-04-11     166 days           199.0  New Haven     6
57  2007 2007-11-08 2008-04-03     147 days           218.0  New Haven     6
58  2008 2008-10-24 2009-04-13     171 days           194.0  New Haven     6
59  2009 2009-11-07 2010-03-27     140 days           225.0  New Haven     6
60  2010 2010-11-20 2011-03-30     130 days           235.0  New Haven     6
61  2011 2011-10-31 2012-03-27     148 days           217.0  New Haven     6
62  2012 2012-11-06 2013-04-04     149 days           216.0  New Haven     6
63  2013 2013-11-04 2014-04-16     163 days           202.0  New Haven     6
64  2014 2014-11-08 2015-04-02     145 days           220.0  New Haven     6
65  2015 2015-10-19 2016-04-13     177 days           188.0  New Haven     6
66  2016 2016-11-01 2017-03-24     143 days           222.0  New Haven     6
67  2017 2017-11-10 2018-04-11     152 days           213.0  New Haven     6
68  2018 2018-11-12 2019-04-02     141 days           224.0  New Haven     6
69  2019 2019-11-08 2020-04-23     167 days           198.0  New Haven     6

[70 rows x 7 columns]

In [183]:
mega_df[(mega_df.city == "McAllen") & (mega_df.minTemp <= 32)]

            date  minTemp  year  month  season     city
339   1950-12-06    28.04  1950     12  Winter  McAllen
340   1950-12-07    26.06  1950     12  Winter  McAllen
372   1951-01-08    30.02  1951      1  Winter  McAllen
393   1951-01-29    28.94  1951      1  Winter  McAllen
394   1951-01-30    26.06  1951      1  Winter  McAllen
395   1951-01-31    26.06  1951      1  Winter  McAllen
396   1951-02-01    21.02  1951      2  Winter  McAllen
397   1951-02-02    24.08  1951      2  Winter  McAllen
398   1951-02-03    19.04  1951      2  Winter  McAllen
436   1951-03-13    30.92  1951      3  Spring  McAllen
671   1951-11-03    32.00  1951     11    Fall  McAllen
720   1951-12-22    32.00  1951     12  Winter  McAllen
1444  1953-12-15    32.00  1953     12  Winter  McAllen
1454  1953-12-25    30.02  1953     12  Winter  McAllen
1455  1953-12-26    30.02  1953     12  Winter  McAllen
1849  1955-01-24    30.92  1955      1  Winter  McAllen
1868  1955-02-12    28.04  1955      2  Winter  McAllen
2175  1955-12-16    32.00  1955     12  Winter  McAllen
2525  1956-11-30    32.00  1956     11    Fall  McAllen
2891  1957-12-01    28.04  1957     12  Winter  McAllen
2902  1957-12-12    26.06  1957     12  Winter  McAllen
2965  1958-02-13    28.04  1958      2  Winter  McAllen
3271  1958-12-16    28.04  1958     12  Winter  McAllen
3291  1959-01-05    30.02  1959      1  Winter  McAllen
3296  1959-01-10    32.00  1959      1  Winter  McAllen
3608  1959-11-18    32.00  1959     11    Fall  McAllen
3619  1959-11-29    30.02  1959     11    Fall  McAllen
3627  1959-12-07    32.00  1959     12  Winter  McAllen
3672  1960-01-21    32.00  1960      1  Winter  McAllen
3707  1960-02-25    28.94  1960      2  Winter  McAllen
...          ...      ...   ...    ...     ...      ...
18111 2002-01-04    28.94  2002      1  Winter  McAllen
18839 2004-02-17    30.92  2004      2  Winter  McAllen
19139 2004-12-25    26.06  2004     12  Winter  McAllen
19140 2004-12-26    24.98  2004     12  Winter  McAllen
19141 2004-12-27    30.92  2004     12  Winter  McAllen
20866 2009-12-05    32.00  2009     12  Winter  McAllen
20900 2010-01-09    28.04  2010      1  Winter  McAllen
20901 2010-01-10    26.96  2010      1  Winter  McAllen
20902 2010-01-11    32.00  2010      1  Winter  McAllen
21219 2010-12-26    32.00  2010     12  Winter  McAllen
21220 2010-12-27    32.00  2010     12  Winter  McAllen
21254 2011-02-02    30.02  2011      2  Winter  McAllen
21255 2011-02-03    26.06  2011      2  Winter  McAllen
21256 2011-02-05    26.06  2011      2  Winter  McAllen
21257 2011-02-06    26.96  2011      2  Winter  McAllen
21258 2011-02-07    26.96  2011      2  Winter  McAllen
21259 2011-02-08    26.96  2011      2  Winter  McAllen
21261 2011-02-10    30.92  2011      2  Winter  McAllen
21262 2011-02-11    28.94  2011      2  Winter  McAllen
21263 2011-02-12    30.92  2011      2  Winter  McAllen
22233 2014-01-25    21.92  2014      1  Winter  McAllen
22237 2014-01-29    32.00  2014      1  Winter  McAllen
22879 2016-01-08     8.06  2016      1  Winter  McAllen
23216 2017-01-07    30.92  2017      1  Winter  McAllen
23217 2017-01-08    28.94  2017      1  Winter  McAllen
23497 2018-01-17    32.00  2018      1  Winter  McAllen
23498 2018-01-18    32.00  2018      1  Winter  McAllen
24182 2020-02-06    32.00  2020      2  Winter  McAllen
24187 2020-02-12    32.00  2020      2  Winter  McAllen
24193 2020-02-22    30.02  2020      2  Winter  McAllen

[199 rows x 6 columns]

In [31]:
worst_cities[np.isnan(worst_cities.growing_season)]

    year  startdate    enddate frost_season  growing_season     city  rank
2   1952        NaT        NaT          NaT             NaN  McAllen     5
6   1956 1956-11-30        NaT          NaT             NaN  McAllen     5
27  1977        NaT        NaT          NaT             NaN  McAllen     5
29  1979        NaT 1980-03-03          NaT             NaN  McAllen     5
30  1980        NaT        NaT          NaT             NaN  McAllen     5
32  1982        NaT        NaT          NaT             NaN  McAllen     5
36  1986        NaT        NaT          NaT             NaN  McAllen     5
37  1987        NaT        NaT          NaT             NaN  McAllen     5
38  1988        NaT 1989-02-08          NaT             NaN  McAllen     5
41  1991        NaT        NaT          NaT             NaN  McAllen     5
42  1992        NaT        NaT          NaT             NaN  McAllen     5
43  1993        NaT        NaT          NaT             NaN  McAllen     5
44  1994        NaT        NaT          NaT             NaN  McAllen     5
47  1997        NaT 1998-02-09          NaT             NaN  McAllen     5
48  1998        NaT        NaT          NaT             NaN  McAllen     5
49  1999        NaT        NaT          NaT             NaN  McAllen     5
50  2000        NaT        NaT          NaT             NaN  McAllen     5
52  2002        NaT        NaT          NaT             NaN  McAllen     5
53  2003        NaT 2004-02-17          NaT             NaN  McAllen     5
55  2005        NaT        NaT          NaT             NaN  McAllen     5
56  2006        NaT        NaT          NaT             NaN  McAllen     5
57  2007        NaT        NaT          NaT             NaN  McAllen     5
58  2008        NaT        NaT          NaT             NaN  McAllen     5
61  2011        NaT        NaT          NaT             NaN  McAllen     5
62  2012        NaT        NaT          NaT             NaN  McAllen     5
64  2014        NaT        NaT          NaT             NaN  McAllen     5
68  2018        NaT        NaT          NaT             NaN  McAllen     5
69  2019        NaT 2020-02-22          NaT             NaN  McAllen     5

In [33]:
worst_cities.to_csv('worst_cities.csv')

In [ ]:
stockton = 'GHCND:USW00023237'
saltlake = 'GHCND:USW00024127'
seattle = 'GHCND:USW00024233'
provo = 'GHCND:USC00427064'
provo = 'GHCND:USC00426538'
provo = 'GHCND:USC00426919'
# durham = 'GHCND:USC00312515'
# durham = 'GHCND:USW00003758'
# durham = 'GHCND:USC00312993'
durham = 'GHCND:USW00013722'
best_cities = [stockton, saltlake, seattle, provo, durham, milwaukee]

best_labels = ['Stockton','Salt Lake City', 'Seattle', 'Provo','Durham', 'Milwaukee']

In [34]:
#initialize lists to store data
dates_array = []
temps_array = []
#for each year from 2015-2019 ...
for city in best_cities:
    print(city)
    dates_temp = []
    temps = []
    for year in range(1950, 2021):
        year = str(year)
        print('working on year '+year)
        r = requests.get('https://www.ncdc.noaa.gov/cdo-web/api/v2/data?datasetid=GHCND&datatypeid=TMIN&limit=1000&stationid='+city+'&startdate='+year+'-01-01&enddate='+year+'-12-31', headers={'token':token})
        d = json.loads(r.text)
        min_temps = [item for item in d['results'] if item['datatype']=='TMIN']
        dates_temp += [item['date'] for item in min_temps]
        temps += [item['value'] for item in min_temps]
    dates_array.append([datetime.strptime(d, "%Y-%m-%dT%H:%M:%S") for d in dates_temp])
    temps_array.append([float(v)/10.0*1.8 + 32 for v in temps])

GHCND:USW00023237
working on year 1950
working on year 1951
working on year 1952
working on year 1953
working on year 1954
working on year 1955
working on year 1956
working on year 1957
working on year 1958
working on year 1959
working on year 1960
working on year 1961
working on year 1962
working on year 1963
working on year 1964
working on year 1965
working on year 1966
working on year 1967
working on year 1968
working on year 1969
working on year 1970
working on year 1971
working on year 1972
working on year 1973
working on year 1974
working on year 1975
working on year 1976
working on year 1977
working on year 1978
working on year 1979
working on year 1980
working on year 1981
working on year 1982
working on year 1983
working on year 1984
working on year 1985
working on year 1986
working on year 1987
working on year 1988
working on year 1989
working on year 1990
working on year 1991
working on year 1992
working on year 1993
working on year 1994
working on year 1995
working on year 1996
working on year 1997
working on year 1998
working on year 1999
working on year 2000
working on year 2001
working on year 2002
working on year 2003
working on year 2004
working on year 2005
working on year 2006
working on year 2007
working on year 2008
working on year 2009
working on year 2010
working on year 2011
working on year 2012
working on year 2013
working on year 2014
working on year 2015
working on year 2016
working on year 2017
working on year 2018
working on year 2019
working on year 2020
GHCND:USW00024127
working on year 1950
working on year 1951
working on year 1952
working on year 1953
working on year 1954
working on year 1955
working on year 1956
working on year 1957
working on year 1958
working on year 1959
working on year 1960
working on year 1961
working on year 1962
working on year 1963
working on year 1964
working on year 1965
working on year 1966
working on year 1967
working on year 1968
working on year 1969
working on year 1970
working on year 1971
working on year 1972
working on year 1973
working on year 1974
working on year 1975
working on year 1976
working on year 1977
working on year 1978
working on year 1979
working on year 1980
working on year 1981
working on year 1982
working on year 1983
working on year 1984
working on year 1985
working on year 1986
working on year 1987
working on year 1988
working on year 1989
working on year 1990
working on year 1991
working on year 1992
working on year 1993
working on year 1994
working on year 1995
working on year 1996
working on year 1997
working on year 1998
working on year 1999
working on year 2000
working on year 2001
working on year 2002
working on year 2003
working on year 2004
working on year 2005
working on year 2006
working on year 2007
working on year 2008
working on year 2009
working on year 2010
working on year 2011
working on year 2012
working on year 2013
working on year 2014
working on year 2015
working on year 2016
working on year 2017
working on year 2018
working on year 2019
working on year 2020
GHCND:USW00024233
working on year 1950
working on year 1951
working on year 1952
working on year 1953
working on year 1954
working on year 1955
working on year 1956
working on year 1957
working on year 1958
working on year 1959
working on year 1960
working on year 1961
working on year 1962
working on year 1963
working on year 1964
working on year 1965
working on year 1966
working on year 1967
working on year 1968
working on year 1969
working on year 1970
working on year 1971
working on year 1972
working on year 1973
working on year 1974
working on year 1975
working on year 1976
working on year 1977
working on year 1978
working on year 1979
working on year 1980
working on year 1981
working on year 1982
working on year 1983
working on year 1984
working on year 1985
working on year 1986
working on year 1987
working on year 1988
working on year 1989
working on year 1990
working on year 1991
working on year 1992
working on year 1993
working on year 1994
working on year 1995
working on year 1996
working on year 1997
working on year 1998
working on year 1999
working on year 2000
working on year 2001
working on year 2002
working on year 2003
working on year 2004
working on year 2005
working on year 2006
working on year 2007
working on year 2008
working on year 2009
working on year 2010
working on year 2011
working on year 2012
working on year 2013
working on year 2014
working on year 2015
working on year 2016
working on year 2017
working on year 2018
working on year 2019
working on year 2020
GHCND:USC00426919
working on year 1950
working on year 1951
working on year 1952
working on year 1953
working on year 1954
working on year 1955
working on year 1956
working on year 1957
working on year 1958
working on year 1959
working on year 1960
working on year 1961
working on year 1962
working on year 1963
working on year 1964
working on year 1965
working on year 1966
working on year 1967
working on year 1968
working on year 1969
working on year 1970
working on year 1971
working on year 1972
working on year 1973
working on year 1974
working on year 1975
working on year 1976
working on year 1977
working on year 1978
working on year 1979
working on year 1980
working on year 1981
working on year 1982
working on year 1983
working on year 1984
working on year 1985
working on year 1986
working on year 1987
working on year 1988
working on year 1989
working on year 1990
working on year 1991
working on year 1992
working on year 1993
working on year 1994
working on year 1995
working on year 1996
working on year 1997
working on year 1998
working on year 1999
working on year 2000
working on year 2001
working on year 2002
working on year 2003
working on year 2004
working on year 2005
working on year 2006
working on year 2007
working on year 2008
working on year 2009
working on year 2010
working on year 2011
working on year 2012
working on year 2013
working on year 2014
working on year 2015
working on year 2016
working on year 2017
working on year 2018
working on year 2019
working on year 2020
GHCND:USW00013722
working on year 1950
working on year 1951
working on year 1952
working on year 1953
working on year 1954
working on year 1955
working on year 1956
working on year 1957
working on year 1958
working on year 1959
working on year 1960
working on year 1961
working on year 1962
working on year 1963
working on year 1964
working on year 1965
working on year 1966
working on year 1967
working on year 1968
working on year 1969
working on year 1970
working on year 1971
working on year 1972
working on year 1973
working on year 1974
working on year 1975
working on year 1976
working on year 1977
working on year 1978
working on year 1979
working on year 1980
working on year 1981
working on year 1982
working on year 1983
working on year 1984
working on year 1985
working on year 1986
working on year 1987
working on year 1988
working on year 1989
working on year 1990
working on year 1991
working on year 1992
working on year 1993
working on year 1994
working on year 1995
working on year 1996
working on year 1997
working on year 1998
working on year 1999
working on year 2000
working on year 2001
working on year 2002
working on year 2003
working on year 2004
working on year 2005
working on year 2006
working on year 2007
working on year 2008
working on year 2009
working on year 2010
working on year 2011
working on year 2012
working on year 2013
working on year 2014
working on year 2015
working on year 2016
working on year 2017
working on year 2018
working on year 2019
working on year 2020
GHCND:USW00014839
working on year 1950
working on year 1951
working on year 1952
working on year 1953
working on year 1954
working on year 1955
working on year 1956
working on year 1957
working on year 1958
working on year 1959
working on year 1960
working on year 1961
working on year 1962
working on year 1963
working on year 1964
working on year 1965
working on year 1966
working on year 1967
working on year 1968
working on year 1969
working on year 1970
working on year 1971
working on year 1972
working on year 1973
working on year 1974
working on year 1975
working on year 1976
working on year 1977
working on year 1978
working on year 1979

working on year 1980
working on year 1981
working on year 1982
working on year 1983
working on year 1984
working on year 1985
working on year 1986
working on year 1987
working on year 1988
working on year 1989
working on year 1990
working on year 1991
working on year 1992
working on year 1993
working on year 1994
working on year 1995
working on year 1996
working on year 1997
working on year 1998
working on year 1999
working on year 2000
working on year 2001
working on year 2002
working on year 2003
working on year 2004
working on year 2005
working on year 2006
working on year 2007
working on year 2008
working on year 2009
working on year 2010
working on year 2011
working on year 2012
working on year 2013
working on year 2014
working on year 2015
working on year 2016
working on year 2017
working on year 2018
working on year 2019
working on year 2020

In [35]:
df_array = []
for i in range(len(dates_array)):
    df_temp = pd.DataFrame()
    df_temp['date'] = dates_array[i]
    df_temp['minTemp'] = temps_array[i]
    df_temp['year'] = pd.DatetimeIndex(df_temp['date']).year
    df_temp['month'] = pd.DatetimeIndex(df_temp['date']).month
    df_temp['season'] = df_temp.apply(lambda row: label_season(row), axis=1)
    df_temp['city'] = best_labels[i]
    df_array.append(df_temp)

In [36]:
mega_df = pd.concat(df_array)
mega_df[mega_df.city == "Seattle"]

            date  minTemp  year  month  season     city
0     1950-01-01    24.08  1950      1  Winter  Seattle
1     1950-01-02     6.08  1950      1  Winter  Seattle
2     1950-01-03     6.08  1950      1  Winter  Seattle
3     1950-01-04    14.00  1950      1  Winter  Seattle
4     1950-01-05    21.92  1950      1  Winter  Seattle
5     1950-01-06    35.06  1950      1  Winter  Seattle
6     1950-01-07    33.08  1950      1  Winter  Seattle
7     1950-01-08    30.92  1950      1  Winter  Seattle
8     1950-01-09    30.02  1950      1  Winter  Seattle
9     1950-01-10    30.92  1950      1  Winter  Seattle
10    1950-01-11    28.94  1950      1  Winter  Seattle
11    1950-01-12    17.96  1950      1  Winter  Seattle
12    1950-01-13    10.94  1950      1  Winter  Seattle
13    1950-01-14     8.06  1950      1  Winter  Seattle
14    1950-01-15    15.08  1950      1  Winter  Seattle
15    1950-01-16    12.92  1950      1  Winter  Seattle
16    1950-01-17    15.08  1950      1  Winter  Seattle
17    1950-01-18     8.96  1950      1  Winter  Seattle
18    1950-01-19    24.08  1950      1  Winter  Seattle
19    1950-01-20    37.04  1950      1  Winter  Seattle
20    1950-01-21    42.08  1950      1  Winter  Seattle
21    1950-01-22    35.96  1950      1  Winter  Seattle
22    1950-01-23    24.98  1950      1  Winter  Seattle
23    1950-01-24    10.04  1950      1  Winter  Seattle
24    1950-01-25     6.98  1950      1  Winter  Seattle
25    1950-01-26    21.02  1950      1  Winter  Seattle
26    1950-01-27    19.04  1950      1  Winter  Seattle
27    1950-01-28     6.98  1950      1  Winter  Seattle
28    1950-01-29     6.08  1950      1  Winter  Seattle
29    1950-01-30     6.98  1950      1  Winter  Seattle
...          ...      ...   ...    ...     ...      ...
25692 2020-05-05    48.92  2020      5  Spring  Seattle
25693 2020-05-06    48.02  2020      5  Spring  Seattle
25694 2020-05-07    44.06  2020      5  Spring  Seattle
25695 2020-05-08    50.00  2020      5  Spring  Seattle
25696 2020-05-09    62.06  2020      5  Spring  Seattle
25697 2020-05-10    62.06  2020      5  Spring  Seattle
25698 2020-05-11    53.96  2020      5  Spring  Seattle
25699 2020-05-12    50.00  2020      5  Spring  Seattle
25700 2020-05-13    51.98  2020      5  Spring  Seattle
25701 2020-05-14    50.00  2020      5  Spring  Seattle
25702 2020-05-15    51.98  2020      5  Spring  Seattle
25703 2020-05-16    53.96  2020      5  Spring  Seattle
25704 2020-05-17    53.06  2020      5  Spring  Seattle
25705 2020-05-18    50.00  2020      5  Spring  Seattle
25706 2020-05-19    51.98  2020      5  Spring  Seattle
25707 2020-05-20    51.08  2020      5  Spring  Seattle
25708 2020-05-21    46.94  2020      5  Spring  Seattle
25709 2020-05-22    46.94  2020      5  Spring  Seattle
25710 2020-05-23    48.02  2020      5  Spring  Seattle
25711 2020-05-24    50.00  2020      5  Spring  Seattle
25712 2020-05-25    55.04  2020      5  Spring  Seattle
25713 2020-05-26    51.98  2020      5  Spring  Seattle
25714 2020-05-27    48.02  2020      5  Spring  Seattle
25715 2020-05-28    57.02  2020      5  Spring  Seattle
25716 2020-05-29    57.92  2020      5  Spring  Seattle
25717 2020-05-30    50.00  2020      5  Spring  Seattle
25718 2020-05-31    48.92  2020      5  Spring  Seattle
25719 2020-06-01    50.00  2020      6  Summer  Seattle
25720 2020-06-02    50.00  2020      6  Summer  Seattle
25721 2020-06-03    50.00  2020      6  Summer  Seattle

[25722 rows x 6 columns]

In [37]:
years = range(1950,2020)
startdates_array = []
enddates_array = []
frost_array = []
growing_array = []
for label in best_labels:
    df_temp = mega_df[mega_df.city==label]
    startdates = []
    enddates = []
    frost = []
    growing = []
    for year in years:
        #print(year)
        start = np.min(df_temp[(df_temp.year == year) & (df_temp.season == 'Fall') & (df_temp.minTemp <= 32)].date)
        end = np.max(df_temp[(df_temp.year == year+1) & (df_temp.season == 'Spring') & (df_temp.minTemp <= 32)].date)
        if pd.isnull(start):
            start = np.min(df_temp[(df_temp.year == year) & (df_temp.month == 12) & (df_temp.minTemp <= 32)].date)
            if pd.isnull(start):
                start = np.min(df_temp[(df_temp.year == year+1) & (df_temp.month == 1) & (df_temp.minTemp <= 32)].date)
        if pd.isnull(end):
            end = np.max(df_temp[(df_temp.year == year+1) & (df_temp.month == 2) & (df_temp.minTemp <= 32)].date)
            if pd.isnull(end):
                end = np.max(df_temp[(df_temp.year == year+1) & (df_temp.month == 1) & (df_temp.minTemp <= 32)].date)
                if pd.isnull(end):
                    end = end = np.max(df_temp[(df_temp.year == year) & (df_temp.month == 12) & (df_temp.minTemp <= 32)].date)
        startdates.append(start)
        enddates.append(end)
        length = end - start
        grow = 365 - length.days
        frost.append(length)
        growing.append(grow)
    startdates_array.append(startdates)
    enddates_array.append(enddates)
    frost_array.append(frost)
    growing_array.append(growing)

In [38]:
tempdf_array = []
for i in range(len(startdates_array)):
    tempdf = pd.DataFrame()
    tempdf['year'] = years
    tempdf['startdate'] = startdates_array[i]
    tempdf['enddate'] = enddates_array[i]
    tempdf['frost_season'] = frost_array[i]
    tempdf['growing_season'] = growing_array[i]
    tempdf['city'] = best_labels[i]
    tempdf['rank'] = 95+i +1
    tempdf_array.append(tempdf)

In [39]:
len(best_labels)

6

In [41]:
best_cities = pd.concat(tempdf_array)
# best_cities[np.isnan(best_cities.growing_season)]
best_cities

    year  startdate    enddate frost_season  growing_season       city  rank
0   1950 1951-01-06 1951-03-11      64 days           301.0   Stockton    96
1   1951 1951-12-07 1952-03-20     104 days           261.0   Stockton    96
2   1952 1952-11-17 1953-03-14     117 days           248.0   Stockton    96
3   1953 1953-12-12 1954-03-14      92 days           273.0   Stockton    96
4   1954 1954-11-18 1955-03-21     123 days           242.0   Stockton    96
5   1955 1955-11-24 1956-03-07     104 days           261.0   Stockton    96
6   1956 1956-11-20 1957-02-05      77 days           288.0   Stockton    96
7   1957 1957-11-23 1958-03-01      98 days           267.0   Stockton    96
8   1958 1958-11-16 1959-02-09      85 days           280.0   Stockton    96
9   1959 1959-11-15 1960-03-02     108 days           257.0   Stockton    96
10  1960 1960-12-06 1961-03-07      91 days           274.0   Stockton    96
11  1961 1961-11-17 1962-02-28     103 days           262.0   Stockton    96
12  1962 1962-11-30 1963-03-18     108 days           257.0   Stockton    96
13  1963 1963-12-10 1964-04-24     136 days           229.0   Stockton    96
14  1964 1964-11-16 1965-02-12      88 days           277.0   Stockton    96
15  1965 1965-11-28 1966-03-17     109 days           256.0   Stockton    96
16  1966 1966-12-27 1967-03-05      68 days           297.0   Stockton    96
17  1967 1967-12-09 1968-01-28      50 days           315.0   Stockton    96
18  1968 1968-11-29 1969-03-14     105 days           260.0   Stockton    96
19  1969 1969-11-18 1970-02-19      93 days           272.0   Stockton    96
20  1970 1970-12-24 1971-03-06      72 days           293.0   Stockton    96
21  1971 1971-11-17 1972-02-03      78 days           287.0   Stockton    96
22  1972 1972-12-05 1973-01-27      53 days           312.0   Stockton    96
23  1973 1974-01-02 1974-02-09      38 days           327.0   Stockton    96
24  1974 1974-11-28 1975-02-23      87 days           278.0   Stockton    96
25  1975 1975-11-19 1976-04-17     150 days           215.0   Stockton    96
26  1976 1976-11-28 1977-03-14     106 days           259.0   Stockton    96
27  1977 1977-11-19 1978-01-24      66 days           299.0   Stockton    96
28  1978 1978-11-12 1979-02-04      84 days           281.0   Stockton    96
29  1979 1979-12-12 1980-02-08      58 days           307.0   Stockton    96
..   ...        ...        ...          ...             ...        ...   ...
40  1990 1990-10-19 1991-04-11     174 days           191.0  Milwaukee   101
41  1991 1991-10-19 1992-04-28     192 days           173.0  Milwaukee   101
42  1992 1992-10-17 1993-04-21     186 days           179.0  Milwaukee   101
43  1993 1993-10-10 1994-04-30     202 days           163.0  Milwaukee   101
44  1994 1994-11-19 1995-04-09     141 days           224.0  Milwaukee   101
45  1995 1995-09-23 1996-05-13     233 days           132.0  Milwaukee   101
46  1996 1996-10-30 1997-05-16     198 days           167.0  Milwaukee   101
47  1997 1997-10-22 1998-04-10     170 days           195.0  Milwaukee   101
48  1998 1998-11-04 1999-04-25     172 days           193.0  Milwaukee   101
49  1999 1999-10-24 2000-04-12     171 days           194.0  Milwaukee   101
50  2000 2000-10-07 2001-04-18     193 days           172.0  Milwaukee   101
51  2001 2001-10-06 2002-05-04     210 days           155.0  Milwaukee   101
52  2002 2002-10-16 2003-04-24     190 days           175.0  Milwaukee   101
53  2003 2003-10-02 2004-05-03     214 days           151.0  Milwaukee   101
54  2004 2004-10-05 2005-04-29     206 days           159.0  Milwaukee   101
55  2005 2005-11-10 2006-04-09     150 days           215.0  Milwaukee   101
56  2006 2006-10-12 2007-04-15     185 days           180.0  Milwaukee   101
57  2007 2007-11-02 2008-04-30     180 days           185.0  Milwaukee   101
58  2008 2008-10-29 2009-04-22     175 days           190.0  Milwaukee   101
59  2009 2009-10-10 2010-04-28     200 days           165.0  Milwaukee   101
60  2010 2010-10-22 2011-04-18     178 days           187.0  Milwaukee   101
61  2011 2011-10-29 2012-04-12     166 days           199.0  Milwaukee   101
62  2012 2012-10-27 2013-04-21     176 days           189.0  Milwaukee   101
63  2013 2013-10-22 2014-04-16     176 days           189.0  Milwaukee   101
64  2014 2014-10-30 2015-04-24     176 days           189.0  Milwaukee   101
65  2015 2015-11-08 2016-04-12     156 days           209.0  Milwaukee   101
66  2016 2016-11-12 2017-03-29     137 days           228.0  Milwaukee   101
67  2017 2017-11-06 2018-04-29     174 days           191.0  Milwaukee   101
68  2018 2018-10-13 2019-04-28     197 days           168.0  Milwaukee   101
69  2019 2019-10-29 2020-05-09     193 days           172.0  Milwaukee   101

[420 rows x 7 columns]

In [153]:
(mega_df[(mega_df.city == "Stockton") & (mega_df.year == 1995)])

            date  minTemp  year  month  season      city
16423 1995-01-01    37.94  1995      1  Winter  Stockton
16424 1995-01-02    39.92  1995      1  Winter  Stockton
16425 1995-01-03    44.06  1995      1  Winter  Stockton
16426 1995-01-04    46.94  1995      1  Winter  Stockton
16427 1995-01-05    46.04  1995      1  Winter  Stockton
16428 1995-01-06    44.06  1995      1  Winter  Stockton
16429 1995-01-07    51.98  1995      1  Winter  Stockton
16430 1995-01-08    53.96  1995      1  Winter  Stockton
16431 1995-01-09    59.00  1995      1  Winter  Stockton
16432 1995-01-10    51.98  1995      1  Winter  Stockton
16433 1995-01-11    48.02  1995      1  Winter  Stockton
16434 1995-01-12    51.98  1995      1  Winter  Stockton
16435 1995-01-13    55.94  1995      1  Winter  Stockton
16436 1995-01-14    48.92  1995      1  Winter  Stockton
16437 1995-01-15    44.06  1995      1  Winter  Stockton
16438 1995-01-16    39.92  1995      1  Winter  Stockton
16439 1995-01-17    35.96  1995      1  Winter  Stockton
16440 1995-01-18    39.02  1995      1  Winter  Stockton
16441 1995-01-19    35.96  1995      1  Winter  Stockton
16442 1995-01-20    39.02  1995      1  Winter  Stockton
16443 1995-01-21    44.06  1995      1  Winter  Stockton
16444 1995-01-22    48.92  1995      1  Winter  Stockton
16445 1995-01-23    51.08  1995      1  Winter  Stockton
16446 1995-01-24    51.08  1995      1  Winter  Stockton
16447 1995-01-25    50.00  1995      1  Winter  Stockton
16448 1995-01-26    42.98  1995      1  Winter  Stockton
16449 1995-01-27    48.92  1995      1  Winter  Stockton
16450 1995-01-28    51.98  1995      1  Winter  Stockton
16451 1995-01-29    48.02  1995      1  Winter  Stockton
16452 1995-01-30    51.98  1995      1  Winter  Stockton
...          ...      ...   ...    ...     ...       ...
16758 1995-12-02    42.98  1995     12  Winter  Stockton
16759 1995-12-03    37.94  1995     12  Winter  Stockton
16760 1995-12-04    51.98  1995     12  Winter  Stockton
16761 1995-12-05    48.92  1995     12  Winter  Stockton
16762 1995-12-06    46.04  1995     12  Winter  Stockton
16763 1995-12-07    48.02  1995     12  Winter  Stockton
16764 1995-12-08    42.98  1995     12  Winter  Stockton
16765 1995-12-09    51.08  1995     12  Winter  Stockton
16766 1995-12-10    48.92  1995     12  Winter  Stockton
16767 1995-12-11    51.98  1995     12  Winter  Stockton
16768 1995-12-12    51.08  1995     12  Winter  Stockton
16769 1995-12-13    48.92  1995     12  Winter  Stockton
16770 1995-12-14    42.08  1995     12  Winter  Stockton
16771 1995-12-15    44.96  1995     12  Winter  Stockton
16772 1995-12-16    42.08  1995     12  Winter  Stockton
16773 1995-12-17    33.98  1995     12  Winter  Stockton
16774 1995-12-18    44.06  1995     12  Winter  Stockton
16775 1995-12-19    42.08  1995     12  Winter  Stockton
16776 1995-12-20    39.02  1995     12  Winter  Stockton
16777 1995-12-21    35.96  1995     12  Winter  Stockton
16778 1995-12-22    39.02  1995     12  Winter  Stockton
16779 1995-12-23    39.02  1995     12  Winter  Stockton
16780 1995-12-24    33.98  1995     12  Winter  Stockton
16781 1995-12-25    33.08  1995     12  Winter  Stockton
16782 1995-12-26    35.06  1995     12  Winter  Stockton
16783 1995-12-27    39.02  1995     12  Winter  Stockton
16784 1995-12-28    44.06  1995     12  Winter  Stockton
16785 1995-12-29    46.94  1995     12  Winter  Stockton
16786 1995-12-30    50.00  1995     12  Winter  Stockton
16787 1995-12-31    50.00  1995     12  Winter  Stockton

[365 rows x 6 columns]

In [155]:
best_cities[best_cities.city == 'Provo']

    year  startdate    enddate frost_season  growing_season   city  rank
0   1950 1950-09-27 1951-05-13     228 days           137.0  Provo    99
1   1951 1951-10-12 1952-04-13     184 days           181.0  Provo    99
2   1952 1952-10-17 1953-05-12     207 days           158.0  Provo    99
3   1953 1953-10-21 1954-05-28     219 days           146.0  Provo    99
4   1954 1954-10-14 1955-05-16     214 days           151.0  Provo    99
5   1955 1955-10-06 1956-05-14     221 days           144.0  Provo    99
6   1956 1956-10-20 1957-04-28     190 days           175.0  Provo    99
7   1957 1957-10-05 1958-04-29     206 days           159.0  Provo    99
8   1958 1958-09-25 1959-05-20     237 days           128.0  Provo    99
9   1959 1959-09-28 1960-05-24     239 days           126.0  Provo    99
10  1960 1960-10-14 1961-05-05     203 days           162.0  Provo    99
11  1961 1961-09-24 1962-05-21     239 days           126.0  Provo    99
12  1962 1962-10-15 1963-04-29     196 days           169.0  Provo    99
13  1963 1963-10-28 1964-05-12     197 days           168.0  Provo    99
14  1964 1964-10-17 1965-05-10     205 days           160.0  Provo    99
15  1965 1965-09-17 1966-05-23     248 days           117.0  Provo    99
16  1966 1966-10-04 1967-05-14     222 days           143.0  Provo    99
17  1967 1967-09-13 1968-05-16     246 days           119.0  Provo    99
18  1968 1968-09-22 1969-04-27     217 days           148.0  Provo    99
19  1969 1969-10-03 1970-05-11     220 days           145.0  Provo    99
20  1970 1970-09-25 1971-05-18     235 days           130.0  Provo    99
21  1971 1971-09-18 1972-05-02     227 days           138.0  Provo    99
22  1972 1972-10-25 1973-05-02     189 days           176.0  Provo    99
23  1973 1973-10-04 1974-05-21     229 days           136.0  Provo    99
24  1974 1974-11-05 1975-05-26     202 days           163.0  Provo    99
25  1975 1975-10-15 1976-04-28     196 days           169.0  Provo    99
26  1976 1976-10-18 1977-04-21     185 days           180.0  Provo    99
27  1977 1977-10-11 1978-05-31     232 days           133.0  Provo    99
28  1978 1978-09-18 1979-05-09     233 days           132.0  Provo    99
29  1979 1979-10-22 1980-03-31     161 days           204.0  Provo    99
..   ...        ...        ...          ...             ...    ...   ...
40  1990 1990-10-08 1991-05-05     209 days           156.0  Provo    99
41  1991 1991-10-24 1992-03-20     148 days           217.0  Provo    99
42  1992 1992-11-03 1993-04-20     168 days           197.0  Provo    99
43  1993 1993-10-27 1994-04-30     185 days           180.0  Provo    99
44  1994 1994-10-29 1995-05-13     196 days           169.0  Provo    99
45  1995 1995-10-05 1996-04-29     207 days           158.0  Provo    99
46  1996 1996-10-17 1997-05-02     197 days           168.0  Provo    99
47  1997 1997-10-12 1998-04-18     188 days           177.0  Provo    99
48  1998 1998-10-06 1999-05-11     217 days           148.0  Provo    99
49  1999 1999-10-17 2000-04-02     168 days           197.0  Provo    99
50  2000 2000-11-02 2001-04-13     162 days           203.0  Provo    99
51  2001 2001-10-10 2002-05-09     211 days           154.0  Provo    99
52  2002 2002-10-13 2003-05-19     218 days           147.0  Provo    99
53  2003 2003-10-11 2004-03-29     170 days           195.0  Provo    99
54  2004 2004-10-31 2005-04-15     166 days           199.0  Provo    99
55  2005 2005-10-05 2006-04-20     197 days           168.0  Provo    99
56  2006 2006-10-18 2007-04-14     178 days           187.0  Provo    99
57  2007 2007-09-30 2008-05-13     226 days           139.0  Provo    99
58  2008 2008-10-11 2009-04-27     198 days           167.0  Provo    99
59  2009 2009-10-01 2010-05-24     235 days           130.0  Provo    99
60  2010 2010-10-27 2011-05-12     197 days           168.0  Provo    99
61  2011 2011-10-26 2012-04-28     185 days           180.0  Provo    99
62  2012 2012-10-07 2013-05-01     206 days           159.0  Provo    99
63  2013 2013-09-28 2014-04-29     213 days           152.0  Provo    99
64  2014 2014-10-27 2015-04-17     172 days           193.0  Provo    99
65  2015 2015-11-06 2015-12-31      55 days           310.0  Provo    99
66  2016 2017-01-01 2017-04-10      99 days           266.0  Provo    99
67  2017 2017-10-13 2018-04-18     187 days           178.0  Provo    99
68  2018 2018-10-15 2019-05-01     198 days           167.0  Provo    99
69  2019 2019-10-09 2020-03-28     171 days           194.0  Provo    99

[70 rows x 7 columns]

In [42]:
best_cities.to_csv('best_cities.csv')

In [ ]:
mega_df = pd.concat(df_array)
mega_df

In [116]:
# best_cities.to_csv('best_cities.csv')

In [6]:
best_cities = pd.read_csv('best_cities.csv')
worst_cities = pd.read_csv('worst_cities.csv')
best_cities

,Unnamed: 0,year,startdate,enddate,frost_season,growing_season,city,rank
0,0,1950,1951-01-06,1951-03-11,64 days 00:00:00.000000000,301.0,Stockton,96
1,1,1951,1951-12-07,1952-03-20,104 days 00:00:00.000000000,261.0,Stockton,96
2,2,1952,1952-11-17,1953-03-14,117 days 00:00:00.000000000,248.0,Stockton,96
3,3,1953,1953-12-12,1954-03-14,92 days 00:00:00.000000000,273.0,Stockton,96
4,4,1954,1954-11-18,1955-03-21,123 days 00:00:00.000000000,242.0,Stockton,96
5,5,1955,1955-11-24,1956-03-07,104 days 00:00:00.000000000,261.0,Stockton,96
6,6,1956,1956-11-20,1957-02-05,77 days 00:00:00.000000000,288.0,Stockton,96
7,7,1957,1957-11-23,1958-03-01,98 days 00:00:00.000000000,267.0,Stockton,96
8,8,1958,1958-11-16,1959-02-09,85 days 00:00:00.000000000,280.0,Stockton,96
9,9,1959,1959-11-15,1960-03-02,108 days 00:00:00.000000000,257.0,Stockton,96
10,10,1960,1960-12-06,1961-03-07,91 days 00:00:00.000000000,274.0,Stockton,96
11,11,1961,1961-11-17,1962-02-28,103 days 00:00:00.000000000,262.0,Stockton,96
12,12,1962,1962-11-30,1963-03-18,108 days 00:00:00.000000000,257.0,Stockton,96
13,13,1963,1963-12-10,1964-04-24,136 days 00:00:00.000000000,229.0,Stockton,96
14,14,1964,1964-11-16,1965-02-12,88 days 00:00:00.000000000,277.0,Stockton,96
15,15,1965,1965-11-28,1966-03-17,109 days 00:00:00.000000000,256.0,Stockton,96
16,16,1966,1966-12-27,1967-03-05,68 days 00:00:00.000000000,297.0,Stockton,96
17,17,1967,1967-12-09,1968-01-28,50 days 00:00:00.000000000,315.0,Stockton,96
18,18,1968,1968-11-29,1969-03-14,105 days 00:00:00.000000000,260.0,Stockton,96
19,19,1969,1969-11-18,1970-02-19,93 days 00:00:00.000000000,272.0,Stockton,96
20,20,1970,1970-12-24,1971-03-06,72 days 00:00:00.000000000,293.0,Stockton,96
21,21,1971,1971-11-17,1972-02-03,78 days 00:00:00.000000000,287.0,Stockton,96
22,22,1972,1972-12-05,1973-01-27,53 days 00:00:00.000000000,312.0,Stockton,96
23,23,1973,1974-01-02,1974-02-09,38 days 00:00:00.000000000,327.0,Stockton,96
24,24,1974,1974-11-28,1975-02-23,87 days 00:00:00.000000000,278.0,Stockton,96
25,25,1975,1975-11-19,1976-04-17,150 days 00:00:00.000000000,215.0,Stockton,96
26,26,1976,1976-11-28,1977-03-14,106 days 00:00:00.000000000,259.0,Stockton,96
27,27,1977,1977-11-19,1978-01-24,66 days 00:00:00.000000000,299.0,Stockton,96
28,28,1978,1978-11-12,1979-02-04,84 days 00:00:00.000000000,281.0,Stockton,96
29,29,1979,1979-12-12,1980-02-08,58 days 00:00:00.000000000,307.0,Stockton,96
...,...,...,...,...,...,...,...,...
390,40,1990,1990-10-19,1991-04-11,174 days 00:00:00.000000000,191.0,Milwaukee,101
391,41,1991,1991-10-19,1992-04-28,192 days 00:00:00.000000000,173.0,Milwaukee,101
392,42,1992,1992-10-17,1993-04-21,186 days 00:00:00.000000000,179.0,Milwaukee,101
393,43,1993,1993-10-10,1994-04-30,202 days 00:00:00.000000000,163.0,Milwaukee,101
394,44,1994,1994-11-19,1995-04-09,141 days 00:00:00.000000000,224.0,Milwaukee,101
395,45,1995,1995-09-23,1996-05-13,233 days 00:00:00.000000000,132.0,Milwaukee,101
396,46,1996,1996-10-30,1997-05-16,198 days 00:00:00.000000000,167.0,Milwaukee,101
397,47,1997,1997-10-22,1998-04-10,170 days 00:00:00.000000000,195.0,Milwaukee,101
398,48,1998,1998-11-04,1999-04-25,172 days 00:00:00.000000000,193.0,Milwaukee,101
399,49,1999,1999-10-24,2000-04-12,171 days 00:00:00.000000000,194.0,Milwaukee,101
400,50,2000,2000-10-07,2001-04-18,193 days 00:00:00.000000000,172.0,Milwaukee,101
401,51,2001,2001-10-06,2002-05-04,210 days 00:00:00.000000000,155.0,Milwaukee,101
402,52,2002,2002-10-16,2003-04-24,190 days 00:00:00.000000000,175.0,Milwaukee,101
403,53,2003,2003-10-02,2004-05-03,214 days 00:00:00.000000000,151.0,Milwaukee,101
404,54,2004,2004-10-05,2005-04-29,206 days 00:00:00.000000000,159.0,Milwaukee,101
405,55,2005,2005-11-10,2006-04-09,150 days 00:00:00.000000000,215.0,Milwaukee,101
406,56,2006,2006-10-12,2007-04-15,185 days 00:00:00.000000000,180.0,Milwaukee,101
407,57,2007,2007-11-02,2008-04-30,180 days 00:00:00.000000000,185.0,Milwaukee,101
408,58,2008,2008-10-29,2009-04-22,175 days 00:00:00.000000000,190.0,Milwaukee,101
409,59,2009,2009-10-10,2010-04-28,200 days 00:00:00.000000000,165.0,Milwaukee,101
410,60,2010,2010-10-22,2011-04-18,178 days 00:00:00.000000000,187.0,Milwaukee,101
411,61,2011,2011-10-29,2012-04-12,166 days 00:00:00.000000000,199.0,Milwaukee,101
412,62,2012,2012-10-27,2013-04-21,176 days 00:00:00.000000000,189.0,Milwaukee,101
413,63,2013,2013-10-22,2014-04-16,176 days 00:00:00.000000000,189.0,Milwaukee,101
414,64,2014,2014-10-30,2015-04-24,176 days 00:00:00.000000000,189.0,Milwaukee,101
415,65,2015,2015-11-08,2016-04-12,156 days 00:00:00.000000000,209.0,Milwaukee,101
416,66,2016,2016-11-12,2017-03-29,137 days 00:00:00.000000000,228.0,Milwaukee,101
417,67,2017,2017-11-06,2018-04-29,174 days 00:00:00.000000000,191.0,Milwaukee,101
418,68,2018,2018-10-13,2019-04-28,197 days 00:00:00.000000000,168.0,Milwaukee,101
419,69,2019,2019-10-29,2020-05-09,193 days 00:00:00.000000000,172.0,Milwaukee,101

In [14]:
best_cities[(best_cities.year == 2019)]

,Unnamed: 0,year,startdate,enddate,frost_season,growing_season,city,rank
69,69,2019,2019-12-27,2020-02-05,40 days 00:00:00.000000000,325.0,Stockton,96
139,69,2019,2019-10-10,2020-04-14,187 days 00:00:00.000000000,178.0,Salt Lake City,97
209,69,2019,2019-11-28,2020-03-15,108 days 00:00:00.000000000,257.0,Seattle,98
279,69,2019,2019-10-09,2020-03-28,171 days 00:00:00.000000000,194.0,Provo,99
349,69,2019,2019-11-09,2020-04-11,154 days 00:00:00.000000000,211.0,Durham,100
419,69,2019,2019-10-29,2020-05-09,193 days 00:00:00.000000000,172.0,Milwaukee,101

In [15]:
best_cities[(best_cities.year == 1950)]

,Unnamed: 0,year,startdate,enddate,frost_season,growing_season,city,rank
0,0,1950,1951-01-06,1951-03-11,64 days 00:00:00.000000000,301.0,Stockton,96
70,0,1950,1950-10-01,1951-05-13,224 days 00:00:00.000000000,141.0,Salt Lake City,97
140,0,1950,1950-11-09,1951-05-01,173 days 00:00:00.000000000,192.0,Seattle,98
210,0,1950,1950-09-27,1951-05-13,228 days 00:00:00.000000000,137.0,Provo,99
280,0,1950,1950-11-05,1951-03-27,142 days 00:00:00.000000000,223.0,Durham,100
350,0,1950,1950-11-04,1951-04-20,167 days 00:00:00.000000000,198.0,Milwaukee,101

In [16]:
worst_cities[(worst_cities.year == 2019)]

,Unnamed: 0,year,startdate,enddate,frost_season,growing_season,city,rank
69,69,2019,2019-11-04,2020-05-10,188 days 00:00:00.000000000,177.0,Richmond,1
139,69,2019,2019-10-19,2020-05-13,207 days 00:00:00.000000000,158.0,Scranton,2
209,69,2019,2019-10-05,2020-05-14,222 days 00:00:00.000000000,143.0,Springfield,3
279,69,2019,2019-11-02,2020-05-10,190 days 00:00:00.000000000,175.0,Hartford,4
349,69,2019,NaN,2020-02-22,NaN,NaN,McAllen,5
419,69,2019,2019-11-08,2020-04-23,167 days 00:00:00.000000000,198.0,New Haven,6

In [17]:
worst_cities[(worst_cities.year == 1950)]

,Unnamed: 0,year,startdate,enddate,frost_season,growing_season,city,rank
0,0,1950,1950-11-06,1951-04-18,163 days 00:00:00.000000000,202.0,Richmond,1
70,0,1950,1950-10-05,1951-04-21,198 days 00:00:00.000000000,167.0,Scranton,2
140,0,1950,1950-09-25,1951-05-14,231 days 00:00:00.000000000,134.0,Springfield,3
210,0,1950,1950-09-24,1951-04-24,212 days 00:00:00.000000000,153.0,Hartford,4
280,0,1950,1950-12-06,1951-03-13,97 days 00:00:00.000000000,268.0,McAllen,5
350,0,1950,1950-10-27,1951-03-27,151 days 00:00:00.000000000,214.0,New Haven,6